### ISSUE TITLE
Problem launching many environments

### ISSUE THREAD

**Issue by mantoone** [minerllabs/minerl#113]
I have been trying to launch multiple environments to train multiple agents simultaneously. I can launch 3 environments without problems, but when I try to launch 4 I get the following error:
```
[21:33:50] [EnvServerSocketHandler/INFO]: [STDOUT]: [ERROR] Video observation is null; please notify the developer.
Exception in thread "EnvServerSocketHandler" [21:33:50] [EnvServerSocketHandler/INFO]: [STDERR]: java.lang.NullPointerException
[21:33:50] [EnvServerSocketHandler/INFO]: [STDERR]: 	at com.microsoft.Malmo.Client.MalmoEnvServer.stepSync(MalmoEnvServer.java:503)
[21:33:50] [EnvServerSocketHandler/INFO]: [STDERR]: 	at com.microsoft.Malmo.Client.MalmoEnvServer.step(MalmoEnvServer.java:530)
[21:33:50] [EnvServerSocketHandler/INFO]: [STDERR]: 	at com.microsoft.Malmo.Client.MalmoEnvServer.access$400(MalmoEnvServer.java:51)
[21:33:50] [EnvServerSocketHandler/INFO]: [STDERR]: 	at com.microsoft.Malmo.Client.MalmoEnvServer$1.run(MalmoEnvServer.java:153)
```

The env_id I used is `MineRLNavigateDense-v0`. I have tried to use `time.sleep(30)` to allow some time between the creation of each environment. The error seemed to appear before env.reset(), probably in the `gym.make('MineRLNavigateDense-v0')` part, since the window didn't get resized.

Log files:
[minecraft_proc_9000.log](https://github.com/minerllabs/minerl/files/3341015/minecraft_proc_9000.log)
[minecraft_proc_9001.log](https://github.com/minerllabs/minerl/files/3341016/minecraft_proc_9001.log)
[minecraft_proc_9002.log](https://github.com/minerllabs/minerl/files/3341017/minecraft_proc_9002.log)
[minecraft_proc_9003.log](https://github.com/minerllabs/minerl/files/3341018/minecraft_proc_9003.log)

**Comment by MadcowD** [comment]
Does this error prevent the mission from starting? I notice later in the logs it starts working?
```
[21:33:50] [Client thread/INFO]: [STDOUT]: Unpausing
[21:33:50] [Client thread/INFO]: [STDOUT]: CLIENT request state: MISSION_ABORTED
[21:33:50] [Client thread/INFO]: [CHAT] §l73...
[21:33:50] [Client thread/INFO]: [STDOUT]: CLIENT enter state: MISSION_ABORTED
[21:33:50] [EnvServerSocketHandler/INFO]: [STDOUT]: [ERROR] Video observation is null; please notify the developer.
[21:33:50] [Client thread/INFO]: [STDOUT]: inform the agent
Exception in thread "EnvServerSocketHandler" [21:33:50] [EnvServerSocketHandler/INFO]: [STDERR]: java.lang.NullPointerException
[21:33:50] [EnvServerSocketHandler/INFO]: [STDERR]: 	at com.microsoft.Malmo.Client.MalmoEnvServer.stepSync(MalmoEnvServer.java:503)
[21:33:50] [EnvServerSocketHandler/INFO]: [STDERR]: 	at com.microsoft.Malmo.Client.MalmoEnvServer.step(MalmoEnvServer.java:530)
[21:33:50] [EnvServerSocketHandler/INFO]: [STDERR]: 	at com.microsoft.Malmo.Client.MalmoEnvServer.access$400(MalmoEnvServer.java:51)
[21:33:50] [EnvServerSocketHandler/INFO]: [STDERR]: 	at com.microsoft.Malmo.Client.MalmoEnvServer$1.run(MalmoEnvServer.java:153)
[21:33:50] [EnvServerSocketHandler/INFO]: [STDOUT]: Received from localhost:<MissionInit xmlns="http://ProjectMalmo.microsoft.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" SchemaVersion="" PlatformVersion="0.37.0">
                                <Mission>
    <About>
        <Summary>Navigation through survival world.</Summary>
    </About>

    <ModSettings>
        <MsPerTick>50</MsPerTick>
    </ModSettings>

    <ServerSection>
        <ServerInitialConditions>
            <Time>
                <StartTime>6000</StartTime>
                <AllowPassageOfTime>false</AllowPassageOfTime>
            </Time>
            <Weather>clear</Weather>
            <AllowSpawning>false</AllowSpawning>
        </ServerInitialConditions>
        <ServerHandlers>
            <DefaultWorldGenerator forceReset="true"/>
            <NavigationDecorator>
                <randomPlacementProperties>
                    <maxRandomizedRadius>64</maxRandomizedRadius>
                    <minRandomizedRadius>64</minRandomizedRadius>
                    <maxRadius>8</maxRadius>
              
[21:33:50] [Client thread/INFO]: [STDOUT]: CLIENT request state: DORMANT
[21:33:50] [Client thread/INFO]: [STDOUT]: CLIENT enter state: DORMANT
[21:33:50] [Client thread/INFO]: [STDOUT]: JETTISONING 0 COMMANDS
[21:33:50] [Server thread/INFO]: [STDOUT]: SERVER request state: CLEAN_UP
[21:33:50] [Server thread/INFO]: [STDOUT]: SERVER enter state: CLEAN_UP
[21:33:50] [Server thread/INFO]: [STDOUT]: SERVER request state: DORMANT
[21:33:50] [Server thread/INFO]: [STDOUT]: SERVER enter state: DORMANT
[21:33:50] [EnvServerSocketHandler/INFO]: [STDOUT]: REPLYING WITH: MALMOOK
[21:33:50] [Client thread/INFO]: [STDOUT]: Mission received: Navigation through survival world.
[21:33:50] [Client thread/INFO]: [STDOUT]: CLIENT request state: CREATING_HANDLERS
[21:33:50] [Client thread/INFO]: [STDOUT]: CLIENT enter state: CREATING_HANDLERS
[21:33:50] [Client thread/INFO]: [STDOUT]: CLIENT request state: EVALUATING_WORLD_REQUIREMENTS
[21:33:50] [Client thread/INFO]: [STDOUT]: CLIENT enter state: EVALUATING_WORLD_REQUIREMENTS
[21:33:50] [Client thread/INFO]: [STDOUT]: CLIENT request state: PAUSING_OLD_SERVER
[21:33:50] [Client thread/INFO]: [STDOUT]: CLIENT enter state: PAUSING_OLD_SERVER
[21:33:50] [Server thread/INFO]: Saving and pausing game...
[21:33:50] [Server thread/INFO]: Saving chunks for level 'TEMP_0_c6306f57-4268-4069-8109-c5ffb618aef1'/Overworld
[21:33:51] [Server thread/INFO]: Saving chunks for level 'TEMP_0_c6306f57-4268-4069-8109-c5ffb618aef1'/Nether
[21:33:51] [Server thread/INFO]: Saving chunks for level 'TEMP_0_c6306f57-4268-4069-8109-c5ffb618aef1'/The End
[21:33:51] [Client thread/INFO]: [STDOUT]: CLIENT request state: CLOSING_OLD_SERVER
[21:33:51] [Client thread/INFO]: [STDOUT]: CLIENT enter state: CLOSING_OLD_SERVER
[21:33:51] [Client thread/INFO]: [STDOUT]: Unpausing
[21:33:51] [Server thread/INFO]: Stopping server
[21:33:51] [Server thread/INFO]: Saving players
[21:33:51] [Server thread/INFO]: MineRLAgent lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[21:33:51] [Server thread/INFO]: MineRLAgent left the game
[21:33:51] [Server thread/INFO]: Stopping singleplayer server as player logged out
[21:33:51] [Server thread/INFO]: Saving worlds
[21:33:51] [Server thread/INFO]: Saving chunks for level 'TEMP_0_c6306f57-4268-4069-8109-c5ffb618aef1'/Overworld
[21:33:51] [Server thread/INFO]: Saving chunks for level 'TEMP_0_c6306f57-4268-4069-8109-c5ffb618aef1'/Nether
[21:33:51] [Server thread/INFO]: Saving chunks for level 'TEMP_0_c6306f57-4268-4069-8109-c5ffb618aef1'/The End
[21:33:51] [Server thread/INFO]: [STDOUT]: Unpausing
[21:33:51] [Server thread/INFO]: [STDOUT]: Unpausing
[21:33:51] [Server thread/INFO]: [STDOUT]: Unpausing
[21:33:51] [Server thread/INFO]: Unloading dimension 0
[21:33:51] [Server thread/INFO]: Unloading dimension -1
[21:33:51] [Server thread/INFO]: Unloading dimension 1
[21:33:51] [Server thread/INFO]: Applying holder lookups
[21:33:51] [Server thread/INFO]: Holder lookups applied
[21:34:01] [Client thread/INFO]: [STDOUT]: CLIENT request state: CREATING_NEW_WORLD
[21:34:01] [Client thread/INFO]: [STDOUT]: CLIENT enter state: CREATING_NEW_WORLD
[21:34:02] [Server thread/INFO]: Starting integrated minecraft server version 1.11.2
[21:34:02] [Server thread/INFO]: Generating keypair
[21:34:02] [Server thread/INFO]: Injecting existing block and item data into this server instance
[21:34:02] [Server thread/INFO]: Applying holder lookups
[21:34:02] [Server thread/INFO]: Holder lookups applied
[21:34:02] [Server thread/INFO]: Loading dimension 0 (TEMP_0_4f2ded67-5488-482d-9fee-bcf06022d971) (net.minecraft.server.integrated.IntegratedServer@5e5c737e)
[21:34:02] [Server thread/INFO]: Loading dimension 1 (TEMP_0_4f2ded67-5488-482d-9fee-bcf06022d971) (net.minecraft.server.integrated.IntegratedServer@5e5c737e)
[21:34:02] [Server thread/INFO]: Loading dimension -1 (TEMP_0_4f2ded67-5488-482d-9fee-bcf06022d971) (net.minecraft.server.integrated.IntegratedServer@5e5c737e)
[21:34:02] [Server thread/INFO]: Preparing start region for level 0
[21:34:03] [Server thread/INFO]: Preparing spawn area: 13%
[21:34:04] [Server thread/INFO]: Preparing spawn area: 25%
[21:34:05] [Server thread/INFO]: Preparing spawn area: 38%
[21:34:06] [Server thread/INFO]: Preparing spawn area: 52%
[21:34:07] [Server thread/INFO]: Preparing spawn area: 65%
[21:34:08] [Server thread/INFO]: Preparing spawn area: 78%
[21:34:09] [Server thread/INFO]: Preparing spawn area: 92%
[21:34:10] [Server thread/INFO]: Changing view distance to 4, from 10
[21:34:10] [Client thread/INFO]: Deleting level TEMP_0_c6306f57-4268-4069-8109-c5ffb618aef1
[21:34:10] [Client thread/INFO]: Attempt 1...
[21:34:10] [Server thread/INFO]: [STDOUT]: SERVER request state: WAITING_FOR_MOD_READY
[21:34:10] [Netty Local Client IO #3/INFO]: Server protocol version 2
[21:34:10] [Netty Server IO #7/INFO]: Client protocol version 2
[21:34:10] [Server thread/INFO]: [STDOUT]: CLIENT request state: WAITING_FOR_SERVER_READY
[21:34:10] [Netty Server IO #7/INFO]: Client attempting to join with 5 mods : minecraft@1.11.2,FML@8.0.99.99,malmomod@0.37.0,forge@13.20.0.2228,mcp@9.19
[21:34:10] [Netty Local Client IO #3/INFO]: [Netty Local Client IO #3] Client side modded connection established
[21:34:10] [Server thread/INFO]: [STDOUT]: SERVER enter state: WAITING_FOR_MOD_READY
[21:34:10] [Client thread/INFO]: [STDOUT]: CLIENT enter state: WAITING_FOR_SERVER_READY
[21:34:10] [Server thread/INFO]: [Server thread] Server side modded connection established
[21:34:10] [Server thread/INFO]: MineRLAgent[local:E:83018a71] logged in with entity id 7743 at (53.5, 69.0, 245.5)
[21:34:10] [Server thread/INFO]: MineRLAgent joined the game
[21:34:10] [Server thread/INFO]: [STDOUT]: SERVER request state: DORMANT
[21:34:10] [Server thread/INFO]: [STDOUT]: SERVER enter state: DORMANT
[21:34:10] [Server thread/INFO]: [STDOUT]: INCOMING MISSION: Received MissionInit directly through ServerStateMachine constructor.
[21:34:10] [Server thread/INFO]: [STDOUT]: Mission received: Navigation through survival world.
[21:34:10] [Server thread/INFO]: Received mission: §9Navigation through survival world.
[21:34:10] [Server thread/INFO]: Source: §alocalhost
[21:34:10] [Server thread/INFO]: [STDOUT]: SERVER request state: BUILDING_WORLD
[21:34:10] [Server thread/INFO]: [STDOUT]: SERVER enter state: BUILDING_WORLD
[21:34:10] [Server thread/INFO]: [STDOUT]: SERVER request state: WAITING_FOR_AGENTS_TO_ASSEMBLE
[21:34:11] [Client thread/INFO]: [CHAT] Received mission: §9Navigation through survival world.
[21:34:11] [Client thread/INFO]: [CHAT] Source: §alocalhost
[21:34:11] [Client thread/INFO]: [STDOUT]: ***Telling server we are ready - MineRLAgent
[21:34:11] [Client thread/INFO]: [STDOUT]: ***Telling server we are ready - MineRLAgent
[21:34:11] [Client thread/INFO]: [STDOUT]: ***Telling server we are ready - MineRLAgent
[21:34:11] [Server thread/INFO]: [STDOUT]: SERVER enter state: WAITING_FOR_AGENTS_TO_ASSEMBLE
[21:34:11] [Server thread/INFO]: [STDOUT]: Experiment requires: 
[21:34:11] [Server thread/INFO]: [STDOUT]: >>>> MineRLAgent
[21:34:11] [Client thread/INFO]: [STDOUT]: ***Telling server we are ready - MineRLAgent
[21:34:11] [Client thread/INFO]: [STDOUT]: CLIENT request state: RUNNING
[21:34:11] [Client thread/INFO]: [STDOUT]: CLIENT enter state: RUNNING
[21:34:11] [Client thread/INFO]: [STDOUT]: Unpausing
[21:34:11] [Server thread/INFO]: [STDOUT]: SERVER request state: RUNNING
[21:34:11] [Server thread/INFO]: [STDOUT]: SERVER enter state: RUNNING
[21:34:12] [Client thread/INFO]: [CHAT] §l300...
[21:34:12] [Client thread/INFO]: [CHAT] §l299...
[21:34:12] [Client thread/INFO]: [CHAT] §l298...
[21:34:12] [Client thread/INFO]: [CHAT] §l297...
[21:34:12] [Client thread/INFO]: [CHAT] §l296...
[21:34:13] [Client thread/INFO]: [CHAT] §l295...
[21:34:13] [Client thread/INFO]: [CHAT] §l294...
[21:34:13] [Client thread/INFO]: [CHAT] §l293...
[21:34:14] [Client thread/INFO]: [CHAT] §l292...
[21:34:14] [Client thread/INFO]: [CHAT] §l291...
[21:34:14] [Client thread/INFO]: [CHAT] §l290...
```

**Comment by MadcowD** [comment]
What are the specs on your machine?

**Comment by mantoone** [comment]
> Does this error prevent the mission from starting? I notice later in the logs it starts working?

Yes, the env appears to get stuck on minecraft start screen (where you can select single player, multiplayer etc.). I don't know how to read the logs, but one of the 4 envs I start gets stuck.

**Comment by mantoone** [comment]
> What are the specs on your machine?

Quad core i7, 32GB ram, 1080 ti. When I run my algorithm, the CPU usage is 100% on all cores. With 3 envs about 20GB ram is used, with 4 it gets to about 28GB. GPU is usage is slight.

**Comment by MadcowD** [comment]
Hey all.
I've made some headway here.

We need to package all of the relevant Minecraft jar's with the Pypi package. I have gotten a service limit increase for our Pip packages: https://github.com/pypa/warehouse/issues/6241

**Comment by zlf0625** [comment]
So is there a solution to run multiple environment instances at the same time?

I use openai baselines repo's ShmemVecEnv and SubprocVecEnv. But it seems that both of them cannot support multiple instances of MineRL.

I am trying to run MineRLNavigateDense-v0, and the error is `AssertionError: daemonic processes are not allowed to have children` if I use above two vectorized environment classes.

If I run them in two separate python processes with DummyVecEnv (for consistency) on the same Linux server via SSH with `xvfb-run`, the first instance will run normally. However, if I run the second one, the first one will be stuck.

I also test on my own MacBook. It works well even for multiple instances.
