### ISSUE TITLE
Not using fork before starting a new process

### ISSUE THREAD

**Issue by sergimassabates1** [minerllabs/minerl#129]
###    Just doing the Sampling The Dataset tutorial and I can't get to solve this problem, any idea on that? I show de cmd text right below.

 context=self.get_context())
  File "C:\Users\SergiM\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\Users\SergiM\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\Users\SergiM\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\SergiM\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\SergiM\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
Traceback (most recent call last):
  File "C:\Users\SergiM\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
  File "<string>", line 1, in <module>
  File "C:\Users\SergiM\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\spawn.py", line 105, in spawn_main
    _check_not_importing_main()
  File "C:\Users\SergiM\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    exitcode = _main(fd)
  File "C:\Users\SergiM\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\spawn.py", line 114, in _main
    is not going to be frozen to produce an executable.''')
RuntimeError:
         An attempt has been made to start a new process before the
         current process has finished its bootstrapping phase.

         This probably means that you are not using fork to start your
         child processes and you have forgotten to use the proper idiom
         in the main module:

             if __name__ == '__main__':
                 freeze_support()
                 ...

         The "freeze_support()" line can be omitted if the program
         is not going to be frozen to produce an executable.
    prepare(preparation_data)
  File "C:\Users\SergiM\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\SergiM\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\SergiM\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\SergiM\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\SergiM\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\SergiM\Desktop\Projectes ML\Estiu 2019\MineRL\samplingDataset.py", line 7, in <module>
    data = minerl.data.make('MineRLObtainDiamond-v0')
  File "C:\Users\SergiM\AppData\Local\Programs\Python\Python37-32\lib\site-packages\minerl\data\__init__.py", line 43, in make
    minimum_size_to_dequeue)
  File "C:\Users\SergiM\AppData\Local\Programs\Python\Python37-32\lib\site-packages\minerl\data\data_pipeline.py", line 54, in __init__
    self.processing_pool = multiprocessing.Pool(self.number_of_workers)
  File "C:\Users\SergiM\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\SergiM\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\Users\SergiM\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\Users\SergiM\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\SergiM\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\SergiM\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\SergiM\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\SergiM\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
         An attempt has been made to start a new process before the
         current process has finished its bootstrapping phase.

         This probably means that you are not using fork to start your
         child processes and you have forgotten to use the proper idiom
         in the main module:

             if __name__ == '__main__':
                 freeze_support()
                 ...

         The "freeze_support()" line can be omitted if the program
         is not going to be frozen to produce an executable.

**Comment by MadcowD** [comment]
Hey what was the solution to this issue?
