### ISSUE TITLE
Error while creating an environment with env = gym.make('MineRLNavigateDense-v0')

### ISSUE THREAD

**Issue by HaozhengLi** [minerllabs/minerl#138]
Device informations:
Windows 7
CPU i5-7500
GPU Intel(R) HD Graphics 630 (no GPU)
Python 3.5.1
JAVA 1.8.0_211

My code:
```
import minerl
import gym
env = gym.make('MineRLNavigateDense-v0')


obs, _ = env.reset()

done = False
while not done:
    action = env.action_space.sample() 
    obs, reward, done, info = env.step(action)
```

The error log:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 115, in _main
    prepare(preparation_data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 240, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Output\Python_output\MineRL\baselines\test.py", line 4, in <module>
    env = gym.make('MineRLNavigateDense-v0')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\gym\envs\registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\gym\envs\registration.py", line 101, in make
    env = spec.make(**kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\gym\envs\registration.py", line 73, in make
    env = cls(**_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\minerl\env\core.py", line 132, in __init__
    self.instance = self._get_new_instance(port)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\minerl\env\core.py", line 154, in _get_new_instance
    instance.launch()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\minerl\env\malmo.py", line 373, in launch
    parent_pid, self.minecraft_process.pid, self.host, port, self.instance_dir)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\minerl\env\malmo.py", line 584, in _launch_process_watcher
    p.start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\multiprocessing\popen_spawn_win32.py", line 34, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 144, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 137, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    env = gym.make('MineRLNavigateDense-v0')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\gym\envs\registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\gym\envs\registration.py", line 101, in make
    env = spec.make(**kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\gym\envs\registration.py", line 73, in make
    env = cls(**_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\minerl\env\core.py", line 132, in __init__
    self.instance = self._get_new_instance(port)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\minerl\env\core.py", line 154, in _get_new_instance
    instance.launch()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\minerl\env\malmo.py", line 397, in launch
    raise EOFError(error_str + "\n\nMinecraft process finished unexpectedly. There was an error with Malmo.")
EOFError: This mapping 'snapshot_20161220' was designed for MC 1.11! Use at your own peril.
#################################################
         ForgeGradle 2.2-SNAPSHOT-3966cea
  https://github.com/MinecraftForge/ForgeGradle
#################################################
               Powered by MCP unknown
             http://modcoderpack.com
         by: Searge, ProfMobius, Fesh0r,
         R4wk, ZeuX, IngisKahn, bspkrs
#################################################
Found AccessTransformer: malmomod_at.cfg
:deobfCompileDummyTask
:deobfProvidedDummyTask
:getVersionJson
:extractUserdev UP-TO-DATE
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar SKIPPED
:mergeJars SKIPPED
:applyBinaryPatches SKIPPED
:extractDependencyATs SKIPPED
:extractMcpData SKIPPED
:extractMcpMappings SKIPPED
:genSrgs SKIPPED
:deobfMcMCP
Applying SpecialSource...
Applying Exceptor...
Applying RuntimeInvisibleParameterAnnotations workaround...
:deobfMcMCP FAILED

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Administrator\AppData\Local\Programs\Python\Python35\Lib\site-packages\minerl\env\Malmo\Min

* What went wrong:
Execution failed for task ':deobfMcMCP'.
> error reading zip file

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 26.81 secs


Minecraft process finished unexpectedly. There was an error with Malmo.
```

Any help will be great, thanks a lot!

**Comment by MadcowD** [comment]
Hi!
What fixed this?

**Comment by HaozhengLi** [comment]
> Hi!
> What fixed this?

Hello, reboot my computer fix this.

But after maybe 24 hours it happened again, so I had to reboot my computer again.

I made a topic on:
(https://discourse.aicrowd.com/t/cannot-make-env-successfully-every-time/1480)

**Comment by MadcowD** [comment]
https://pytorch.org/docs/stable/notes/windows.html#multiprocessing-error-without-if-clause-protection

You need to make sure your process is wrapped in an if_else to check for main,

I've added some code to the new package that should fix this, but I'm not sure it will.

**Comment by MadcowD** [comment]
@HaozhengLi  Let me know if the new changes help <3 :)

**Comment by HaozhengLi** [comment]
> @HaozhengLi Let me know if the new changes help <3 :)

Hello, I wrapped my process in an if_else to check for main, and it works, thank you for your help! :)
