### ISSUE TITLE
Unclean termination when running remote instance manager

### ISSUE THREAD

**Issue by skbly7** [minerllabs/minerl#158]
```
2019-07-22 05:56:18 skbly7.local minerl.env.malmo.instance.33122e[59225] DEBUG [05:56:18] [Server thread/INFO]: MalmoTutorialBot was blown up by Creeper
2019-07-22 05:56:19 skbly7.local minerl.env.malmo.instance.33122e[59225] DEBUG [05:56:19] [Client thread/INFO]: [CHAT] §l269...
2019-07-22 05:56:19 skbly7.local minerl.env.malmo.instance.33122e[59225] DEBUG [05:56:19] [Client thread/INFO]: [STDOUT]: Unpausing
2019-07-22 05:56:19 skbly7.local minerl.env.malmo.instance.33122e[59225] DEBUG [05:56:19] [Client thread/INFO]: [STDOUT]: CLIENT request state: MISSION_ABORTED
2019-07-22 05:56:19 skbly7.local minerl.env.malmo.instance.33122e[59225] DEBUG [05:56:19] [Client thread/INFO]: [STDOUT]: CLIENT enter state: MISSION_ABORTED
2019-07-22 2019-07-22 05:56:19 skbly7.local root[59231] ERROR Inference Failed...
05:56:19 skbly7.local minerl.env.malmo.instance.33122e[59225] DEBUG [05:56:19] [Client thread/INFO]: [STDOUT]: inform the agent
2019-07-22 05:56:19 skbly7.local minerl.env.malmo.instance.33122e[59225] INFO [05:56:19] [EnvServerSocketHandler/INFO]: [STDOUT]: [LOGTOPY] Want to quit on disconnect.
2019-07-22 05:56:19 skbly7.local minerl.env.malmo.instance.33122e[59225] DEBUG [05:56:19] [Server thread/INFO]: [STDOUT]: SERVER request state: CLEAN_UP
2019-07-22 05:56:19 skbly7.local minerl.env.malmo.instance.33122e[59225] DEBUG [05:56:19] [Server thread/INFO]: [STDOUT]: SERVER enter state: CLEAN_UP
2019-07-22 05:56:19 skbly7.local minerl.env.malmo.instance.33122e[59225] DEBUG [05:56:19] [Server thread/INFO]: [STDOUT]: SERVER request state: DORMANT
2019-07-22 05:56:19 skbly7.local minerl.env.malmo.instance.33122e[59225] DEBUG [05:56:19] [Server thread/INFO]: [STDOUT]: SERVER enter state: DORMANT
2019-07-22 05:56:19 skbly7.local minerl.env.malmo.instance.33122e[59225] DEBUG [05:56:19] [Client thread/INFO]: [STDOUT]: CLIENT request state: DORMANT
2019-07-22 05:56:19 skbly7.local minerl.env.malmo.instance.33122e[59225] DEBUG [05:56:19] [Client thread/INFO]: [STDOUT]: CLIENT enter state: DORMANT
2019-07-22 05:56:19 skbly7.local minerl.env.malmo.instance.33122e[59225] DEBUG [05:56:19] [Client thread/INFO]: [STDOUT]: JETTISONING 0 COMMANDS
2019-07-22 05:56:19 skbly7.local minerl.env.malmo.instance.33122e[59231] DEBUG [05:56:19] [Client thread/INFO]: [STDOUT]: inform the agent
remote object 'PYRO:obj_dd5cc88fb49b4a47bece6511e6f23bdd@localhost:54922' has no exposed attribute or method 'running'
Exception ignored in: <function Proxy.__del__ at 0x111a6df28>
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/minerl/lib/python3.7/site-packages/Pyro4/core.py", line 266, in __del__
  File "/usr/local/anaconda3/envs/minerl/lib/python3.7/site-packages/Pyro4/core.py", line 400, in _pyroRelease
  File "/usr/local/anaconda3/envs/minerl/lib/python3.7/logging/__init__.py", line 1370, in debug
  File "/usr/local/anaconda3/envs/minerl/lib/python3.7/logging/__init__.py", line 1626, in isEnabledFor
TypeError: 'NoneType' object is not callable
2019-07-22 05:56:24 skbly7.local minerl.env.malmo.instance.33122e[59225] DEBUG [05:56:24] [EnvServerSocketHandler/INFO]: Java has been asked to exit (code 0) by net.minecraftforge.fml.common.FMLCommonHandler.exitJava(FMLCommonHandler.java:659).
```

MalmoTutorialBot was blown up by Creeper event is leading to unclean exit. 

This happens when remove instance manager is used. Tried with `minerl==0.2.2`.

**Comment by MadcowD** [comment]
Could you explain the inference failed line? Also would you be willing to share code for the context?

**Comment by skbly7** [comment]
```
2019-07-22 2019-07-22 05:56:19 skbly7.local root[59231] ERROR Inference Failed...
```

This is coming from log on my side i.e. 59231 pid is the agent, while 59225 pid is the remote instance I am connecting to. Sure, I will upload the code and share asap.

**Comment by skbly7** [comment]
The code I am trying is `train.py` [here](https://github.com/AIcrowd/neurips2019_minerl_challenge_starter_kit/blob/master/train.py). 

I am executing it as `./utility/evaluation_locally.sh` ([script](https://github.com/AIcrowd/neurips2019_minerl_challenge_starter_kit/blob/master/utility/evaluation_locally.sh))
