### ISSUE TITLE
Minecraft server plugin failed to record.

### ISSUE THREAD

**Issue by MadcowD** [minerllabs/minerl#20]
@brandonhoughton  

Here is an error from the Minecraft server plugin "Failed to start recording."
```
[14:54:59] [Netty Epoll Client IO #0/INFO] [replaymod-recording]: UID: 92ec99fcafe51cc4151156ae9fca58d4

[14:54:59] [Netty Epoll Client IO #0/INFO] [replaymod-recording]: Establishing connection to minecraft server: mc.minerl.io
[14:55:00] [Netty Epoll Client IO #0/INFO] [replaymod-recording]: Minecraft Key:    CU4UVIJ6ZVIVF7B2XLTSR9MPOLRGQ11EF5J1PV9F3WC5O

[14:55:00] [Netty Epoll Client IO #0/INFO] [replaymod-recording]: Minecraft Key:    CU4UVIJ6ZVIVF7B2XLTSR9MPOLRGQ11EF5J1PV9F3WC5O

[14:55:00] [Netty Epoll Client IO #0/INFO] [replaymod-recording]: Server response: true

[14:55:01] [Netty Epoll Client IO #0/ERROR] [replaymod-recording]: Could not parse returned firehose stream infromation
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: java.net.SocketTimeoutException: Receive timed out
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at java.net.PlainDatagramSocketImpl.receive0(Native Method)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:143)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at java.net.DatagramSocket.receive(DatagramSocket.java:812)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at com.replaymod.replaystudio.replay.StreamReplayFile.getFirehoseStream(StreamReplayFile.java:223)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at com.replaymod.replaystudio.replay.StreamReplayFile.<init>(StreamReplayFile.java:155)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at com.replaymod.recording.handler.ConnectionEventHandler.onConnectedToServerEvent(ConnectionEventHandler.java:226)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at com.replaymod.recording.ReplayModRecording.initiateRecording(ReplayModRecording.java:72)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at net.minecraft.client.network.NetHandlerLoginClient.handler$replayModRecording_initiateRecording$zzd000(NetHandlerLoginClient.java:536)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at net.minecraft.client.network.NetHandlerLoginClient.func_147390_a(NetHandlerLoginClient.java)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at net.minecraft.network.login.server.SPacketLoginSuccess.func_148833_a(SPacketLoginSuccess.java:42)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at net.minecraft.network.login.server.SPacketLoginSuccess.func_148833_a(SPacketLoginSuccess.java:12)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:147)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:49)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1017)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.replaystudio.replay.StreamReplayFile:getFirehoseStream:248]: 	at java.lang.Thread.run(Thread.java:748)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: java.io.IOException: Unable to get firehose stream 
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at com.replaymod.replaystudio.replay.StreamReplayFile.<init>(StreamReplayFile.java:157)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at com.replaymod.recording.handler.ConnectionEventHandler.onConnectedToServerEvent(ConnectionEventHandler.java:226)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at com.replaymod.recording.ReplayModRecording.initiateRecording(ReplayModRecording.java:72)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at net.minecraft.client.network.NetHandlerLoginClient.handler$replayModRecording_initiateRecording$zzd000(NetHandlerLoginClient.java:536)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at net.minecraft.client.network.NetHandlerLoginClient.func_147390_a(NetHandlerLoginClient.java)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at net.minecraft.network.login.server.SPacketLoginSuccess.func_148833_a(SPacketLoginSuccess.java:42)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at net.minecraft.network.login.server.SPacketLoginSuccess.func_148833_a(SPacketLoginSuccess.java:12)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:147)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:49)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1017)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
[14:55:01] [Netty Epoll Client IO #0/INFO] [STDERR]: [com.replaymod.recording.handler.ConnectionEventHandler:onConnectedToServerEvent:272]: 	at java.lang.Thread.run(Thread.java:748)
[14:55:01] [Netty Epoll Client IO #0/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] [Replay Mod] Failed to start recording

```

**Comment by brandonhoughton** [comment]
Tracked in the wrong repo - closing
