### ISSUE TITLE
Cannot generate minecraft environment (No display)

### ISSUE THREAD

**Issue by juliusfrost** [minerllabs/minerl#21]
Hi, this time using a Linux server, I got this error message while trying to run the Hello World tutorial. Run on minerl 0.1.2

```
(dl) [juliusf@ivcgpu5 juliusf]$ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gym
>>> import minerl
>>> env = gym.make('MineRLNavigateDense-v0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/juliusf/anaconda3/envs/dl/lib/python3.6/site-packages/gym/envs/registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "/scratch/juliusf/anaconda3/envs/dl/lib/python3.6/site-packages/gym/envs/registration.py", line 101, in make
    env = spec.make(**kwargs)
  File "/scratch/juliusf/anaconda3/envs/dl/lib/python3.6/site-packages/gym/envs/registration.py", line 73, in make
    env = cls(**_kwargs)
  File "/scratch/juliusf/anaconda3/envs/dl/lib/python3.6/site-packages/minerl/env/core.py", line 126, in __init__
    self.init(observation_space, action_space, port=port)
  File "/scratch/juliusf/anaconda3/envs/dl/lib/python3.6/site-packages/minerl/env/core.py", line 152, in init
    self.instance = InstanceManager.get_instance().__enter__()
  File "/scratch/juliusf/anaconda3/envs/dl/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/scratch/juliusf/anaconda3/envs/dl/lib/python3.6/site-packages/minerl/env/malmo.py", line 90, in get_instance
    inst = cls._Instance(cls._get_valid_port())
  File "/scratch/juliusf/anaconda3/envs/dl/lib/python3.6/site-packages/minerl/env/malmo.py", line 260, in __init__
    self.launch(port, existing)
  File "/scratch/juliusf/anaconda3/envs/dl/lib/python3.6/site-packages/minerl/env/malmo.py", line 288, in launch
    raise EOFError("Minecraft process finished unexpectedly")
EOFError: Minecraft process finished unexpectedly
>>>

```

Detailed Error

```
(dl) [juliusf@ivcgpu5 juliusf]$ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gym
>>> import minerl
>>> import logging
>>> logging.basicConfig(level=logging.DEBUG)
>>>
>>> env = gym.make('MineRLNavigateDense-v0')
INFO:minerl.env.malmo:Starting Minecraft process: ['/scratch/juliusf/anaconda3/envs/dl/lib/python3.6/site-packages/minerl/env/Malmo/Minecraft/launchClient.sh', '-port', '9000', '-env']
DEBUG:minerl.env.malmo:This mapping 'snapshot_20161220' was designed for MC 1.11! Use at your own peril.
DEBUG:minerl.env.malmo:#################################################
DEBUG:minerl.env.malmo:         ForgeGradle 2.2-SNAPSHOT-3966cea
DEBUG:minerl.env.malmo:  https://github.com/MinecraftForge/ForgeGradle
DEBUG:minerl.env.malmo:#################################################
DEBUG:minerl.env.malmo:               Powered by MCP unknown
DEBUG:minerl.env.malmo:             http://modcoderpack.com
DEBUG:minerl.env.malmo:         by: Searge, ProfMobius, Fesh0r,
DEBUG:minerl.env.malmo:         R4wk, ZeuX, IngisKahn, bspkrs
DEBUG:minerl.env.malmo:#################################################
DEBUG:minerl.env.malmo:Found AccessTransformer: malmomod_at.cfg
DEBUG:minerl.env.malmo::deobfCompileDummyTask
DEBUG:minerl.env.malmo::deobfProvidedDummyTask
DEBUG:minerl.env.malmo::sourceApiJava UP-TO-DATE
DEBUG:minerl.env.malmo::compileApiJava UP-TO-DATE
DEBUG:minerl.env.malmo::processApiResources UP-TO-DATE
DEBUG:minerl.env.malmo::apiClasses UP-TO-DATE
DEBUG:minerl.env.malmo::copyModToClient UP-TO-DATE
DEBUG:minerl.env.malmo::copyModToServer UP-TO-DATE
DEBUG:minerl.env.malmo::extractMcpData SKIPPED
DEBUG:minerl.env.malmo::extractMcpMappings SKIPPED
DEBUG:minerl.env.malmo::getVersionJson
DEBUG:minerl.env.malmo::extractUserdev UP-TO-DATE
DEBUG:minerl.env.malmo::genSrgs SKIPPED
DEBUG:minerl.env.malmo::copySrg UP-TO-DATE
DEBUG:minerl.env.malmo::deleteSchemas
DEBUG:minerl.env.malmo::copySchemas
DEBUG:minerl.env.malmo::jaxb UP-TO-DATE
DEBUG:minerl.env.malmo::sourceMainJava UP-TO-DATE
DEBUG:minerl.env.malmo::compileJavawarning: [options] bootstrap class path not set in conjunction with -source 1.6
DEBUG:minerl.env.malmo:Note: SpongePowered MIXIN Annotation Processor Version=0.7.5
DEBUG:minerl.env.malmo:Note: ObfuscationServiceMCP supports type: "searge"
DEBUG:minerl.env.malmo:Note: ObfuscationServiceMCP supports type: "notch"
DEBUG:minerl.env.malmo:Note: Loading searge mappings from /home/ugrad/juliusf/.gradle/caches/minecraft/de/oceanlabs/mcp/mcp_snapshot/20161220/1.11.2/srgs/mcp-srg.srg
DEBUG:minerl.env.malmo:Note: Loading notch mappings from /home/ugrad/juliusf/.gradle/caches/minecraft/de/oceanlabs/mcp/mcp_snapshot/20161220/1.11.2/srgs/mcp-notch.srg
DEBUG:minerl.env.malmo:Note: Writing refmap to /scratch/juliusf/anaconda3/envs/dl/lib/python3.6/site-packages/minerl/env/Malmo/Minecraft/build/tmp/compileJava/compileJava-refmap.json
DEBUG:minerl.env.malmo:Note: Writing searge output SRGs to /scratch/juliusf/anaconda3/envs/dl/lib/python3.6/site-packages/minerl/env/Malmo/Minecraft/build/tmp/compileJava/mcp-srg.srg
DEBUG:minerl.env.malmo:Note: Writing notch output SRGs to /scratch/juliusf/anaconda3/envs/dl/lib/python3.6/site-packages/minerl/env/Malmo/Minecraft/build/tmp/compileJava/mcp-notch.srg
DEBUG:minerl.env.malmo:Note: Writing refmap to /scratch/juliusf/anaconda3/envs/dl/lib/python3.6/site-packages/minerl/env/Malmo/Minecraft/build/tmp/compileJava/compileJava-refmap.json
DEBUG:minerl.env.malmo:Note: Writing searge output SRGs to /scratch/juliusf/anaconda3/envs/dl/lib/python3.6/site-packages/minerl/env/Malmo/Minecraft/build/tmp/compileJava/mcp-srg.srg
DEBUG:minerl.env.malmo:Note: Writing notch output SRGs to /scratch/juliusf/anaconda3/envs/dl/lib/python3.6/site-packages/minerl/env/Malmo/Minecraft/build/tmp/compileJava/mcp-notch.srg
DEBUG:minerl.env.malmo:Note: Some input files use or override a deprecated API.
DEBUG:minerl.env.malmo:Note: Recompile with -Xlint:deprecation for details.
DEBUG:minerl.env.malmo:Note: Some input files use unchecked or unsafe operations.
DEBUG:minerl.env.malmo:Note: Recompile with -Xlint:unchecked for details.
DEBUG:minerl.env.malmo:
DEBUG:minerl.env.malmo::processResources UP-TO-DATE
DEBUG:minerl.env.malmo::classes
DEBUG:minerl.env.malmo::jar UP-TO-DATE
DEBUG:minerl.env.malmo::extractNatives SKIPPED
DEBUG:minerl.env.malmo::getAssetIndex UP-TO-DATE
DEBUG:minerl.env.malmo::getAssets
DEBUG:minerl.env.malmo::makeStart SKIPPED
DEBUG:minerl.env.malmo::runClient
DEBUG:minerl.env.malmo:[14:40:31] [main/INFO] [GradleStart]: Extra: []
DEBUG:minerl.env.malmo:[14:40:31] [main/INFO] [GradleStart]: Found and added coremod: com.microsoft.Malmo.OverclockingPlugin
DEBUG:minerl.env.malmo:[14:40:31] [main/INFO] [GradleStart]: Running with arguments: [--userProperties, {}, --assetsDir, /home/ugrad/juliusf/.gradle/caches/minecraft/assets, --assetIndex, 1.11, --accessToken{REDACTED}, --version, 1.11.2, --tweakClass, net.minecraftforge.fml.common.launcher.FMLTweaker, --tweakClass, net.minecraftforge.gradle.tweakers.CoremodTweaker]
DEBUG:minerl.env.malmo:[14:40:31] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
DEBUG:minerl.env.malmo:[14:40:31] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
DEBUG:minerl.env.malmo:[14:40:31] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.CoremodTweaker
DEBUG:minerl.env.malmo:[14:40:31] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
DEBUG:minerl.env.malmo:[14:40:31] [main/INFO] [FML]: Forge Mod Loader version 13.20.0.2228 for Minecraft 1.11.2 loading
DEBUG:minerl.env.malmo:[14:40:31] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_212, running on Linux:amd64:3.10.0-957.12.2.el7.x86_64, installed at /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre
DEBUG:minerl.env.malmo:[14:40:31] [main/INFO] [FML]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
DEBUG:minerl.env.malmo:[14:40:31] [main/INFO] [FML]: Found a command line coremod : com.microsoft.Malmo.OverclockingPlugin
DEBUG:minerl.env.malmo:[14:40:31] [main/WARN] [FML]: The coremod com.microsoft.Malmo.OverclockingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
DEBUG:minerl.env.malmo:[14:40:32] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.5 Source=file:/home/ugrad/juliusf/.gradle/caches/modules-2/files-2.1/org.spongepowered/mixin/0.7.5-SNAPSHOT/c989878008c2c5ff1a7c6491c4103d8faa221d19/mixin-0.7.5-SNAPSHOT.jar Service=LaunchWrapper Env=CLIENT
DEBUG:minerl.env.malmo:[14:40:32] [main/INFO] [mixin]: Compatibility level set to JAVA_8
DEBUG:minerl.env.malmo:[14:40:32] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.CoremodTweaker
DEBUG:minerl.env.malmo:[14:40:32] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.fml.relauncher.FMLCorePlugin
DEBUG:minerl.env.malmo:[14:40:32] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.classloading.FMLForgePlugin
DEBUG:minerl.env.malmo:[14:40:32] [main/INFO] [GradleStart]: Injecting location in coremod com.microsoft.Malmo.OverclockingPlugin
DEBUG:minerl.env.malmo:[14:40:32] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
DEBUG:minerl.env.malmo:[14:40:32] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
DEBUG:minerl.env.malmo:[14:40:32] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
DEBUG:minerl.env.malmo:[14:40:32] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
DEBUG:minerl.env.malmo:[14:40:32] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
DEBUG:minerl.env.malmo:[14:40:32] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
DEBUG:minerl.env.malmo:[14:40:32] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
DEBUG:minerl.env.malmo:[14:40:32] [main/ERROR] [FML]: The binary patch set is missing. Either you are in a development environment, or things are not going to work!
DEBUG:minerl.env.malmo:[14:40:32] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
DEBUG:minerl.env.malmo:[14:40:32] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
DEBUG:minerl.env.malmo:[14:40:32] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
DEBUG:minerl.env.malmo:[14:40:32] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
DEBUG:minerl.env.malmo:[14:40:32] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@3ee39da0
DEBUG:minerl.env.malmo:[14:40:32] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
DEBUG:minerl.env.malmo:[14:40:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
DEBUG:minerl.env.malmo:[14:40:33] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
DEBUG:minerl.env.malmo:[14:40:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
DEBUG:minerl.env.malmo:[14:40:33] [main/WARN] [mixin]: Reference map 'mixins.replaymod.refmap.json' for mixins.overclocking.malmomod.json could not be read. If this is a development environment you can ignore this message
DEBUG:minerl.env.malmo:[14:40:33] [main/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:transform:58]: MALMO: Attempting to transform MinecraftServer
DEBUG:minerl.env.malmo:[14:40:33] [main/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:overclockRenderer:129]: MALMO: Found Minecraft, attempting to transform it
DEBUG:minerl.env.malmo:[14:40:33] [main/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:overclockRenderer:135]: MALMO: Found Minecraft.runGameLoop() method, attempting to transform it
DEBUG:minerl.env.malmo:[14:40:33] [main/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:overclockRenderer:150]: MALMO: Hooked into call to Minecraft.updateDisplay()
DEBUG:minerl.env.malmo:[14:40:33] [main/INFO] [mixin]: A re-entrant transformer '$wrapper.com.microsoft.Malmo.OverclockingClassTransformer' was detected and will no longer process meta class data
DEBUG:minerl.env.malmo:[14:40:33] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
DEBUG:minerl.env.malmo:[14:40:33] [main/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:transform:58]: MALMO: Attempting to transform MinecraftServer
DEBUG:minerl.env.malmo:[14:40:33] [main/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:overclockRenderer:129]: MALMO: Found Minecraft, attempting to transform it
DEBUG:minerl.env.malmo:[14:40:33] [main/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:overclockRenderer:135]: MALMO: Found Minecraft.runGameLoop() method, attempting to transform it
DEBUG:minerl.env.malmo:[14:40:33] [main/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:overclockRenderer:150]: MALMO: Hooked into call to Minecraft.updateDisplay()
DEBUG:minerl.env.malmo:[14:40:33] [main/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:transform:42]: Transformed Name: net.minecraft.client.entity.EntityPlayerSP
DEBUG:minerl.env.malmo:[14:40:33] [main/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:transform:42]: Transformed Name: net.minecraft.client.entity.AbstractClientPlayer
DEBUG:minerl.env.malmo:[14:40:35] [Client thread/INFO]: Setting user: Player163
DEBUG:minerl.env.malmo:[14:40:37] [Client thread/WARN]: Skipping bad option: lastServer:
DEBUG:minerl.env.malmo:[14:40:37] [Client thread/INFO]: LWJGL Version: 2.9.4
DEBUG:minerl.env.malmo:[14:40:38] [Client thread/INFO]: [STDOUT]: MALMO: Attempting to transform MinecraftServer
DEBUG:minerl.env.malmo:[14:40:38] [Client thread/INFO]: [STDOUT]: MALMO: Found GlStateManager, attempting to transform it
DEBUG:minerl.env.malmo:[14:40:38] [Client thread/INFO]: [STDOUT]: MALMO: Found GlStateManager.bindTexture() method, attempting to transform it
DEBUG:minerl.env.malmo:[14:40:38] [Client thread/INFO]: [STDOUT]: MALMO: Hooked into call to GlStateManager.bindTexture()
DEBUG:minerl.env.malmo:[14:40:38] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:600]: ---- Minecraft Crash Report ----
DEBUG:minerl.env.malmo:// Quite honestly, I wouldn't worry myself about that.
DEBUG:minerl.env.malmo:
DEBUG:minerl.env.malmo:Time: 6/9/19 2:40 PM
DEBUG:minerl.env.malmo:Description: Initializing game
DEBUG:minerl.env.malmo:
DEBUG:minerl.env.malmo:java.lang.ExceptionInInitializerError
DEBUG:minerl.env.malmo: at net.minecraft.client.Minecraft.setWindowIcon(Minecraft.java:670)
DEBUG:minerl.env.malmo: at net.minecraft.client.Minecraft.init(Minecraft.java:467)
DEBUG:minerl.env.malmo: at net.minecraft.client.Minecraft.run(Minecraft.java:387)
DEBUG:minerl.env.malmo: at net.minecraft.client.main.Main.main(Main.java:118)
DEBUG:minerl.env.malmo: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
DEBUG:minerl.env.malmo: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
DEBUG:minerl.env.malmo: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
DEBUG:minerl.env.malmo: at java.lang.reflect.Method.invoke(Method.java:498)
DEBUG:minerl.env.malmo: at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
DEBUG:minerl.env.malmo: at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
DEBUG:minerl.env.malmo: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
DEBUG:minerl.env.malmo: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
DEBUG:minerl.env.malmo: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
DEBUG:minerl.env.malmo: at java.lang.reflect.Method.invoke(Method.java:498)
DEBUG:minerl.env.malmo: at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
DEBUG:minerl.env.malmo: at GradleStart.main(GradleStart.java:26)
DEBUG:minerl.env.malmo:Caused by: java.lang.NullPointerException
DEBUG:minerl.env.malmo: at org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:947)
DEBUG:minerl.env.malmo: at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738)
DEBUG:minerl.env.malmo: at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
DEBUG:minerl.env.malmo: ... 16 more
DEBUG:minerl.env.malmo:
DEBUG:minerl.env.malmo:
DEBUG:minerl.env.malmo:A detailed walkthrough of the error, its code path and all known details is as follows:
DEBUG:minerl.env.malmo:---------------------------------------------------------------------------------------
DEBUG:minerl.env.malmo:
DEBUG:minerl.env.malmo:-- Head --
DEBUG:minerl.env.malmo:Thread: Client thread
DEBUG:minerl.env.malmo:Stacktrace:
DEBUG:minerl.env.malmo: at net.minecraft.client.Minecraft.setWindowIcon(Minecraft.java:670)
DEBUG:minerl.env.malmo: at net.minecraft.client.Minecraft.init(Minecraft.java:467)
DEBUG:minerl.env.malmo:
DEBUG:minerl.env.malmo:-- Initialization --
DEBUG:minerl.env.malmo:Details:
DEBUG:minerl.env.malmo:Stacktrace:
DEBUG:minerl.env.malmo: at net.minecraft.client.Minecraft.run(Minecraft.java:387)
DEBUG:minerl.env.malmo: at net.minecraft.client.main.Main.main(Main.java:118)
DEBUG:minerl.env.malmo: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
DEBUG:minerl.env.malmo: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
DEBUG:minerl.env.malmo: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
DEBUG:minerl.env.malmo: at java.lang.reflect.Method.invoke(Method.java:498)
DEBUG:minerl.env.malmo: at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
DEBUG:minerl.env.malmo: at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
DEBUG:minerl.env.malmo: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
DEBUG:minerl.env.malmo: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
DEBUG:minerl.env.malmo: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
DEBUG:minerl.env.malmo: at java.lang.reflect.Method.invoke(Method.java:498)
DEBUG:minerl.env.malmo: at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
DEBUG:minerl.env.malmo: at GradleStart.main(GradleStart.java:26)
DEBUG:minerl.env.malmo:
DEBUG:minerl.env.malmo:-- System Details --
DEBUG:minerl.env.malmo:Details:
DEBUG:minerl.env.malmo: Minecraft Version: 1.11.2
DEBUG:minerl.env.malmo: Operating System: Linux (amd64) version 3.10.0-957.12.2.el7.x86_64
DEBUG:minerl.env.malmo: Java Version: 1.8.0_212, Oracle Corporation
DEBUG:minerl.env.malmo: Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
DEBUG:minerl.env.malmo: Memory: 913091760 bytes (870 MB) / 1494745088 bytes (1425 MB) up to 1908932608 bytes (1820 MB)
DEBUG:minerl.env.malmo: JVM Flags: 1 total; -Xmx2G
DEBUG:minerl.env.malmo: IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
DEBUG:minerl.env.malmo: FML:
DEBUG:minerl.env.malmo: Loaded coremods (and transformers):
DEBUG:minerl.env.malmo:OverclockingPlugin (MalmoMod-0.37.0.jar)
DEBUG:minerl.env.malmo:  com.microsoft.Malmo.OverclockingClassTransformer
DEBUG:minerl.env.malmo: Launched Version: 1.11.2
DEBUG:minerl.env.malmo: LWJGL: 2.9.4
DEBUG:minerl.env.malmo: OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
DEBUG:minerl.env.malmo: GL Caps:
DEBUG:minerl.env.malmo: Using VBOs: Yes
DEBUG:minerl.env.malmo: Is Modded: Definitely; Client brand changed to 'fml,forge'
DEBUG:minerl.env.malmo: Type: Client (map_client.txt)
DEBUG:minerl.env.malmo: Resource Packs:
DEBUG:minerl.env.malmo: Current Language: ~~ERROR~~ NullPointerException: null
DEBUG:minerl.env.malmo: Profiler Position: N/A (disabled)
DEBUG:minerl.env.malmo: CPU: <unknown>
DEBUG:minerl.env.malmo:[14:40:38] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:600]: #@!@# Game crashed! Crash report saved to: #@!@# /scratch/juliusf/anaconda3/envs/dl/lib/python3.6/site-packages/minerl/env/Malmo/Minecraft/run/./crash-reports/crash-2019-06-09_14.40.38-client.txt
DEBUG:minerl.env.malmo::runClient FAILED
DEBUG:minerl.env.malmo:
DEBUG:minerl.env.malmo:FAILURE: Build failed with an exception.
DEBUG:minerl.env.malmo:
DEBUG:minerl.env.malmo:* What went wrong:
DEBUG:minerl.env.malmo:Execution failed for task ':runClient'.
DEBUG:minerl.env.malmo:> Process 'command '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/bin/java'' finished with non-zero exit value 255
DEBUG:minerl.env.malmo:
DEBUG:minerl.env.malmo:* Try:
DEBUG:minerl.env.malmo:Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
DEBUG:minerl.env.malmo:
DEBUG:minerl.env.malmo:BUILD FAILED
DEBUG:minerl.env.malmo:
DEBUG:minerl.env.malmo:Total time: 18.052 secs
DEBUG:minerl.env.malmo:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/juliusf/anaconda3/envs/dl/lib/python3.6/site-packages/gym/envs/registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "/scratch/juliusf/anaconda3/envs/dl/lib/python3.6/site-packages/gym/envs/registration.py", line 101, in make
    env = spec.make(**kwargs)
  File "/scratch/juliusf/anaconda3/envs/dl/lib/python3.6/site-packages/gym/envs/registration.py", line 73, in make
    env = cls(**_kwargs)
  File "/scratch/juliusf/anaconda3/envs/dl/lib/python3.6/site-packages/minerl/env/core.py", line 126, in __init__
    self.init(observation_space, action_space, port=port)
  File "/scratch/juliusf/anaconda3/envs/dl/lib/python3.6/site-packages/minerl/env/core.py", line 152, in init
    self.instance = InstanceManager.get_instance().__enter__()
  File "/scratch/juliusf/anaconda3/envs/dl/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/scratch/juliusf/anaconda3/envs/dl/lib/python3.6/site-packages/minerl/env/malmo.py", line 90, in get_instance
    inst = cls._Instance(cls._get_valid_port())
  File "/scratch/juliusf/anaconda3/envs/dl/lib/python3.6/site-packages/minerl/env/malmo.py", line 260, in __init__
    self.launch(port, existing)
  File "/scratch/juliusf/anaconda3/envs/dl/lib/python3.6/site-packages/minerl/env/malmo.py", line 288, in launch
    raise EOFError("Minecraft process finished unexpectedly")
EOFError: Minecraft process finished unexpectedly
>>>

```

**Comment by MadcowD** [comment]
Ah, it appears you are running the environment without a display. Currently, GPU accelerated headless mode is not supported. 

You can either add a montor, or run your program with a virtual x-server. 

In order to run on a headless server, try runnign the command 'xvfb-run python3 <whatever_you're trying to run>',

**Comment by MadcowD** [comment]
I'm closing this issue, feel free to open if you have any questions!

**Comment by juliusfrost** [comment]
Thank you for your help.
I don't seem to have xvfb-run on my machine. It has CentOS installed.

**Comment by juliusfrost** [comment]
Currently I connect with MobaXterm. I wonder if there is any way to route the display through there.

**Comment by MadcowD** [comment]
Can you install xvbf using:
```
yum install xorg-x11-server-Xvfb
```

**Comment by juliusfrost** [comment]
Thanks, I will contact someone with root access.

**Comment by MadcowD** [comment]
Sorry for this inconvenience!!!

**Comment by juliusfrost** [comment]
Got it to run with vncserver that was already installed instead.

**Comment by tmhm** [comment]
Hi, @juliusfrost , I got the same error with yours, likes,

```
OverclockingPlugin (MalmoMod-0.37.0.jar)
  com.microsoft.Malmo.OverclockingClassTransformer
        Launched Version: 1.11.2
        LWJGL: 2.9.4
        OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
        GL Caps:
        Using VBOs: Yes
        Is Modded: Definitely; Client brand changed to 'fml,forge'
        Type: Client (map_client.txt)
        Resource Packs:
        Current Language: ~~ERROR~~ NullPointerException: null
        Profiler Position: N/A (disabled)
        CPU: <unknown>
[02:52:12] [Client thread/INFO]: [net.minecraft.init.Bootstrap:printToSYSOUT:523]: #@!@# Game crashed! Crash report saved to: #@!@# /tmp/tmpbqbjsjtz/Minecraft/run/./crash-reports/crash-2019-08-08_02.52.12-client.txt
:runClient FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runClient'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 255

```
And ,my run command as `xvfb-run -s "-ac -screen 0 1280x1024x24" python first_agent.py `. 
Do you have fix this issue now ? Thanks :)

**Comment by juliusfrost** [comment]
Hi @tmhm, seems like a different issue. Try opening a new one.

**Comment by ProQianXiao** [comment]
> Got it to run with vncserver that was already installed instead.

Could you give more details about your solution? I am in the same error with you, and I installed vncserver, what's the next operation? Thanks very much.

**Comment by sapan-ostic** [comment]
Hi, can you please describe how to solve the problem when suing vncserver?
