### ISSUE TITLE
Equipped item type bypasses "other" filter in observation for mainhand type

### ISSUE THREAD

**Issue by russelltankl** [minerllabs/minerl#242]
I am trying to write a custom observation wrapper. As I was printing `[observation['equipped_items']['mainhand']['type']]` in my training runs when I encountered this error. The default value obtained is [0] (I presume this denotes None or Air). As the agent interacts with the environment and happens to hit a grass that drops a wheat_seed, it is registered as wheat_seeds instead of Other (from the minerl docs). Other items the agent picks up which throws a similar error includes egg and sapling. 

```[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
['wheat_seeds']
INFO     - 2019-09-13 13:47:30,951 - [chainerrl.experiments.train_agent save_agent 274] Saved the agent to results/20190913T133426.254244/32125_except
ERROR    - 2019-09-13 13:47:30,952 - [__main__ main 115] execution failed.
Traceback (most recent call last):
  File "/home/microway/Desktop/minerl/baselines/general/chainerrl/baselines/ppo_custom.py", line 113, in main
    _main(args)
  File "/home/microway/Desktop/minerl/baselines/general/chainerrl/baselines/ppo_custom.py", line 249, in _main
    save_best_so_far_agent=True,
  File "/home/microway/.conda/envs/minerl/lib/python3.7/site-packages/chainerrl/experiments/train_agent.py", line 163, in train_agent_with_evaluation
    logger=logger)
  File "/home/microway/.conda/envs/minerl/lib/python3.7/site-packages/chainerrl/experiments/train_agent.py", line 54, in train_agent
    obs, r, done, info = env.step(action)
  File "/home/microway/.conda/envs/minerl/lib/python3.7/site-packages/gym/core.py", line 282, in step
    return self.env.step(self.action(action))
  File "/home/microway/.conda/envs/minerl/lib/python3.7/site-packages/gym/core.py", line 259, in step
    return self.observation(observation), reward, done, info
  File "/home/microway/.conda/envs/minerl/lib/python3.7/site-packages/chainerrl/wrappers/atari_wrappers.py", line 241, in observation
    return np.array(observation).astype(np.float32) / self.scale
ValueError: could not convert string to float: 'wheat_seeds'

**Comment by brandonhoughton** [comment]
Thanks for the report! We're on this now
