### ISSUE TITLE
build failed?

### ISSUE THREAD

**Issue by dannyisbad** [minerllabs/minerl#278]
I'm trying to build minerl but it's not working at all, I've downloaded the source and used some of the code for treechop, still nothing. I got this error "* What went wrong:
Execution failed for task ':deobfMcMCP'.
> java.util.zip.ZipException: invalid stored block lengths

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 18.031 secs

Minecraft process finished unexpectedly. There was an error with Malmo."

while running it for the first time, while the second time I got this error (even when running it as admin)

"Traceback (most recent call last):
  File "test.py", line 4, in <module>
    env = gym.make("MineRLTreechop-v0")
  File "C:\Users\Danny\Anaconda3\lib\site-packages\gym\envs\registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "C:\Users\Danny\Anaconda3\lib\site-packages\gym\envs\registration.py", line 101, in make
    env = spec.make(**kwargs)
  File "C:\Users\Danny\Anaconda3\lib\site-packages\gym\envs\registration.py", line 73, in make
    env = cls(**_kwargs)
  File "C:\Users\Danny\Anaconda3\lib\site-packages\minerl\env\core.py", line 133, in __init__
    self.instance = self._get_new_instance(port)
  File "C:\Users\Danny\Anaconda3\lib\site-packages\minerl\env\core.py", line 155, in _get_new_instance
    instance.launch()
  File "C:\Users\Danny\Anaconda3\lib\site-packages\minerl\env\malmo.py", line 438, in launch
    shutil.copytree(os.path.join(InstanceManager.MINECRAFT_DIR), self.minecraft_dir)
  File "C:\Users\Danny\Anaconda3\lib\shutil.py", line 368, in copytree
    raise Error(errors)
shutil.Error: [('C:\\Users\\Danny\\Anaconda3\\lib\\site-packages\\minerl\\env\\Malmo\\Minecraft\\.gradle\\2.14\\taskArtifacts\\cache.properties.lock', 'C:\\Users\\Danny\\AppData\\Local\\Temp\\tmptjea0jpe\\Minecraft\\.gradle\\2.14\\taskArtifacts\\cache.properties.lock', '[Errno 13] Permission denied')]"

I'm using anaconda to run it in a container, but shortly after my mc launched as normal.

![image](https://user-images.githubusercontent.com/54243564/67267450-532d9c00-f480-11e9-81ed-11df95286020.png)

**Comment by dannyisbad** [comment]
Just another note: If I use py rather than python it gives me the first error, which is "Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Danny\Desktop\minerl\test.py", line 4, in <module>
    env = gym.make("MineRLTreechop-v0")
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python37\lib\site-packages\gym\envs\registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python37\lib\site-packages\gym\envs\registration.py", line 101, in make
    env = spec.make(**kwargs)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python37\lib\site-packages\gym\envs\registration.py", line 73, in make
    env = cls(**_kwargs)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python37\lib\site-packages\minerl\env\core.py", line 133, in __init__
    self.instance = self._get_new_instance(port)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python37\lib\site-packages\minerl\env\core.py", line 155, in _get_new_instance
    instance.launch()
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python37\lib\site-packages\minerl\env\malmo.py", line 453, in launch
    parent_pid, self.minecraft_process.pid, self.host, port, self.instance_dir)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python37\lib\site-packages\minerl\env\malmo.py", line 669, in _launch_process_watcher
    p.start()
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python37\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable."

and at the end "FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Danny\AppData\Local\Programs\Python\Python37\Lib\site-packages\minerl\env\Malmo\Minecraft\build.gradle' line: 228

* What went wrong:
Execution failed for task ':deobfMcMCP'.
> error reading zip file

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 23.919 secs


Minecraft process finished unexpectedly. There was an error with Malmo."

**Comment by MadcowD** [comment]
We're currently working on a new build script. It's a shame that we make end-users rebuild the library.

**Comment by brandonhoughton** [comment]
Closing as stale - please reopen if issue is still present!
