### ISSUE TITLE
TypeError: a bytes-like object is required, not 'NoneType'

### ISSUE THREAD

**Issue by shadowyzy** [minerllabs/minerl#280]
```
Traceback (most recent call last):
  File "metacontroller.py", line 209, in <module>
    train()
  File "metacontroller.py", line 123, in train
    rew, done = agent2.step2(50, env, m_obs, m_inv, 1)
  File "/home/yuziyi/minerl/metacontroller/now/craft.py", line 196, in step2
    obs, rew, done, info, t = envstep(env, action_num, kind)
  File "/home/yuziyi/minerl/metacontroller/now/craft.py", line 295, in envstep
    return nearbycraft(env, reward, done, 4, kind)
  File "/home/yuziyi/minerl/metacontroller/now/craft.py", line 301, in nearbycraft
    obs, rew, done, info = envstep_done(env, action, done)
  File "/home/yuziyi/minerl/metacontroller/now/craft.py", line 321, in envstep_done
    return env.step(act)
  File "/home/yuziyi/anaconda3/envs/my_env/lib/python3.6/site-packages/gym/wrappers/time_limit.py", line 16, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/yuziyi/anaconda3/envs/my_env/lib/python3.6/site-packages/minerl/env/core.py", line 547, in step
    reward, done, sent = struct.unpack('!dbb', reply)
TypeError: a bytes-like object is required, not 'NoneType'
Attempted to send kill command to minecraft process and failed.

**Comment by MadcowD** [comment]
This happens when the Malmo simulator is unresponsive. This should be fixed when we switch away from Malmo.

**Comment by Skirlax** [comment]
Is there some fix to this? At least temporary?

Thanks.
