### ISSUE TITLE
gym.Make() raises Permission Denied error [ERRNO 13]

### ISSUE THREAD

**Issue by fedetask** [minerllabs/minerl#299]
Ubuntu version: 18.0.4
Python version: 3.7
minerl version: 0.2.9

Making an environment with

```python
import minerl
import gym

env = gym.make('MineRLNavigateDense-v0')
```

rasises the following

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fedetask/Desktop/behavior-trees-reinforcement-learning/venv/lib/python3.7/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/fedetask/Desktop/behavior-trees-reinforcement-learning/venv/lib/python3.7/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/home/fedetask/Desktop/behavior-trees-reinforcement-learning/venv/lib/python3.7/site-packages/gym/envs/registration.py", line 60, in make
    env = cls(**_kwargs)
  File "/home/fedetask/Desktop/behavior-trees-reinforcement-learning/venv/lib/python3.7/site-packages/minerl/env/core.py", line 133, in __init__
    self.instance = self._get_new_instance(port)
  File "/home/fedetask/Desktop/behavior-trees-reinforcement-learning/venv/lib/python3.7/site-packages/minerl/env/core.py", line 155, in _get_new_instance
    instance.launch()
  File "/home/fedetask/Desktop/behavior-trees-reinforcement-learning/venv/lib/python3.7/site-packages/minerl/env/malmo.py", line 448, in launch
    self.minecraft_dir)
  File "/home/fedetask/Desktop/behavior-trees-reinforcement-learning/venv/lib/python3.7/site-packages/minerl/env/malmo.py", line 647, in _launch_minecraft
    preexec_fn=preexec_fn
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/tmp/tmpg90rdo47/Minecraft/launchClient.sh'
```

Do you have any tips?

**Comment by MadcowD** [comment]
Hmm do you have permission to make files in your `tmp` directory?

**Comment by fedetask** [comment]
Yes I do

**Comment by MadcowD** [comment]
Perhaps the sh file is not executable.

**Comment by MadcowD** [comment]
Did you install from pip?

**Comment by fedetask** [comment]
Sorry, I lost track of this issue. Yes, I installed from pip3 in a virtualenv

**Comment by fedetask** [comment]
I solved the issue. Using python 3.6.9 instead of 3.7.5 makes it work
