### ISSUE TITLE
MineRLNavigateDenseVectorObf-v0 cannot call reset

### ISSUE THREAD

**Issue by s-shiroshita** [minerllabs/minerl#302]
I tried to run the following code using `MineRLNavigateDenseVectorObf-v0`:
```
import minerl
import gym

def main():
    env = gym.make('MineRLNavigateDenseVectorObf-v0')
    print(env.reset())
    env.close()

if __name__ == '__main__':
    main()
```

but I got the following error:
```
$ python test.py 
/Users/sshiroshita/.local/share/virtualenvs/minerl2020-IWA6Vnra/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    main()
  File "test.py", line 6, in main
    print(env.reset())
  File "/Users/sshiroshita/.local/share/virtualenvs/minerl2020-IWA6Vnra/lib/python3.7/site-packages/minerl/env/core.py", line 446, in reset
    return self._start_up()
  File "/Users/sshiroshita/.local/share/virtualenvs/minerl2020-IWA6Vnra/lib/python3.7/site-packages/minerl/env/core.py", line 468, in _start_up
    return self._peek_obs()
  File "/Users/sshiroshita/.local/share/virtualenvs/minerl2020-IWA6Vnra/lib/python3.7/site-packages/minerl/env/core.py", line 527, in _peek_obs
    return self._process_observation(obs, info)
  File "/Users/sshiroshita/.local/share/virtualenvs/minerl2020-IWA6Vnra/lib/python3.7/site-packages/minerl/env/core.py", line 380, in _process_observation
    obs_dict = self.env_spec.wrap_observation(obs_dict)
  File "/Users/sshiroshita/.local/share/virtualenvs/minerl2020-IWA6Vnra/lib/python3.7/site-packages/minerl/herobraine/wrapper.py", line 26, in wrap_observation
    obs = self.env_to_wrap.wrap_observation(obs)
  File "/Users/sshiroshita/.local/share/virtualenvs/minerl2020-IWA6Vnra/lib/python3.7/site-packages/minerl/herobraine/wrapper.py", line 28, in wrap_observation
    assert obs in self.env_to_wrap.observation_space
  File "/Users/sshiroshita/.local/share/virtualenvs/minerl2020-IWA6Vnra/lib/python3.7/site-packages/gym/spaces/space.py", line 34, in __contains__
    return self.contains(x)
  File "/Users/sshiroshita/.local/share/virtualenvs/minerl2020-IWA6Vnra/lib/python3.7/site-packages/gym/spaces/dict.py", line 59, in contains
    if not space.contains(x[k]):
  File "/Users/sshiroshita/.local/share/virtualenvs/minerl2020-IWA6Vnra/lib/python3.7/site-packages/gym/spaces/box.py", line 128, in contains
    return x.shape == self.shape and np.all(x >= self.low) and np.all(x <= self.high)
AttributeError: 'float' object has no attribute 'shape'
Terminated: 15
```

It seems to happen only in Navigation-related tasks.
Could you check the conversion around `compassAngle`?

**Comment by MadcowD** [comment]
Yep! Good catch

**Comment by MadcowD** [comment]
@s-shiroshita Please pull
