### ISSUE TITLE
Navigate Obf environments don't work

### ISSUE THREAD

**Issue by MadcowD** [minerllabs/minerl#323]
Traceback (most recent call last):
  File ".../lib/python3.6/site-packages/ray/tune/trial_runner.py", line 467, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File ".../lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 431, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File ".../lib/python3.6/site-packages/ray/worker.py", line 1515, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AssertionError): ray::SAC.train() (pid=5509, ip=192.168.17.105)
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 417, in ray._raylet.execute_task.function_executor
  File ".../lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 498, in train
    raise e
  File ".../lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 484, in train
    result = Trainable.train(self)
  File ".../lib/python3.6/site-packages/ray/tune/trainable.py", line 261, in train
    result = self._train()
  File ".../lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 151, in _train
    fetches = self.optimizer.step()
  File ".../lib/python3.6/site-packages/ray/rllib/optimizers/sync_replay_optimizer.py", line 127, in step
    batch = self.workers.local_worker().sample()
  File ".../lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 510, in sample
    batches = [self.input_reader.next()]
  File ".../lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 54, in next
    batches = [self.get_data()]
  File ".../lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 98, in get_data
    item = next(self.rollout_provider)
  File ".../lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 371, in _env_runner
    base_env.send_actions(actions_to_send)
  File ".../lib/python3.6/site-packages/ray/rllib/env/base_env.py", line 328, in send_actions
    self.vector_env.vector_step(action_vector)
  File ".../lib/python3.6/site-packages/ray/rllib/env/vector_env.py", line 106, in vector_step
    obs, r, done, info = self.envs[i].step(actions[i])
  File ".../lib/python3.6/site-packages/gym/core.py", line 285, in step
    return self.env.step(self.action(action))
  File ".../lib/python3.6/site-packages/gym/core.py", line 285, in step
    return self.env.step(self.action(action))
  File ".../lib/python3.6/site-packages/gym/core.py", line 261, in step
    observation, reward, done, info = self.env.step(action)
  File ".../lib/python3.6/site-packages/minerl/env/core.py", line 553, in step
    malmo_command = self._process_action(action)
  File ".../lib/python3.6/site-packages/minerl/env/core.py", line 410, in _process_action
    act, action_in[act])
AssertionError: Invalid value for enum action place, stone

**Comment by MadcowD** [comment]
Fixed by #322 

Upgrade to `minerl >= 0.3.2`
