### ISSUE TITLE
minerl.interactor fails to start because of handled exception from shutil

### ISSUE THREAD

**Issue by ofer1992** [minerllabs/minerl#366]
While trying to start minerl.interactor I ran into the following error:
**traceback:**
```
(base) λ python -m minerl.interactor --debug 5551
C:\Users\ofer\miniconda3\lib\site-packages\gym\logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
2020-07-25 15:14:50 Anat __main__[18388] WARNING No existing interactor found on port 31415. Starting a new interactor.
Traceback (most recent call last):
  File "C:\Users\ofer\miniconda3\lib\site-packages\minerl\interactor\__main__.py", line 40, in run_interactor
    InstanceManager.add_existing_instance(interactor_port)
  File "C:\Users\ofer\miniconda3\lib\site-packages\minerl\env\malmo.py", line 244, in add_existing_instance
    assert cls._is_port_taken(port), "No Malmo mod utilizing the port specified."
AssertionError: No Malmo mod utilizing the port specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ofer\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\ofer\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ofer\miniconda3\lib\site-packages\minerl\interactor\__main__.py", line 73, in <module>
    run_interactor(ip=opts.ip, port=opts.port)
  File "C:\Users\ofer\miniconda3\lib\site-packages\minerl\interactor\__main__.py", line 46, in run_interactor
    instance.launch(daemonize=True)
  File "C:\Users\ofer\miniconda3\lib\site-packages\minerl\env\malmo.py", line 469, in launch
    shutil.copytree(os.path.join(InstanceManager.MINECRAFT_DIR), self.minecraft_dir)
  File "C:\Users\ofer\miniconda3\lib\shutil.py", line 368, in copytree
    raise Error(errors)
shutil.Error: [('C:\\Users\\ofer\\miniconda3\\lib\\site-packages\\minerl\\env\\Malmo\\Minecraft\\.gradle\\2.14\\taskArtifacts\\cache.properties.lock', 'C:\\Users\\ofer\\AppData\\Local\\Temp\\tmpryl1d8r3\\Minecraft\\.gradle\\2.14\\taskArtifacts\\cache.properties.lock', '[Errno 13] Permission denied')]
```
After tinkering around I figured that the file _cache.properties.lock_ is not copied for some reason, yet the rest of the files are copied without problem. The exception raised by shutil.copytree causes launch() in malmo.py to fail. Adding a try except block around the calls to shutil.copytree allowed execution to carry on without other issues.

Anyway, perhaps this warrants a better handling of the error?

**Comment by ofer1992** [comment]
Seems like this issue has already been dicussed here
#210 and here #351.

**Comment by MadcowD** [comment]
Got it,

We're working on a PR right now that will get us a lot further towards fixing this bug.

https://github.com/minerllabs/minerl/pull/350

This effectively stop gradle from building MC everytime Minecraft is launched.
