### ISSUE TITLE
initialize any game mod get stuck

### ISSUE THREAD

**Issue by XDang13** [minerllabs/minerl#372]
The script get stuck at gym.make("env-name"). I tried MineRLTreechop-v0, MineRLNavigateDense-v0 and MineRLObtainDiamondVectorObf-v0. When stop the script manually, I got message:
Traceback (most recent call last):
  File ".\test.py", line 32, in <module>
  File ".\test.py", line 7, in main
    env = gym.make("MineRLObtainDiamondVectorObf-v0")
  File "C:\Users\birdh\AppData\Local\Programs\Python\Python38\lib\site-packages\gym\envs\registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "C:\Users\birdh\AppData\Local\Programs\Python\Python38\lib\site-packages\gym\envs\registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "C:\Users\birdh\AppData\Local\Programs\Python\Python38\lib\site-packages\gym\envs\registration.py", line 60, in make
    env = cls(**_kwargs)
  File "C:\Users\birdh\AppData\Local\Programs\Python\Python38\lib\site-packages\minerl\env\core.py", line 137, in __init__
    self.instance = self._get_new_instance(port)
  File "C:\Users\birdh\AppData\Local\Programs\Python\Python38\lib\site-packages\minerl\env\core.py", line 159, in _get_new_instance
    instance.launch()
  File "C:\Users\birdh\AppData\Local\Programs\Python\Python38\lib\site-packages\minerl\env\malmo.py", line 498, in launch
    line = self.minecraft_process.stdout.readline().decode(mine_log_encoding)
KeyboardInterrupt

**Comment by Miffyli** [comment]
First time launching MineRL env takes long time as it compiles things. `gym.make` should throw an exception if something goes wrong, so let the code run for a good while (+10 minutes) before digging into it deeper.

**Comment by XDang13** [comment]
Problem solved. For the first time to initialize the MineRL env it may take at least 30 mins to set all the configuration include java. Then it will take 1mins to 2mins to initialize the MineRL env each time on my computer.
