### ISSUE TITLE
data_directory: os.path

### ISSUE THREAD

**Issue by Mar1noc** [minerllabs/minerl#443]
When I try to run the code I get this

Traceback (most recent call last):
  File "C:\Users\User\Desktop\minerl-master\datebaes.py", line 1, in <module>
    import minerl
  File "C:\Users\User\Desktop\minerl-master\minerl\__init__.py", line 4, in <module>
    import minerl.data
  File "C:\Users\User\Desktop\minerl-master\minerl\data\__init__.py", line 1, in <module>
    from minerl.data.data_pipeline import DataPipeline
  File "C:\Users\User\Desktop\minerl-master\minerl\data\data_pipeline.py", line 52
    data_directory: os.path,
                  ^
SyntaxError: invalid syntax

How to fix that?

the code:
_`import minerl
import gym
env = gym.make('MineRLNavigateDense-v0')

obs = env.reset()

done = False
while not done:
    action = env.action_space.sample() 
 
    # One can also take a no_op action with
    # action =env.action_space.noop()
    
 
    obs, reward, done, info = env.step(
        action)`_

**Comment by brandonhoughton** [comment]
Can you try this again on the latest version of MineRL? `python -m pip install --upgrade minerl`

**Comment by shwang** [comment]
This looks like a syntax error due to loading Python 3 parameter annotation syntax using a python 2 parser. (Or maybe a version of python before python 3.5).

Closing this issue since it's been a while since it was raised, and probably was a python version issue.
