### ISSUE TITLE
An error with malmo

### ISSUE THREAD

**Issue by JunkWarrior001** [minerllabs/minerl#598]
Hello, everyone. When I run my code with xvfb-run python3 xxx.py, the error below occured. 
Traceback (most recent call last):
  File "mtest.py", line 6, in <module>
    obs=env.reset()
  File "/home/junkwarrior/.conda/envs/basalt/lib/python3.7/site-packages/gym/wrappers/time_limit.py", line 27, in reset
    return self.env.reset(**kwargs)
  File "/home/junkwarrior/.conda/envs/basalt/lib/python3.7/site-packages/minerl/env/_singleagent.py", line 22, in reset
    multi_obs = super().reset()
  File "/home/junkwarrior/.conda/envs/basalt/lib/python3.7/site-packages/minerl/env/_multiagent.py", line 455, in reset
    self._setup_instances()
  File "/home/junkwarrior/.conda/envs/basalt/lib/python3.7/site-packages/minerl/env/_multiagent.py", line 556, in _setup_instances
    self.instances.extend([f.result() for f in instance_futures])
  File "/home/junkwarrior/.conda/envs/basalt/lib/python3.7/site-packages/minerl/env/_multiagent.py", line 556, in <listcomp>
    self.instances.extend([f.result() for f in instance_futures])
  File "/home/junkwarrior/.conda/envs/basalt/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/junkwarrior/.conda/envs/basalt/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/junkwarrior/.conda/envs/basalt/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/junkwarrior/.conda/envs/basalt/lib/python3.7/site-packages/minerl/env/_multiagent.py", line 807, in _get_new_instance
    instance.launch(replaceable=self._is_fault_tolerant)
  File "/home/junkwarrior/.conda/envs/basalt/lib/python3.7/site-packages/minerl/env/malmo.py", line 530, in launch
    error_str + "\n\nMinecraft process finished unexpectedly. There was an error with Malmo.")
EOFError: /tmp/tmpirobvigr/Minecraft
# Configuration file
# Autogenerated from command-line options

malmoports {
  I:portOverride=12736
}
malmoscore {
  I:policy=0
}

malmoperformance {
  I:outDir=NONE
}

malmoseed {
  I:seed=NONE
}

runtype {
  B:replaceable=true
}

envtype {
  B:env=true
}

/tmp/tmpirobvigr/Minecraft/run

[21:15:15] [main/INFO]: Extra: []
[21:15:15] [main/INFO]: Found and added coremod: com.microsoft.Malmo.OverclockingPlugin
[21:15:15] [main/INFO]: Running with arguments: [--userProperties, {}, --assetsDir, /tmp/tmpirobvigr/Minecraft/run/gradle/caches/minecraft/assets, --assetIndex, 1.11, --accessToken{REDACTED}, --version, 1.11.2, --tweakClass, net.minecraftforge.fml.common.launcher.FMLTweaker, --tweakClass, com.microsoft.Malmo.Launcher.tweakers.CoremodTweaker]
[21:15:15] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:15:15] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:15:15] [main/INFO]: Loading tweak class name com.microsoft.Malmo.Launcher.tweakers.CoremodTweaker
[21:15:15] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[21:15:15] [main/INFO]: Forge Mod Loader version 13.20.1.2588 for Minecraft 1.11.2 loading
[21:15:15] [main/INFO]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_302, running on Linux:amd64:3.10.0-1160.36.2.el7.x86_64, installed at /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.302.b08-0.el7_9.x86_64/jre
[21:15:15] [main/INFO]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[21:15:15] [main/INFO]: Found a command line coremod : com.microsoft.Malmo.OverclockingPlugin
[21:15:15] [main/WARN]: The coremod com.microsoft.Malmo.OverclockingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:15:21] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.5 Source=file:/tmp/tmpirobvigr/Minecraft/build/libs/MalmoMod-0.37.0-fat.jar Service=LaunchWrapper Env=CLIENT
[21:15:21] [main/INFO]: Compatibility level set to JAVA_8
[21:15:21] [main/INFO]: Calling tweak class com.microsoft.Malmo.Launcher.tweakers.CoremodTweaker
[21:15:21] [main/INFO]: Injecting location in coremod net.minecraftforge.fml.relauncher.FMLCorePlugin
[21:15:21] [main/INFO]: Injecting location in coremod net.minecraftforge.classloading.FMLForgePlugin
[21:15:21] [main/INFO]: Injecting location in coremod com.microsoft.Malmo.OverclockingPlugin
[21:15:21] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:15:21] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[21:15:21] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:15:21] [main/INFO]: Loading tweak class name com.microsoft.Malmo.Launcher.tweakers.AccessTransformerTweaker
[21:15:21] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:15:21] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:15:21] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:15:21] [main/ERROR]: The binary patch set is missing. Either you are in a development environment, or things are not going to work!
[21:15:21] [main/ERROR]: FML appears to be missing any signature data. This is not a good thing
[21:15:21] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:15:21] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:15:21] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[21:15:21] [main/INFO]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@65f87a2c
[21:15:21] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:15:22] [main/INFO]: Calling tweak class com.microsoft.Malmo.Launcher.tweakers.AccessTransformerTweaker
[21:15:22] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[21:15:22] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[21:15:22] [main/WARN]: Reference map 'mixins.malmo.refmap.json' for mixins.overclocking.malmomod.json could not be read. If this is a development environment you can ignore this message
[21:15:22] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[21:15:22] [main/INFO]: [com.microsoft.Malmo.OverclockingClassTransformer:insertTextureHandler:120]: MALMO: Found GlStateManager, attempting to transform it
[21:15:22] [main/INFO]: [com.microsoft.Malmo.OverclockingClassTransformer:insertTextureHandler:126]: MALMO: Found GlStateManager.bindTexture() method, attempting to transform it
[21:15:22] [main/INFO]: [com.microsoft.Malmo.OverclockingClassTransformer:insertTextureHandler:139]: MALMO: Hooked into call to GlStateManager.bindTexture()
[21:15:22] [main/INFO]: A re-entrant transformer '$wrapper.com.microsoft.Malmo.OverclockingClassTransformer' was detected and will no longer process meta class data
[21:15:22] [main/INFO]: [com.microsoft.Malmo.OverclockingClassTransformer:transform:42]: Transformed Name: net.minecraft.client.entity.EntityPlayerSP
[21:15:22] [main/INFO]: [com.microsoft.Malmo.OverclockingClassTransformer:transform:42]: Transformed Name: net.minecraft.client.entity.AbstractClientPlayer
No protocol specified
[21:15:22] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [MalmoMod-0.37.0-fat.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [MalmoMod-0.37.0-fat.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302]
        at com.microsoft.Malmo.Launcher.GradleStartCommon.launch(GradleStartCommon.java:98) [MalmoMod-0.37.0-fat.jar:?]
        at com.microsoft.Malmo.Launcher.GradleStart.main(GradleStart.java:27) [MalmoMod-0.37.0-fat.jar:?]
Caused by: java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
        at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method) ~[?:1.8.0_302]
        at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65) ~[?:1.8.0_302]
        at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115) ~[?:1.8.0_302]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_302]
        at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74) ~[?:1.8.0_302]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_302]
        at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_302]
        at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103) ~[?:1.8.0_302]
        at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82) ~[?:1.8.0_302]
        at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:131) ~[?:1.8.0_302]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_302]
        at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_302]
        at java.awt.Toolkit$2.run(Toolkit.java:860) ~[?:1.8.0_302]
        at java.awt.Toolkit$2.run(Toolkit.java:855) ~[?:1.8.0_302]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_302]
        at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854) ~[?:1.8.0_302]
        at org.lwjgl.LinuxSysImplementation.<clinit>(LinuxSysImplementation.java:50) ~[MalmoMod-0.37.0-fat.jar:?]
        at org.lwjgl.Sys.createImplementation(Sys.java:131) ~[MalmoMod-0.37.0-fat.jar:?]
        at org.lwjgl.Sys.<clinit>(Sys.java:116) ~[MalmoMod-0.37.0-fat.jar:?]
        at net.minecraft.client.Minecraft.getSystemTime(Minecraft.java:2886) ~[Minecraft.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:39) ~[Main.class:?]
        ... 12 more
Exception in thread "main" [21:15:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.reflect.InvocationTargetException
[21:15:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]:         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:15:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]:         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:15:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:15:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]:         at java.lang.reflect.Method.invoke(Method.java:498)
[21:15:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]:         at com.microsoft.Malmo.Launcher.GradleStartCommon.launch(GradleStartCommon.java:98)
[21:15:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]:         at com.microsoft.Malmo.Launcher.GradleStart.main(GradleStart.java:27)
[21:15:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[21:15:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]:         at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[21:15:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]:         at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[21:15:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]:         at java.lang.Runtime.exit(Runtime.java:107)
[21:15:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]:         at java.lang.System.exit(System.java:973)
[21:15:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]:         at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[21:15:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]:         at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:15:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]:         ... 6 more

Minecraft process finished unexpectedly. There was an error with Malmo.
(basalt) [junkwarrior@localhost her]$ xvfb-run python3 mtest.py
/home/junkwarrior/.conda/envs/basalt/lib/python3.7/site-packages/gym/logger.py:34: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))
/home/junkwarrior/.conda/envs/basalt/lib/python3.7/site-packages/gym/logger.py:34: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))
/home/junkwarrior/.conda/envs/basalt/lib/python3.7/runpy.py:125: RuntimeWarning: 'minerl.utils.process_watcher' found in sys.modules after import of package 'minerl.utils', but prior to execution of 'minerl.utils.process_watcher'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Traceback (most recent call last):
  File "mtest.py", line 6, in <module>
    obs=env.reset()
  File "/home/junkwarrior/.conda/envs/basalt/lib/python3.7/site-packages/gym/wrappers/time_limit.py", line 27, in reset
    return self.env.reset(**kwargs)
  File "/home/junkwarrior/.conda/envs/basalt/lib/python3.7/site-packages/minerl/env/_singleagent.py", line 22, in reset
    multi_obs = super().reset()
  File "/home/junkwarrior/.conda/envs/basalt/lib/python3.7/site-packages/minerl/env/_multiagent.py", line 455, in reset
    self._setup_instances()
  File "/home/junkwarrior/.conda/envs/basalt/lib/python3.7/site-packages/minerl/env/_multiagent.py", line 556, in _setup_instances
    self.instances.extend([f.result() for f in instance_futures])
  File "/home/junkwarrior/.conda/envs/basalt/lib/python3.7/site-packages/minerl/env/_multiagent.py", line 556, in <listcomp>
    self.instances.extend([f.result() for f in instance_futures])
  File "/home/junkwarrior/.conda/envs/basalt/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/junkwarrior/.conda/envs/basalt/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/junkwarrior/.conda/envs/basalt/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/junkwarrior/.conda/envs/basalt/lib/python3.7/site-packages/minerl/env/_multiagent.py", line 807, in _get_new_instance
    instance.launch(replaceable=self._is_fault_tolerant)
  File "/home/junkwarrior/.conda/envs/basalt/lib/python3.7/site-packages/minerl/env/malmo.py", line 530, in launch
    error_str + "\n\nMinecraft process finished unexpectedly. There was an error with Malmo.")
EOFError: /tmp/tmp2u5oxtuz/Minecraft
# Configuration file
# Autogenerated from command-line options

malmoports {
  I:portOverride=10181
}
malmoscore {
  I:policy=0
}

malmoperformance {
  I:outDir=NONE
}

malmoseed {
  I:seed=NONE
}

runtype {
  B:replaceable=true
}

envtype {
  B:env=true
}

/tmp/tmp2u5oxtuz/Minecraft/run

[21:16:15] [main/INFO]: Extra: []
[21:16:15] [main/INFO]: Found and added coremod: com.microsoft.Malmo.OverclockingPlugin
[21:16:15] [main/INFO]: Running with arguments: [--userProperties, {}, --assetsDir, /tmp/tmp2u5oxtuz/Minecraft/run/gradle/caches/minecraft/assets, --assetIndex, 1.11, --accessToken{REDACTED}, --version, 1.11.2, --tweakClass, net.minecraftforge.fml.common.launcher.FMLTweaker, --tweakClass, com.microsoft.Malmo.Launcher.tweakers.CoremodTweaker]
[21:16:15] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:16:15] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:16:15] [main/INFO]: Loading tweak class name com.microsoft.Malmo.Launcher.tweakers.CoremodTweaker
[21:16:15] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[21:16:15] [main/INFO]: Forge Mod Loader version 13.20.1.2588 for Minecraft 1.11.2 loading
[21:16:15] [main/INFO]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_302, running on Linux:amd64:3.10.0-1160.36.2.el7.x86_64, installed at /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.302.b08-0.el7_9.x86_64/jre
[21:16:15] [main/INFO]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[21:16:15] [main/INFO]: Found a command line coremod : com.microsoft.Malmo.OverclockingPlugin
[21:16:15] [main/WARN]: The coremod com.microsoft.Malmo.OverclockingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:16:21] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.5 Source=file:/tmp/tmp2u5oxtuz/Minecraft/build/libs/MalmoMod-0.37.0-fat.jar Service=LaunchWrapper Env=CLIENT
[21:16:21] [main/INFO]: Compatibility level set to JAVA_8
[21:16:21] [main/INFO]: Calling tweak class com.microsoft.Malmo.Launcher.tweakers.CoremodTweaker
[21:16:21] [main/INFO]: Injecting location in coremod net.minecraftforge.fml.relauncher.FMLCorePlugin
[21:16:21] [main/INFO]: Injecting location in coremod net.minecraftforge.classloading.FMLForgePlugin
[21:16:21] [main/INFO]: Injecting location in coremod com.microsoft.Malmo.OverclockingPlugin
[21:16:21] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:16:21] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[21:16:21] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:16:21] [main/INFO]: Loading tweak class name com.microsoft.Malmo.Launcher.tweakers.AccessTransformerTweaker
[21:16:21] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:16:21] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:16:21] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:16:21] [main/ERROR]: The binary patch set is missing. Either you are in a development environment, or things are not going to work!
[21:16:21] [main/ERROR]: FML appears to be missing any signature data. This is not a good thing
[21:16:21] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:16:21] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:16:21] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[21:16:21] [main/INFO]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@65f87a2c
[21:16:21] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:16:21] [main/INFO]: Calling tweak class com.microsoft.Malmo.Launcher.tweakers.AccessTransformerTweaker
[21:16:21] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[21:16:21] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[21:16:22] [main/WARN]: Reference map 'mixins.malmo.refmap.json' for mixins.overclocking.malmomod.json could not be read. If this is a development environment you can ignore this message
[21:16:22] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[21:16:22] [main/INFO]: [com.microsoft.Malmo.OverclockingClassTransformer:insertTextureHandler:120]: MALMO: Found GlStateManager, attempting to transform it
[21:16:22] [main/INFO]: [com.microsoft.Malmo.OverclockingClassTransformer:insertTextureHandler:126]: MALMO: Found GlStateManager.bindTexture() method, attempting to transform it
[21:16:22] [main/INFO]: [com.microsoft.Malmo.OverclockingClassTransformer:insertTextureHandler:139]: MALMO: Hooked into call to GlStateManager.bindTexture()
[21:16:22] [main/INFO]: A re-entrant transformer '$wrapper.com.microsoft.Malmo.OverclockingClassTransformer' was detected and will no longer process meta class data
[21:16:22] [main/INFO]: [com.microsoft.Malmo.OverclockingClassTransformer:transform:42]: Transformed Name: net.minecraft.client.entity.EntityPlayerSP
[21:16:22] [main/INFO]: [com.microsoft.Malmo.OverclockingClassTransformer:transform:42]: Transformed Name: net.minecraft.client.entity.AbstractClientPlayer
[21:16:22] [Client thread/INFO]: Setting user: Player650
[21:16:24] [Client thread/WARN]: Skipping bad option: lastServer:
[21:16:24] [Client thread/INFO]: LWJGL Version: 2.9.4
[21:16:24] [Client thread/ERROR]: Couldn't set pixel format
org.lwjgl.LWJGLException: Could not init GLX
        at org.lwjgl.opengl.LinuxDisplayPeerInfo.initDefaultPeerInfo(Native Method) ~[MalmoMod-0.37.0-fat.jar:?]
        at org.lwjgl.opengl.LinuxDisplayPeerInfo.<init>(LinuxDisplayPeerInfo.java:61) ~[MalmoMod-0.37.0-fat.jar:?]
        at org.lwjgl.opengl.LinuxDisplay.createPeerInfo(LinuxDisplay.java:828) ~[MalmoMod-0.37.0-fat.jar:?]
        at org.lwjgl.opengl.DrawableGL.setPixelFormat(DrawableGL.java:61) ~[MalmoMod-0.37.0-fat.jar:?]
        at org.lwjgl.opengl.Display.create(Display.java:846) ~[MalmoMod-0.37.0-fat.jar:?]
        at org.lwjgl.opengl.Display.create(Display.java:757) ~[MalmoMod-0.37.0-fat.jar:?]
        at net.minecraft.client.Minecraft.createDisplay(Minecraft.java:574) [Minecraft.class:?]
        at net.minecraft.client.Minecraft.init(Minecraft.java:431) [Minecraft.class:?]
        at net.minecraft.client.Minecraft.run(Minecraft.java:352) [Minecraft.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [MalmoMod-0.37.0-fat.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [MalmoMod-0.37.0-fat.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302]
        at com.microsoft.Malmo.Launcher.GradleStartCommon.launch(GradleStartCommon.java:98) [MalmoMod-0.37.0-fat.jar:?]
        at com.microsoft.Malmo.Launcher.GradleStart.main(GradleStart.java:27) [MalmoMod-0.37.0-fat.jar:?]
[21:16:25] [Client thread/INFO]: [STDOUT]: MALMO: Found GlStateManager, attempting to transform it
[21:16:25] [Client thread/INFO]: [STDOUT]: MALMO: Found GlStateManager.bindTexture() method, attempting to transform it
[21:16:25] [Client thread/INFO]: [STDOUT]: MALMO: Hooked into call to GlStateManager.bindTexture()
[21:16:25] [Client thread/INFO]: [net.minecraft.init.Bootstrap:printToSYSOUT:523]: ---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 10/16/21 9:16 PM
Description: Initializing game

org.lwjgl.LWJGLException: Could not init GLX
        at org.lwjgl.opengl.LinuxDisplayPeerInfo.initDefaultPeerInfo(Native Method)
        at org.lwjgl.opengl.LinuxDisplayPeerInfo.<init>(LinuxDisplayPeerInfo.java:61)
        at org.lwjgl.opengl.LinuxDisplay.createPeerInfo(LinuxDisplay.java:828)
        at org.lwjgl.opengl.DrawableGL.setPixelFormat(DrawableGL.java:61)
        at org.lwjgl.opengl.Display.create(Display.java:846)
        at org.lwjgl.opengl.Display.create(Display.java:757)
        at org.lwjgl.opengl.Display.create(Display.java:739)
        at net.minecraft.client.Minecraft.createDisplay(Minecraft.java:594)
        at net.minecraft.client.Minecraft.init(Minecraft.java:431)
        at net.minecraft.client.Minecraft.run(Minecraft.java:352)
        at net.minecraft.client.main.Main.main(SourceFile:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.microsoft.Malmo.Launcher.GradleStartCommon.launch(GradleStartCommon.java:98)
        at com.microsoft.Malmo.Launcher.GradleStart.main(GradleStart.java:27)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
        at org.lwjgl.opengl.LinuxDisplayPeerInfo.initDefaultPeerInfo(Native Method)
        at org.lwjgl.opengl.LinuxDisplayPeerInfo.<init>(LinuxDisplayPeerInfo.java:61)
        at org.lwjgl.opengl.LinuxDisplay.createPeerInfo(LinuxDisplay.java:828)
        at org.lwjgl.opengl.DrawableGL.setPixelFormat(DrawableGL.java:61)
        at org.lwjgl.opengl.Display.create(Display.java:846)
        at org.lwjgl.opengl.Display.create(Display.java:757)
        at org.lwjgl.opengl.Display.create(Display.java:739)
        at net.minecraft.client.Minecraft.createDisplay(Minecraft.java:594)
        at net.minecraft.client.Minecraft.init(Minecraft.java:431)

-- Initialization --
Details:
Stacktrace:
        at net.minecraft.client.Minecraft.run(Minecraft.java:352)
        at net.minecraft.client.main.Main.main(SourceFile:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.microsoft.Malmo.Launcher.GradleStartCommon.launch(GradleStartCommon.java:98)
        at com.microsoft.Malmo.Launcher.GradleStart.main(GradleStart.java:27)

-- System Details --
Details:
        Minecraft Version: 1.11.2
        Operating System: Linux (amd64) version 3.10.0-1160.36.2.el7.x86_64
        Java Version: 1.8.0_302, Red Hat, Inc.
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Red Hat, Inc.
        Memory: 1119454408 bytes (1067 MB) / 1287651328 bytes (1228 MB) up to 1908932608 bytes (1820 MB)
        JVM Flags: 1 total; -Xmx2G
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        FML:
        Loaded coremods (and transformers):
OverclockingPlugin (MalmoMod-0.37.0-fat.jar)
  com.microsoft.Malmo.OverclockingClassTransformer
        Launched Version: 1.11.2
        LWJGL: 2.9.4
        OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
        GL Caps:
        Using VBOs: Yes
        Is Modded: Definitely; Client brand changed to 'fml,forge'
        Type: Client (map_client.txt)
        Resource Packs:
        Current Language: ~~ERROR~~ NullPointerException: null
        Profiler Position: N/A (disabled)
        CPU: <unknown>
[21:16:25] [Client thread/INFO]: [net.minecraft.init.Bootstrap:printToSYSOUT:523]: #@!@# Game crashed! Crash report saved to: #@!@# /tmp/tmp2u5oxtuz/Minecraft/run/./crash-reports/crash-2021-10-16_21.16.25-client.txt

Minecraft process finished unexpectedly. There was an error with Malmo.

The java version is:
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (build 25.302-b08, mixed mode)

Help!!

**Comment by Miffyli** [comment]
Try running it with `xvfb-run -a python3 [your script]` (the "-a" flag might be necessary). If possible, do a debug test with headed machine (e.g. one with a GPU and display attached).

Tip: Put your logs/code into triple-quotation marks like this for prettier results :) 
\```
logs go here and will look nice
\```
