### ISSUE TITLE
Got errors on the custom environment example

### ISSUE THREAD

**Issue by mwang808** [minerllabs/minerl#609]
Hello,

I try to run the "mlg_wb_solution.py" file provided in the tutorial but got the following errors. Can you tell me how to fix it? Thanks.

I am using ubuntu 20.04. The error information is below.

Traceback (most recent call last):
  File "mlg_wb_solution.py", line 16, in <module>
    obs  = env.reset()
  File "/home/xxx/.local/lib/python3.8/site-packages/gym/wrappers/time_limit.py", line 27, in reset
    return self.env.reset(**kwargs)
  File "/home/xxx/.local/lib/python3.8/site-packages/minerl/env/_singleagent.py", line 22, in reset
    multi_obs = super().reset()
  File "/home/xxx/.local/lib/python3.8/site-packages/minerl/env/_multiagent.py", line 452, in reset
    agent_xmls = self._setup_agent_xmls(ep_uid)
  File "/home/xxx/.local/lib/python3.8/site-packages/minerl/env/_multiagent.py", line 498, in _setup_agent_xmls
    xml_in = self.task.to_xml()
  File "/home/xxx/.local/lib/python3.8/site-packages/minerl/herobraine/env_spec.py", line 269, in to_xml
    xml = template.render(var_dict)
  File "/home/xxx/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/xxx/.local/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 77, in top-level template code
  File "/home/xxx/.local/lib/python3.8/site-packages/minerl/herobraine/env_spec.py", line 291, in get_consolidated_xml
    handler_xml_strs = [handler.xml() for handler in handlers]
  File "/home/xxx/.local/lib/python3.8/site-packages/minerl/herobraine/env_spec.py", line 291, in <listcomp>
    handler_xml_strs = [handler.xml() for handler in handlers]
  File "/home/xxx/.local/lib/python3.8/site-packages/minerl/herobraine/hero/handler.py", line 53, in xml
    template = env.from_string(self.xml_template())
  File "/home/xxx/.local/lib/python3.8/site-packages/minerl/herobraine/hero/handler.py", line 37, in xml_template
    raise NotImplementedError()
NotImplementedError

**Comment by Miffyli** [comment]
Try installing minerl with `pip install git+https://github.com/minerllabs/minerl.git` and try the code after that :). `pip install --upgrade minerl` should also work now, I think.

**Comment by mwang808** [comment]
Tried "pip install --upgrade minerl" and it works. Thanks.

**Comment by mchoccie** [comment]
I'm getting this error again does anyone have any idea?
