### ISSUE TITLE
I get an error when I try to import minerl

### ISSUE THREAD

**Issue by panghuuuuuu** [minerllabs/minerl#620]
When I run the following code, I get this error:
import gym
import minerl
env = gym.make('MineRLObtainDiamond-v0')

Traceback (most recent call last):
  File "G:/Minerl_Learning/main.py", line 1, in <module>
    import minerl
  File "F:\Anaconda\envs\minerl_learning\lib\site-packages\minerl\__init__.py", line 6, in <module>
    import minerl.herobraine.envs
  File "F:\Anaconda\envs\minerl_learning\lib\site-packages\minerl\herobraine\envs.py", line 16, in <module>
    MINERL_TREECHOP_V0 = Treechop()
  File "F:\Anaconda\envs\minerl_learning\lib\site-packages\minerl\herobraine\env_specs\treechop_specs.py", line 35, in __init__
    max_episode_steps=8000, reward_threshold=64.0)
  File "F:\Anaconda\envs\minerl_learning\lib\site-packages\minerl\herobraine\env_specs\simple_env_spec.py", line 30, in __init__
    super().__init__(name, xml, *args, **kwargs)
  File "F:\Anaconda\envs\minerl_learning\lib\site-packages\minerl\herobraine\env_spec.py", line 24, in __init__
    self.actionables = self.create_actionables()
  File "F:\Anaconda\envs\minerl_learning\lib\site-packages\minerl\herobraine\env_specs\simple_env_spec.py", line 43, in create_actionables
    handlers.KeyboardAction(k, v) for k,v in INVERSE_KEYMAP.items()
  File "F:\Anaconda\envs\minerl_learning\lib\site-packages\minerl\herobraine\env_specs\simple_env_spec.py", line 44, in <listcomp>
    if k in SimpleEnvSpec.STANDARD_KEYBOARD_ACTIONS
  File "F:\Anaconda\envs\minerl_learning\lib\site-packages\minerl\herobraine\hero\handlers\actionable.py", line 364, in __init__
    super().__init__(command, spaces.Discrete(len(keys) + 1))
  File "F:\Anaconda\envs\minerl_learning\lib\site-packages\minerl\herobraine\hero\spaces.py", line 202, in __init__
    self.shape = ()
AttributeError: can't set attribute

Can someone tell me why I get an error?
py3.7 + minerl==0.3.7 + windows11

**Comment by Miffyli** [comment]
You have too new gym installed. Run `pip install gym==0.19` and try again.

**Comment by panghuuuuuu** [comment]
It works as expected! Thanks for your help!
