### ISSUE TITLE
Cannot download minerl

### ISSUE THREAD

**Issue by 452Foxy** [minerllabs/minerl#631]
It's probably cause I'm dumb, but I don't know how to fix this error.
Please help ;-;
```
Error:

      Note: Some input files use or override a deprecated API.
      Note: Recompile with -Xlint:deprecation for details.
      Note: Some input files use unchecked or unsafe operations.
      Note: Recompile with -Xlint:unchecked for details.
      3 warnings

      > Task :processResources
      > Task :classes
      > Task :extractNatives
      > Task :getAssetIndex

      > Task :getAssets
      Current status: 46/1196   3%
      Current status: 252/1196   21%
      Current status: 973/1196   81%

      java.io.FileNotFoundException: C:\Users\Ruben\AppData\Local\Temp\pip-insta
ll-4zgjsmu_\minerl_c7c7e67d324a44a6b8b1914a09887d35\build\lib\minerl\Malmo\Minec
raft\run\gradle\caches\minecraft\assets\objects\e9\e9833a1512b57bcf88ac4fdcc8df4
e5a7e9d701d (Cannot access the file. The file is being used by another process.)
          at java.io.FileInputStream.open0(Native Method)
          at java.io.FileInputStream.open(FileInputStream.java:195)
          at java.io.FileInputStream.<init>(FileInputStream.java:138)
          at net.minecraftforge.gradle.common.Constants.hash(Constants.java:387)

          at net.minecraftforge.gradle.tasks.DownloadAssetsTask.checkFileCorrupt
(DownloadAssetsTask.java:144)
          at net.minecraftforge.gradle.tasks.DownloadAssetsTask.access$100(Downl
oadAssetsTask.java:50)
          at net.minecraftforge.gradle.tasks.DownloadAssetsTask$GetAssetTask.cal
l(DownloadAssetsTask.java:175)
          at net.minecraftforge.gradle.tasks.DownloadAssetsTask$GetAssetTask.cal
l(DownloadAssetsTask.java:150)
          at java.util.concurrent.FutureTask.run(FutureTask.java:266)
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecuto
r.java:1149)
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecut
or.java:624)
          at java.lang.Thread.run(Thread.java:750)

      > Task :getAssets
      Current status: 1107/1196   92%

      > Task :makeStart
      > Task :shadowJar

      Deprecated Gradle features were used in this build, making it incompatible
 with Gradle 5.0.
      Use '--warning-mode all' to show the individual deprecation warnings.
      See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#s
ec:command_line_warnings

      BUILD SUCCESSFUL in 4m 33s
      26 actionable tasks: 26 executed
      error: [WinError 3] Cannot find specified path: 'C:\\User
s\\Ruben\\AppData\\Local\\Temp\\pip-install-4zgjsmu_\\minerl_c7c7e67d324a44a6b8b
1914a09887d35\\build\\lib\\minerl\\Malmo\\Minecraft\\run\\gradle\\caches\\4.10.2
\\scripts\\8ep3o1leudvwqy2gc96ddrjkw\\cp_proj\\cp_proj70b1361a260e0ceb212a59c45f
680ebd\\cp_proj70b1361a260e0ceb212a59c45f680ebd.lock'
      building Minecraft from  C:\Users\Ruben\AppData\Local\Temp\pip-install-4zg
jsmu_\minerl_c7c7e67d324a44a6b8b1914a09887d35\minerl\Malmo, build dir: build\lib
\minerl\Malmo
      copying source dir
      CALLING SETUP.
      Deleting fileContent.lock
      Deleting fileHashes.lock
      Deleting javaCompile.lock
      Deleting taskHistory.lock
      Deleting buildOutputCleanup.lock
      Deleting fileContent.lock
      Deleting fileHashes.lock
      Deleting javaCompile.lock
      Deleting md-rule.lock
      Deleting md-supplier.lock
      Deleting cp_proj70b1361a260e0ceb212a59c45f680ebd.lock
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem wit
h pip.
  ERROR: Failed building wheel for minerl
  Running setup.py clean for minerl
  error: subprocess-exited-with-error

  × python setup.py clean did not run successfully.
  │ exit code: 1
  ?─> [3 lines of output]
      running clean
      removing 'build\lib' (and everything under it)
      error: [WinError 3] Cannot find specified path: 'build\\l
ib\\minerl\\Malmo\\Minecraft\\run\\gradle\\caches\\modules-2\\files-2.1\\org.apa
che.httpcomponents\\httpcomponents-core\\4.3.2\\35bff8146ac0477f3d3e4d85ef93341e
5d3ecdb1'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem wit
h pip.
  ERROR: Failed cleaning build dir for minerl
Failed to build minerl
Installing collected packages: minerl
  Running setup.py install for minerl ... error
  error: subprocess-exited-with-error

  × Running setup.py install for minerl did not run successfully.
  │ exit code: 1
  ?─> [26 lines of output]
      running install
      running build
      running build_py
      running egg_info
      writing minerl.egg-info\PKG-INFO
      writing dependency_links to minerl.egg-info\dependency_links.txt
      writing requirements to minerl.egg-info\requires.txt
      writing top-level names to minerl.egg-info\top_level.txt
      reading manifest file 'minerl.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      no previously-included directories found matching 'minerl\Malmo\Minecraft\
.gradle'
      no previously-included directories found matching 'minerl\Malmo\Minecraft\
bin'
      no previously-included directories found matching 'minerl\Malmo\Minecraft\
build'
      no previously-included directories found matching 'minerl\Malmo\Minecraft\
run\gradle'
      no previously-included directories found matching 'minerl\Malmo\Minecraft\
.minecraft'
      no previously-included directories found matching 'minerl\Malmo\Minecraft\
.minecraftserver'
      no previously-included directories found matching 'minerl\Malmo\Minecraft\
run\saves'
      warning: no previously-included files matching '*.lock' found anywhere in
distribution
      warning: no previously-included files matching '*fuse_hidden*' found anywh
ere in distribution
      adding license file 'LICENSE'
      writing manifest file 'minerl.egg-info\SOURCES.txt'
      running build_ext
      running install_lib
      error: [WinError 3] Cannot find specified path: 'build\\l
ib\\minerl\\Malmo\\Minecraft\\build\\classes\\java\\main\\com\\microsoft\\Malmo\
\MissionHandlers\\CommandForWheeledRobotNavigationImplementation$ResetPitchAndYa
wEvent.class'
      building Minecraft from  C:\Users\Ruben\AppData\Local\Temp\pip-install-4zg
jsmu_\minerl_c7c7e67d324a44a6b8b1914a09887d35\minerl\Malmo, build dir: build\lib
\minerl\Malmo
      copying source dir
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem wit
h pip.
error: legacy-install-failure

× Encountered error while trying to install package.
?─> minerl

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
Traceback (most recent call last):
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\runpy.py", li
ne 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\runpy.py", li
ne 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\Scripts\pip3.exe\
__main__.py", line 7, in <module>
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\site-packages
\pip\_internal\cli\main.py", line 70, in main
    return command.main(cmd_args)
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\site-packages
\pip\_internal\cli\base_command.py", line 100, in main
    with self.main_context():
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\contextlib.py
", line 142, in __exit__
    next(self.gen)
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\site-packages
\pip\_internal\cli\command_context.py", line 19, in main_context
    with self._main_context:
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\contextlib.py
", line 576, in __exit__
    raise exc_details[1]
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\contextlib.py
", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\site-packages
\pip\_internal\utils\temp_dir.py", line 70, in tempdir_registry
    yield _tempdir_registry
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\contextlib.py
", line 561, in __exit__
    if cb(*exc_details):
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\contextlib.py
", line 142, in __exit__
    next(self.gen)
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\site-packages
\pip\_internal\utils\temp_dir.py", line 31, in global_tempdir_manager
    with ExitStack() as stack:
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\contextlib.py
", line 576, in __exit__
    raise exc_details[1]
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\contextlib.py
", line 561, in __exit__
    if cb(*exc_details):
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\site-packages
\pip\_internal\utils\temp_dir.py", line 156, in __exit__
    self.cleanup()
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\site-packages
\pip\_internal\utils\temp_dir.py", line 173, in cleanup
    rmtree(self._path)
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\site-packages
\pip\_vendor\tenacity\__init__.py", line 326, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\site-packages
\pip\_vendor\tenacity\__init__.py", line 406, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\site-packages
\pip\_vendor\tenacity\__init__.py", line 362, in iter
    raise retry_exc.reraise()
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\site-packages
\pip\_vendor\tenacity\__init__.py", line 195, in reraise
    raise self.last_attempt.result()
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\concurrent\fu
tures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\concurrent\fu
tures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\site-packages
\pip\_vendor\tenacity\__init__.py", line 409, in __call__
    result = fn(*args, **kwargs)
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\site-packages
\pip\_internal\utils\misc.py", line 124, in rmtree
    shutil.rmtree(dir, ignore_errors=ignore_errors, onerror=rmtree_errorhandler)

  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\shutil.py", l
ine 747, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\shutil.py", l
ine 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\shutil.py", l
ine 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\shutil.py", l
ine 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 11 more times]
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\shutil.py", l
ine 621, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\Ruben\AppData\Local\Programs\Python\Python310\lib\shutil.py", l
ine 619, in _rmtree_unsafe
    os.rmdir(path)
OSError: [WinError 145] The directory is not empty: 'C:\\Users\\Ruben\\AppData\\Lo
cal\\Temp\\pip-install-4zgjsmu_\\minerl_c7c7e67d324a44a6b8b1914a09887d35\\build\
\lib\\minerl\\Malmo\\Minecraft\\build\\classes\\java\\main\\com\\microsoft\\Malm
o\\MissionHandlers'
```

**Comment by Miffyli** [comment]
See the first tip here regarding MAX_PATH: https://minerl.readthedocs.io/en/latest/notes/windows.html

**Comment by 452Foxy** [comment]
Thanks! It fixed the issue.
