### ISSUE TITLE
[v1.0.0] There is an environment reset error

### ISSUE THREAD

**Issue by neverparadise** [minerllabs/minerl#637]
Hi. I installed minerl v1.0.0. I tried to run the example code and meet some errors.
Here are python codes and the error logs. How can I solve it?

```
import gym
import minerl
import logging
import coloredlogs

coloredlogs.install(logging.DEBUG)

env = gym.make("MineRLBasaltBuildVillageHouse-v0")
obs = env.reset()
```

# [1] python error logs

/root/anaconda3/envs/minerl1/lib/python3.7/site-packages/minerl/env/../MCP-Reborn
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[04:18:12] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[04:18:13] [Render thread/ERROR]: Failed to verify authentication!
[04:18:13] [Render thread/INFO]: Setting user: Player495
[04:18:13] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT
---- Minecraft Crash Report ----
// You're mean.

Time: 6/24/22 4:18 AM
Description: Initializing game

java.lang.IllegalStateException: Failed to initialize GLFW, errors: GLFW error during init: [0x10008]140294784392896
	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:80)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:586)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:406)
	at net.minecraft.client.main.Main.main(Main.java:154)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:80)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:586)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:406)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:154)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.4.0-120-generic
	Java Version: 1.8.0_312, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 1058162376 bytes (1009 MB) / 2281701376 bytes (2176 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 96
	JVM Flags: 1 total; -Xmx4G
	Launched Version: ~~NULL~~
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /root/anaconda3/envs/minerl1/lib/python3.7/site-packages/minerl/MCP-Reborn/./crash-reports/crash-2022-06-24_04.18.13-client.txt

Minecraft process finished unexpectedly. There was an error with Malmo.
  File "/root/env_test.py", line 9, in <module>
    obs = env.reset()

# [2] colored logs

2022-06-24 04:18:00 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] INFO Starting Minecraft process: ['/root/anaconda3/envs/minerl1/lib/python3.7/site-packages/minerl/env/../MCP-Reborn/launchClient.sh', '-port', '9362', '-env', '-runDir', '/root/anaconda3/envs/minerl1/lib/python3.7/site-packages/minerl/env/../MCP-Reborn/run']
2022-06-24 04:18:00 9bdba77f741f process_watcher[10815] INFO Launching process watcher daemonizer.
/root/anaconda3/envs/minerl1/lib/python3.7/runpy.py:125: RuntimeWarning: 'minerl.utils.process_watcher' found in sys.modules after import of package 'minerl.utils', but prior to execution of 'minerl.utils.process_watcher'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2022-06-24 04:18:01 9bdba77f741f process_watcher[10815] INFO Process watcher daemonizer launched successfully.
2022-06-24 04:18:01 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG /root/anaconda3/envs/minerl1/lib/python3.7/site-packages/minerl/env/../MCP-Reborn
2022-06-24 04:18:10 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2022-06-24 04:18:10 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-06-24 04:18:10 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-06-24 04:18:12 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG [04:18:12] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR [04:18:13] [Render thread/ERROR]: Failed to verify authentication!
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG [04:18:13] [Render thread/INFO]: Setting user: Player495
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG [04:18:13] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG ---- Minecraft Crash Report ----
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG // You're mean.
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG 
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG Time: 6/24/22 4:18 AM
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG Description: Initializing game
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG 
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR java.lang.IllegalStateException: Failed to initialize GLFW, errors: GLFW error during init: [0x10008]140294784392896
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG  at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:80)
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG  at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:586)
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG  at net.minecraft.client.Minecraft.<init>(Minecraft.java:406)
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG  at net.minecraft.client.main.Main.main(Main.java:154)
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG 
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG 
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG A detailed walkthrough of the error, its code path and all known details is as follows:
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG ---------------------------------------------------------------------------------------
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG 
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG -- Head --
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG Thread: Render thread
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG Stacktrace:
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG  at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:80)
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG  at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:586)
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG  at net.minecraft.client.Minecraft.<init>(Minecraft.java:406)
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG 
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG -- Initialization --
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG Details:
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG Stacktrace:
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG  at net.minecraft.client.main.Main.main(Main.java:154)
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG 
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG -- System Details --
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG Details:
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG  Minecraft Version: 1.16.5
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG  Minecraft Version ID: 1.16.5
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG  Operating System: Linux (amd64) version 5.4.0-120-generic
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG  Java Version: 1.8.0_312, Private Build
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG  Memory: 1058162376 bytes (1009 MB) / 2281701376 bytes (2176 MB) up to 3817865216 bytes (3641 MB)
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG  CPUs: 96
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG  JVM Flags: 1 total; -Xmx4G
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG  Launched Version: ~~NULL~~
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG  Backend library: LWJGL version 3.2.2 SNAPSHOT
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG  Backend API: NO CONTEXT
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG  GL Caps: 
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG  Using VBOs: Yes
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG  Is Modded: Very likely; Jar signature invalidated
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG  Type: Client (map_client.txt)
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG  CPU: <unknown>
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] DEBUG #@!@# Game crashed! Crash report saved to: #@!@# /root/anaconda3/envs/minerl1/lib/python3.7/site-packages/minerl/MCP-Reborn/./crash-reports/crash-2022-06-24_04.18.13-client.txt
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR /root/anaconda3/envs/minerl1/lib/python3.7/site-packages/minerl/env/../MCP-Reborn
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR [04:18:12] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR [04:18:13] [Render thread/ERROR]: Failed to verify authentication!
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR [04:18:13] [Render thread/INFO]: Setting user: Player495
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR [04:18:13] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR ---- Minecraft Crash Report ----
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR // You're mean.
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR 
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR Time: 6/24/22 4:18 AM
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR Description: Initializing game
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR 
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR java.lang.IllegalStateException: Failed to initialize GLFW, errors: GLFW error during init: [0x10008]140294784392896
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR  at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:80)
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR  at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:586)
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR  at net.minecraft.client.Minecraft.<init>(Minecraft.java:406)
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR  at net.minecraft.client.main.Main.main(Main.java:154)
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR 
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR 
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR A detailed walkthrough of the error, its code path and all known details is as follows:
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR ---------------------------------------------------------------------------------------
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR 
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR -- Head --
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR Thread: Render thread
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR Stacktrace:
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR  at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:80)
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR  at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:586)
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR  at net.minecraft.client.Minecraft.<init>(Minecraft.java:406)
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR 
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR -- Initialization --
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR Details:
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR Stacktrace:
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR  at net.minecraft.client.main.Main.main(Main.java:154)
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR 
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR -- System Details --
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR Details:
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR  Minecraft Version: 1.16.5
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR  Minecraft Version ID: 1.16.5
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR  Operating System: Linux (amd64) version 5.4.0-120-generic
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR  Java Version: 1.8.0_312, Private Build
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR  Memory: 1058162376 bytes (1009 MB) / 2281701376 bytes (2176 MB) up to 3817865216 bytes (3641 MB)
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR  CPUs: 96
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR  JVM Flags: 1 total; -Xmx4G
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR  Launched Version: ~~NULL~~
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR  Backend library: LWJGL version 3.2.2 SNAPSHOT
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR  Backend API: NO CONTEXT
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR  GL Caps: 
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR  Using VBOs: Yes
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR  Is Modded: Very likely; Jar signature invalidated
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR  Type: Client (map_client.txt)
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR  CPU: <unknown>
2022-06-24 04:18:13 9bdba77f741f minerl.env.malmo.instance.800d7e[10815] ERROR #@!@# Game crashed! Crash report saved to: #@!@# /root/anaconda3/envs/minerl1/lib/python3.7/site-packages/minerl/MCP-Reborn/./crash-reports/crash-2022-06-24_04.18.13-client.txt

# [3] Minecraft Crash Report

---- Minecraft Crash Report ----
// My bad.

Time: 6/24/22 4:18 AM
Description: Initializing game

java.lang.IllegalStateException: Failed to initialize GLFW, errors: GLFW error during init: [0x10008]140294784392896
        at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:80)
        at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:586)
        at net.minecraft.client.Minecraft.<init>(Minecraft.java:406)
        at net.minecraft.client.main.Main.main(Main.java:154)

A detailed walkthrough of the error, its code path and all known details is as follows: 
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
        at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:80)
        at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:586)
        at net.minecraft.client.Minecraft.<init>(Minecraft.java:406)

-- Initialization --
Details:
Stacktrace:
        at net.minecraft.client.main.Main.main(Main.java:154)

-- System Details --
Details:
        Minecraft Version: 1.16.5
        Minecraft Version ID: 1.16.5
        Operating System: Linux (amd64) version 5.4.0-120-generic
        Java Version: 1.8.0_312, Private Build
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
        Memory: 1058162376 bytes (1009 MB) / 2281701376 bytes (2176 MB) up to 3817865216 bytes (3641 MB)
        CPUs: 96
        JVM Flags: 1 total; -Xmx4G
        Launched Version: ~~NULL~~
        Backend library: LWJGL version 3.2.2 SNAPSHOT
        Backend API: NO CONTEXT
        GL Caps:
        Using VBOs: Yes
        Is Modded: Very likely; Jar signature invalidated
        Type: Client (map_client.txt)
        CPU: <unknown>
~

**Comment by Miffyli** [comment]
Hey, did you try using `xvfb`?  I.e. run your code with `xvfb-run -a python [path to your code]`. On monitor-less ("headless") machines or on WSL this is required to run the code.

**Comment by neverparadise** [comment]
Thank you!!! It works well

**Comment by neverparadise** [comment]
Thank you!!! It works well
