### ISSUE TITLE
Upgrade version

### ISSUE THREAD

**Issue by feyzazeynep** [minerllabs/minerl#651]
I want to upgrade from version 0.4.4 to version 1.0.0. pip install --upgrade minerall doesn't work. I get error with pip install git+https://github.com/minellabs/minerl@v1.0.0 --user. how should i go about it?

**Comment by feyzazeynep** [comment]
pip install -U git+https://github.com/minerllabs/minerl@v1.0.0
WARNING: Ignoring invalid distribution -sutil (c:\users\dell\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cipy (c:\users\dell\anaconda3\lib\site-packages)
Collecting git+https://github.com/minerllabs/minerl@v1.0.0
  Cloning https://github.com/minerllabs/minerl (to revision v1.0.0) to c:\users\dell\appdata\local\temp\pip-req-build-bhforux5
  Running command git clone --filter=blob:none --quiet https://github.com/minerllabs/minerl 'C:\Users\DELL\AppData\Local\Temp\pip-req-build-bhforux5'
  Running command git checkout -b v1.0.0 --track origin/v1.0.0
  branch 'v1.0.0' set up to track 'origin/v1.0.0'.
  Switched to a new branch 'v1.0.0'
  Resolved https://github.com/minerllabs/minerl to commit cc8bbbbcf106f3b89955f2d80cd5ef0c8f43a5c0
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Cloning into 'MCP-Reborn'...
      Note: switching to '1.16.5-20210115'.

      You are in 'detached HEAD' state. You can look around, make experimental
      changes and commit them, and you can discard any commits you make in this
      state without impacting any branches by switching back to a branch.

      If you want to create a new branch to retain commits you create, you may
      do so (now or later) by using -c with the switch command. Example:

        git switch -c <new-branch-name>

      Or undo this operation with:

        git switch -

      Turn off this advice by setting config variable advice.detachedHead to false

      HEAD is now at 1e71be5 Update README.md
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\DELL\AppData\Local\Temp\pip-req-build-bhforux5\setup.py", line 215, in <module>
          prep_mcp()
        File "C:\Users\DELL\AppData\Local\Temp\pip-req-build-bhforux5\setup.py", line 136, in prep_mcp
          setup_output = subprocess.check_output(['bash.exe', 'setup_mcp.sh']).decode()
      UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdd in position 586: invalid continuation byte
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: Ignoring invalid distribution -sutil (c:\users\dell\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cipy (c:\users\dell\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -sutil (c:\users\dell\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cipy (c:\users\dell\anaconda3\lib\site-packages)

**Comment by Miffyli** [comment]
Try installing with `pip install git+https://github.com/minerllabs/minerl`. I have added a fix that should help out, although does not explain how there were such invalid bytes in the mix.
