### ISSUE TITLE
Installtion Error

### ISSUE THREAD

**Issue by NEE2641** [minerllabs/minerl#669]
Cloning https://github.com/minerllabs/minerl to c:\users\zheng lihao\appdata\local\temp\pip-req-build-tnwxmboh
  Running command git clone --filter=blob:none --quiet https://github.com/minerllabs/minerl 'C:\Users\Zheng Lihao\AppData\Local\Temp\pip-req-build-tnwxmboh'
  Resolved https://github.com/minerllabs/minerl to commit 03510486957633676d269bf83115a84499ef7f47
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      setup_mcp.sh: line 4: cd: too many arguments
      Cloning into 'MCP-Reborn'...
      Note: switching to '1.16.5-20210115'.

      You are in 'detached HEAD' state. You can look around, make experimental
      changes and commit them, and you can discard any commits you make in this
      state without impacting any branches by switching back to a branch.

      If you want to create a new branch to retain commits you create, you may
      do so (now or later) by using -c with the switch command. Example:

        git switch -c <new-branch-name>

      Or undo this operation with:

        git switch -

      Turn off this advice by setting config variable advice.detachedHead to false

      HEAD is now at 1e71be5 Update README.md
      patch_mcp.sh: line 5: cd: too many arguments
      patch: **** Can't open patch file /c/Users/Zheng : No such file or directory
      cp: target './src/main/resources' is not a directory
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Zheng Lihao\AppData\Local\Temp\pip-req-build-tnwxmboh\setup.py", line 214, in <module>
          prep_mcp()
        File "C:\Users\Zheng Lihao\AppData\Local\Temp\pip-req-build-tnwxmboh\setup.py", line 184, in prep_mcp
          os.chdir(workdir)
      FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'C:\\Users\\Zheng Lihao\\AppData\\Local\\Temp\\pip-req-build-tnwxmboh\\minerl\\MCP-Reborn'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Miffyli** [comment]
Hmm this probably is caused by the whitespace in your username for the machine. You can probably fix this by cloning the repository to your machine and modifying [this](https://github.com/minerllabs/minerl/blob/03510486957633676d269bf83115a84499ef7f47/scripts/patch_mcp.sh#L5) line to `cd "${DIR}/../minerl/MCP-Reborn"` (and same might need to be done for the other ".sh" scripts). We can fix this in the main repo if you can test this to work correctly.
