### ISSUE TITLE
Install Failed

### ISSUE THREAD

**Issue by Game5048-bilibili** [minerllabs/minerl#670]
D:\个人项目\minerl-1.0>python setup.py
setup_mcp.sh: line 6: git: command not found
setup_mcp.sh: line 7: cd: MCP-Reborn: No such file or directory
setup_mcp.sh: line 8: git: command not found
setup_mcp.sh: line 10: ./gradlew: No such file or directory
patch_mcp.sh: line 5: cd: /mnt/d/个人项目/minerl-1.0/scripts/../minerl/MCP-Reborn: No such file or directory
patch_mcp.sh: line 6: patch: command not found
cp: cannot create directory './src/main/resources': No such file or directory
Traceback (most recent call last):
  File "setup.py", line 214, in <module>
    prep_mcp()
  File "setup.py", line 184, in prep_mcp
    os.chdir(workdir)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'D:\\个人项目\\minerl-1.0\\minerl\\MCP-Reborn'

D:\个人项目\minerl-1.0>

Could anyone please tell me how I can get the MCP-Reborn ?

**Comment by Miffyli** [comment]
As per installation instructions, you should first install Windows WSL (most tested option) before proceeding. The code requires linux-tools (e.g., bash) to be installed, which WSL will provide. You could also try installing things like git bash with mingw,  but those are trickier to install, and WSL has been the most successful option so far.
