### ISSUE TITLE
run example error

### ISSUE THREAD

**Issue by lmx760581375** [minerllabs/minerl#678]
When I went to the trouble of installing it, I found a bug that I couldn't fix(the code is your example):

Traceback (most recent call last):
  File "C:/Users/mingxiaoli/PycharmProjects/rl_v1/main.py", line 9, in <module>
    env = gym.make("MineRLNavigateDense-v0")
  File "C:\Users\mingxiaoli\AppData\Roaming\Python\Python36\site-packages\gym\envs\registration.py", line 184, in make
    return registry.make(id, **kwargs)
  File "C:\Users\mingxiaoli\AppData\Roaming\Python\Python36\site-packages\gym\envs\registration.py", line 106, in make
    env = spec.make(**kwargs)
  File "C:\Users\mingxiaoli\AppData\Roaming\Python\Python36\site-packages\gym\envs\registration.py", line 79, in make
    spec = copy.deepcopy(self)
  File "C:\Program Files\Python36\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Program Files\Python36\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Program Files\Python36\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "C:\Program Files\Python36\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Program Files\Python36\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Program Files\Python36\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Program Files\Python36\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Program Files\Python36\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Program Files\Python36\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "C:\Program Files\Python36\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Program Files\Python36\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Program Files\Python36\lib\copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.RLock objects

Process finished with exit code 1

**Comment by Miffyli** [comment]
Hey. If you installed MineRL from the repository, it does not have the "MineRLNavigate-v0" environment. If you installed it from pypi with `pip install minerl==0.4.4` (or just `pip install minerl`), then something might have gone off in your installation. It also seems like something might be off in your gym installation (e.g., try testing out other gym installations and see gym docs).
