### ISSUE TITLE
Import minerl fails due to expired deprecation of numpy bool (np.bool)

### ISSUE THREAD

**Issue by chrissarmstrong** [minerllabs/minerl#686]
I recently created a new conda environment and installed minerl per the instructions here: https://minerl.readthedocs.io/en/latest/tutorials/index.html

When I attempt to import minerl, however, I get

> AttributeError: module 'numpy' has no attribute 'bool'

I believe this is because of a recently expired deprecation of numpy bool in numpy 1.24: https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations

numpy.version.version is 1.24.0

Full stack trace:

> /bigdrive/anaconda3/envs/minerl/lib/python3.9/site-packages/minerl/herobraine/hero/handlers/agent/observations/lifestats.py:62: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
>   space=spaces.Box(low=False, high=True, shape=(), dtype=np.bool),
> Traceback (most recent call last):
>   File "/home/csa/minerl-playing/./random-agent.py", line 4, in <module>
>     import minerl
>   File "/bigdrive/anaconda3/envs/minerl/lib/python3.9/site-packages/minerl/__init__.py", line 6, in <module>
>     import minerl.herobraine.envs
>   File "/bigdrive/anaconda3/envs/minerl/lib/python3.9/site-packages/minerl/herobraine/envs.py", line 30, in <module>
>     MINERL_HUMAN_SURVIVAL_V0 = HumanSurvival()
>   File "/bigdrive/anaconda3/envs/minerl/lib/python3.9/site-packages/minerl/herobraine/env_specs/human_survival_specs.py", line 17, in __init__
>     super().__init__(
>   File "/bigdrive/anaconda3/envs/minerl/lib/python3.9/site-packages/minerl/herobraine/env_specs/human_controls.py", line 54, in __init__
>     super().__init__(name, *args, **kwargs)
>   File "/bigdrive/anaconda3/envs/minerl/lib/python3.9/site-packages/minerl/herobraine/env_spec.py", line 38, in __init__
>     self.reset()
>   File "/bigdrive/anaconda3/envs/minerl/lib/python3.9/site-packages/minerl/herobraine/env_spec.py", line 43, in reset
>     self.observables = self.create_observables()
>   File "/bigdrive/anaconda3/envs/minerl/lib/python3.9/site-packages/minerl/herobraine/env_specs/human_survival_specs.py", line 31, in create_observables
>     handlers.ObservationFromLifeStats(),
>   File "/bigdrive/anaconda3/envs/minerl/lib/python3.9/site-packages/minerl/herobraine/hero/handlers/agent/observations/lifestats.py", line 22, in __init__
>     _IsAliveObservation(),
>   File "/bigdrive/anaconda3/envs/minerl/lib/python3.9/site-packages/minerl/herobraine/hero/handlers/agent/observations/lifestats.py", line 62, in __init__
>     space=spaces.Box(low=False, high=True, shape=(), dtype=np.bool),
>   File "/bigdrive/anaconda3/envs/minerl/lib/python3.9/site-packages/numpy/__init__.py", line 284, in __getattr__
>     raise AttributeError("module {!r} has no attribute "
> AttributeError: module 'numpy' has no attribute 'bool'

It is possibly worth noting that 10 days ago I'd installed minerl in the same way and used it with no issues (and subsequently had to uninstall / reinstall conda altogether due to unrelated problems).

**Comment by Miffyli** [comment]
Hey! Thank you for reporting this (and sorry for the delayed answer!). As a quick fix I will set a upper cap for Numpy version, but ultimately, this should be fixed in the code. Do I understand right that `np.bool8` should be used instead of `np.bool` in future versions?

If anybody is reading this, I would very happily accept a PR to fix this issue if somebody finds the time to work on this :)

**Comment by chrissarmstrong** [comment]
Hi @Miffyli, thanks for your help! Seems like an upper cap on Numpy version will work fine as a short-term fix.

Re longer-term fix: my read of [this page](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations) (see the first entry in the top table) is that `numpy.bool` was just an alias to `bool`, and that we should now use the latter.
