### ISSUE TITLE
Error when running minerl test

### ISSUE THREAD

**Issue by turtlemaster890** [minerllabs/minerl#690]
PS C:\Users\###\github\minerl> python minerl.py
C:\Users\###\github\minerl\minerl\herobraine\hero\handlers\agent\observations\lifestats.py:62: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
  space=spaces.Box(low=False, high=True, shape=(), dtype=np.bool),
Traceback (most recent call last):
  File "C:\Users\###\github\minerl\minerl.py", line 2, in <module>
    import minerl
  File "C:\Users\###\github\minerl\minerl\__init__.py", line 6, in <module>
    import minerl.herobraine.envs
  File "C:\Users\###\github\minerl\minerl\herobraine\envs.py", line 30, in <module>
    MINERL_HUMAN_SURVIVAL_V0 = HumanSurvival()
  File "C:\Users\###\github\minerl\minerl\herobraine\env_specs\human_survival_specs.py", line 17, in __init__
    super().__init__(
  File "C:\Users\###\github\minerl\minerl\herobraine\env_specs\human_controls.py", line 54, in __init__
    super().__init__(name, *args, **kwargs)
  File "C:\Users\###\github\minerl\minerl\herobraine\env_spec.py", line 38, in __init__
    self.reset()
  File "C:\Users\###\github\minerl\minerl\herobraine\env_spec.py", line 43, in reset
    self.observables = self.create_observables()
  File "C:\Users\###\github\minerl\minerl\herobraine\env_specs\human_survival_specs.py", line 31, in create_observables
    handlers.ObservationFromLifeStats(),
  File "C:\Users\###\github\minerl\minerl\herobraine\hero\handlers\agent\observations\lifestats.py", line 22, in __init__
    _IsAliveObservation(),
  File "C:\Users\###\github\minerl\minerl\herobraine\hero\handlers\agent\observations\lifestats.py", line 62, in __init__
    space=spaces.Box(low=False, high=True, shape=(), dtype=np.bool),
  File "C:\Users\###\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool'. Did you mean: 'bool_'?

That's the error, I get it when I try running the program.

**Comment by Miffyli** [comment]
Try `pip install numpy<1.24` . Newest numpy is broken in MineRL (should fix that one day...)
