### ISSUE TITLE
cant import minerl

### ISSUE THREAD

**Issue by lycaneo** [minerllabs/minerl#691]
Hi, i just installed minerl using WSL 2 and i got an error while following the "hello world" tutorial
`$ python3 minerl.py
Traceback (most recent call last):
  File "/home/lycaneo/.local/lib/python3.10/site-packages/gym/envs/registration.py", line 150, in spec
    return self.env_specs[id]
KeyError: 'MineRLBasaltFindCave-v0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/apoca/desktop/minerl.py", line 2, in <module>
    import minerl
  File "/mnt/c/Users/apoca/desktop/minerl.py", line 4, in <module>
    env = gym.make("MineRLBasaltFindCave-v0")
  File "/home/lycaneo/.local/lib/python3.10/site-packages/gym/envs/registration.py", line 184, in make
    return registry.make(id, **kwargs)
  File "/home/lycaneo/.local/lib/python3.10/site-packages/gym/envs/registration.py", line 105, in make
    spec = self.spec(path)
  File "/home/lycaneo/.local/lib/python3.10/site-packages/gym/envs/registration.py", line 167, in spec
    raise error.UnregisteredEnv("No registered env with id: {}".format(id))
gym.error.UnregisteredEnv: No registered env with id: MineRLBasaltFindCave-v0`

i understand it as "can't import minerl"

**Comment by Miffyli** [comment]
Hey. Make sure the minerl installation succeeded correctly (should say at the end that it installed MineRL). Also make sure you are using the same Python environment to where MineRL was installed.

**Comment by lycaneo** [comment]
the installation seem to have succeeded in the python environment: all "Requirement already satisfied:" when trying to reinstall and present when using pip freeze; is there maybe an upper compatible version of python? (i'm on 3.10.6)

**Comment by Miffyli** [comment]
Ah I think I see the problem; your code file is named "minerl.py", and if you do `import minerl`, it might be trying to import from this file. Try renaming your file(s) and making sure there is no file or directory named "minerl" in the directory you work in.
