### ISSUE TITLE
Installing minerl via pip fails during gradle build

### ISSUE THREAD

**Issue by jhsul** [minerllabs/minerl#693]
I am trying to install minerl via pip (conda environment). My java environment is zulu 8, but I also tried this with temurin 8 and got the same error. This is on mac silicon.

I included the relevant part of the error below. It seems like within Malmo, there a missing file, which causes the gradle build to fail?

```
...
Set executable permissions for: /private/var/folders/xh/kd_p58q54sg_1wrqsphxn26h0000gn/T/pip-install-mg6w5ojz/minerl_0aaaa2605f5348bea30b9b5ab04dce19/build/lib.macosx-11.1-arm64-cpython-310/minerl/Malmo/Minecraft/run/gradle/wrapper/dists/gradle-4.10.2-all/9fahxiiecdb76a5g3aw9oi8rv/gradle-4.10.2/bin/gradle
      
      Welcome to Gradle 4.10.2!
      
      Here are the highlights of this release:
       - Incremental Java compilation by default
       - Periodic Gradle caches cleanup
       - Gradle Kotlin DSL 1.0-RC6
       - Nested included builds
       - SNAPSHOT plugin versions in the `plugins {}` block
      
      For more details see https://docs.gradle.org/4.10.2/release-notes.html
      
      Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details
      
      > Configure project :
      This mapping 'snapshot_20161220' was designed for MC 1.11! Use at your own peril.
      
      FAILURE: Build failed with an exception.
      
      * Where:
      Build file '/private/var/folders/xh/kd_p58q54sg_1wrqsphxn26h0000gn/T/pip-install-mg6w5ojz/minerl_0aaaa2605f5348bea30b9b5ab04dce19/build/lib.macosx-11.1-arm64-cpython-310/minerl/Malmo/Minecraft/build.gradle' line: 313
      
      * What went wrong:
      A problem occurred evaluating root project 'Minecraft'.
      > src/main/resources/schemas.index (No such file or directory)
      
      * Try:
      Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
      
      * Get more help at https://help.gradle.org
      
      Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
      Use '--warning-mode all' to show the individual deprecation warnings.
      See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings
      
      BUILD FAILED in 12s
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
...
```

**Comment by Miffyli** [comment]
Hey. M1 silicon is not officially supported and probably failing. You can try tricks laid out [here](https://github.com/minerllabs/minerl/issues/659#issuecomment-1306635414).

**Comment by jhsul** [comment]
That worked great! Thanks for the clutch link.
