### ISSUE TITLE
Installation failed by the error: Could not get unknown property 'jar' for task ':universalJar' of type org.gradle.api.tasks.bundling.Jar.

### ISSUE THREAD

**Issue by circlegreen2** [minerllabs/minerl#702]
Hi. I'm trying to install minerl 1.0.0 on WSL Ubuntu 22.04.2 with the below command.

**pip install git+https://github.com/minerllabs/minerl --user**

I followed the doc: https://minerl.readthedocs.io/en/latest/tutorials/index.html
but following error occurs.

```
=================================
Welcome to Gradle 6.8.1!

      Here are the highlights of this release:
       - Faster Kotlin DSL script compilation
       - Vendor selection for Java toolchains
       - Convenient execution of tasks in composite builds
       - Consistent dependency resolution

      For more details see https://docs.gradle.org/6.8.1/release-notes.html

      Starting a Gradle Daemon (subsequent builds will be faster)

      > Configure project :
      [MixinGradle] Skipping eclipse integration, extension not found
      * * * * * * * * * * * * * * * * * * * * * * * *
      These are the repositories after plugins have been applied:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_-1544493048 -> downloads to: /home/ai/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *
      Repositories after removing proxied repos:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_-1544493048 -> downloads to: /home/ai/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *
      Setting up MCP environment
      Initializing steps
      Executing steps
       > Running 'downloadManifest'
       > Running 'downloadJson'
       > Running 'downloadServer'
       > Running 'strip'
       > Running 'rename'
      Stopping at requested step: /home/ai/.gradle/caches/forge_gradle/mcp_repo/de/oceanlabs/mcp/mcp_config/1.16.5-20210115.111550/server/rename/output.jar

      FAILURE: Build failed with an exception.

      * What went wrong:
      A problem occurred configuring root project 'mcprec'.
      > Could not get unknown property 'jar' for task ':universalJar' of type org.gradle.api.tasks.bundling.Jar.

      * Try:
      Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

      * Get more help at https://help.gradle.org

      Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
      Use '--warning-mode all' to show the individual deprecation warnings.
      See https://docs.gradle.org/6.8.1/userguide/command_line_interface.html#sec:command_line_warnings

      BUILD FAILED in 34s

      > Configure project :
      [MixinGradle] Skipping eclipse integration, extension not found
      * * * * * * * * * * * * * * * * * * * * * * * *
      These are the repositories after plugins have been applied:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_1242089960 -> downloads to: /home/ai/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *
      Repositories after removing proxied repos:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_1242089960 -> downloads to: /home/ai/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *

      FAILURE: Build failed with an exception.

      * What went wrong:
      A problem occurred configuring root project 'mcprec'.
      > Could not get unknown property 'jar' for task ':universalJar' of type org.gradle.api.tasks.bundling.Jar.

      * Try:
      Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

      * Get more help at https://help.gradle.org

      Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
      Use '--warning-mode all' to show the individual deprecation warnings.
      See https://docs.gradle.org/6.8.1/userguide/command_line_interface.html#sec:command_line_warnings

      BUILD FAILED in 1s

      > Configure project :
      [MixinGradle] Skipping eclipse integration, extension not found
      * * * * * * * * * * * * * * * * * * * * * * * *
      These are the repositories after plugins have been applied:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_467283282 -> downloads to: /home/ai/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *
      Repositories after removing proxied repos:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_467283282 -> downloads to: /home/ai/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *

      FAILURE: Build failed with an exception.

      * What went wrong:
      A problem occurred configuring root project 'mcprec'.
      > Could not get unknown property 'jar' for task ':universalJar' of type org.gradle.api.tasks.bundling.Jar.

      * Try:
      Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

      * Get more help at https://help.gradle.org

      Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
      Use '--warning-mode all' to show the individual deprecation warnings.
      See https://docs.gradle.org/6.8.1/userguide/command_line_interface.html#sec:command_line_warnings

      BUILD FAILED in 794ms
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-qb9h2cd1/setup.py", line 214, in <module>
          prep_mcp()
        File "/tmp/pip-req-build-qb9h2cd1/setup.py", line 193, in prep_mcp
          raise e
        File "/tmp/pip-req-build-qb9h2cd1/setup.py", line 190, in prep_mcp
          subprocess.check_call('{} downloadAssets'.format(gradlew).split(' '), cwd=workdir)
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['./gradlew', 'downloadAssets']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

========================
```

Java -> openjdk version 1.8.0_362
Python -> 3.10.6

I reinstalled Ubuntu but got the same error.
Could you tell me what is the cause? Thanks!

**Comment by fmalato** [comment]
Exact same error here.
Java -> openjdk version 1.8.0_362
Python -> 3.9.16

I am trying to install on a venv through pip. I also have another venv (untouchable) where minerl works.

**EDIT:** The original env where `minerl` works has the following dependencies:
Java -> openjdk version 1.8.0_362
Python -> **3.7.12**

Still, if I try to install on a clean env with those exact versions, I still get the error now.

**Comment by circlegreen2** [comment]
I tried on another machine (macOS) and got exact same error.
looks like not environmental issue?

**Comment by Miffyli** [comment]
Yeah this is not an environmental issue... This has something to do deeper with the build systems and such (e.g., gradle version or something has changed). This needs further investigation. If anybody has any clues or ideas, please share! I do not have plenty of bandwidth to spare on this project myself.

**Comment by boholder** [comment]
The meaing of 
```log
Could not get unknown property 'jar' for task ':universalJar' of type org.gradle.api.tasks.bundling.Jar
```
meaning that: there is one plugin we "applied" in `build.gradle` provides a task called `universalJar`, and in its definition it declared `jar` property, this property's type is `org.gradle.api.tasks.bundling.Jar`, in groovy grammar it is in form of `jar {...}`.

```log
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'mcprec'.
...
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'jar' for task ':universalJar' of type org.gradle.api.tasks.bundling.Jar.
```
Frustratingly, there is no direct dependency on this task in our `build.gradle` file, and I can't search for a way to *search for the definition of the task provided by the plugin* ([There is one](https://stackoverflow.com/questions/19191521/is-there-a-command-line-way-to-get-information-about-a-gradle-task), but doesn't work when BUILD FAILED). And a full-text-search on all project and depedency files also hits zero match (where is it?).

This `universalJar` task might be provided by `net.minecraftforge.gradle.forgedev.patcher` plugin, but in [its 1.16.x version ](https://github.com/MinecraftForge/MinecraftForge/blob/09f1b8d43856643e4ab36d9d64e2176c440a3e72/build.gradle#LL790C3-L790C3) implementation, there is no `jar` text shows up.

We get a Jar declaration in `build.gradle`, I've tried moving it here and there (because the typical MissingPropertyException happens when property is used BEFORE declared), nothing happened. 

PS: the colon of `:universalJar` means [this task will only running on the project where you executing the command](https://stackoverflow.com/questions/53394617/why-is-there-a-difference-between-gradlew-clean-build-and-gradlew-clean-bui/53426354#53426354), not related to this issue.

Keep up keeping up!

**Comment by Miffyli** [comment]
Thanks a lot @boholder ! Finding the `universalJar` in forgedev was a nice catch, but yeah, it does not seem lead to much (I am very new to gradle stuff so no idea how that works).

Another datapoint: MCP-Reborn's [build.gradle works fine](https://github.com/Hexeption/MCP-Reborn/blob/1.16.5-20210115/build.gradle) before applying the patch in this repo that modifies it.

Continuing investigation...

**Comment by Miffyli** [comment]
Think I might have cracked it! Comparing with MCP-Reborn, one of the things new build.gradle tried to get was the mixinGradle thing. [Commenting it out](https://github.com/minerllabs/minerl/commit/ead4986d0f62fa625bad2cd8175c1f4f497a4a69) seems to have fixed the issue (MineRL builds and runs seemingly fine). I reckon Mixin thing was a remnant of the past.

@boholder @fmalato  Could you try out if indeed installing now works fine?

**Comment by boholder** [comment]
> one of the things new build.gradle tried to get was the mixinGradle thing.

The mixin thing is a method to change original Minecraft code, both Forge and Fabric modding frameworks supports this.

https://github.com/SpongePowered/Mixin/wiki/Mixins-on-Minecraft-Forge

I'm not sure if commenting it out will cause those mixins (if we have) can't work, but making the gradle build succeed then we can try something about `gradle help --task` to find out more information.

Nice work!

**Comment by boholder** [comment]
Nope, the `gradle downloadAssets` works, but the next `gradle clean build shadowJar` will fail with:

```log
> Task :jaxb FAILED

FAILURE: Build failed with an exception.

* Where:
Build file 'G:\code\ml\minerl\MCP-Reborn\build.gradle' line: 380

* What went wrong:
Execution failed for task ':jaxb'.
> grammar is not specified
```

[line 380 of build.gradle ](https://github.com/minerllabs/minerl/blob/ead4986d0f62fa625bad2cd8175c1f4f497a4a69/scripts/mcp_patch.diff#LL451C1-L451C1):

```groovy
ant.xjc( destdir: 'src/main/java', package: 'com.microsoft.Malmo.Schemas' )
```

Can anyone reproduce this error?

**Comment by Miffyli** [comment]
Interesting :o . I did not have this issue even though I thought I had cleared all caches. I will try cleaning my caches and stuff.

Did you use `gradlew` or your own gradle directly to do the operation? I run my commands through `./gradlew [command]` while in the `MCP-Reborn` directory.

**Comment by boholder** [comment]
> Did you use `gradlew` or your own gradle directly to do the operation? I run my commands through `./gradlew [command]` while in the `MCP-Reborn` directory.

Yep, `gradlew.bat` directly in `MCP-Reborn` directory.

**Comment by boholder** [comment]
> Nope, the `gradle downloadAssets` works, but the next `gradle clean build shadowJar` will fail with:

I found the mistake I made: 
Misunderstood the command of the shell script -> wrong `MCP-Reborn` directory location -> `Malmo/Schemas` directory not exist -> JAXB refuses to run when no *.xsd is supplied (the `grammar is not specified` error log from JAXB tool)

The `MCP-Reborn` directory should be under `<project root>/minerl/`, not directly under `<project root>`

After fixing that, the `setup.py` finished successfully. Later I'll try to run an agent.

**Comment by lukedoma1** [comment]
was this resolved? I'm having the same issues unsure what to do. I got v1.0.0 to work on my ubuntu VM and didn't give this error, but trying to do it on the windows system is giving me this error...

**Comment by lukedoma1** [comment]
update: 
I installed with this: pip install git+https://github.com/minerllabs/minerl
instead of this:  pip install git+https://github.com/minerllabs/minerl@v1.0.0

And the error went away lol..
