### ISSUE TITLE
HelloWorld failed after building on "remove mixin"

### ISSUE THREAD

**Issue by boholder** [minerllabs/minerl#704]
Here is my code:

```python
import gym
import minerl

env = gym.make("MineRLBasaltFindCave-v0")
obs = env.reset()

done = False
while not done:
    ac = env.action_space.noop()
    # Spin around to see what is around us
    ac["camera"] = [0, 3]
    obs, reward, done, info = env.step(ac)
    env.render()
env.close()
```

When running the `obs = env.reset()`, Malmo failed to start, here is its crash report (I censored some hardware info):

```log
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 23-5-23 下午10:12
Description: Rendering overlay

java.lang.NullPointerException: "in" is null!
	at java.nio.channels.Channels.checkNotNull(Channels.java:67)
	at java.nio.channels.Channels.newChannel(Channels.java:347)
	at net.minecraft.client.renderer.texture.TextureUtil.readToBuffer(TextureUtil.java:89)
	at net.minecraft.client.renderer.texture.NativeImage.read(NativeImage.java:88)
	at net.minecraft.client.renderer.texture.NativeImage.read(NativeImage.java:80)
	at net.minecraft.client.renderer.texture.SimpleTexture$TextureData.getTextureData(SimpleTexture.java:82)
	at net.minecraft.client.renderer.texture.PreloadedTexture.lambda$new$0(PreloadedTexture.java:21)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
	Suppressed: java.lang.NullPointerException
		at net.minecraft.resources.SimpleResource.close(SimpleResource.java:113)
		at net.minecraft.client.renderer.texture.SimpleTexture$TextureData.getTextureData(SimpleTexture.java:92)
		... 7 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.nio.channels.Channels.checkNotNull(Channels.java:67)
	at java.nio.channels.Channels.newChannel(Channels.java:347)
	at net.minecraft.client.renderer.texture.TextureUtil.readToBuffer(TextureUtil.java:89)
	at net.minecraft.client.renderer.texture.NativeImage.read(NativeImage.java:88)
	at net.minecraft.client.renderer.texture.NativeImage.read(NativeImage.java:80)
	at net.minecraft.client.renderer.texture.SimpleTexture$TextureData.getTextureData(SimpleTexture.java:82)
	at net.minecraft.client.renderer.texture.PreloadedTexture.lambda$new$0(PreloadedTexture.java:21)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)

-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.updateCameraAndRender(GameRenderer.java:483)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:972)
	at net.minecraft.client.Minecraft.run(Minecraft.java:593)
	at net.minecraft.client.main.Main.main(Main.java:193)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 
	CPUs: 
	JVM Flags: 1 total; -Xmx4G
	Launched Version: ~~NULL~~
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: /PCIe/SSE2 GL version 4.6.0 NVIDIA 531.68, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 
```
Have search for a while but haven't find the solution. Can anyone re-products it?

**Comment by zhuliwen** [comment]
How did you solve it?

**Comment by boholder** [comment]
> How did you solve it?

I just gave up 😂
