### ISSUE TITLE
error obs=env.reset() // 

### ISSUE THREAD

**Issue by drozdj** [minerllabs/minerl#705]
main.py contents:
import gym 
import minerl
env = gym.make('MineRLBasaltFindCave'-v0')
obs = env.reset()

dr@macbrain:~/projects$ python3 main.py 
/usr/lib/python3.10/runpy.py:126: RuntimeWarning: 'minerl.utils.process_watcher' found in sys.modules after import of package 'minerl.utils', but prior to execution of 'minerl.utils.process_watcher'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Traceback (most recent call last):
  File "/home/dr/projects/main.py", line 5, in <module>
    obs = env.reset()
  File "/home/dr/.local/lib/python3.10/site-packages/gym/wrappers/time_limit.py", line 27, in reset
    return self.env.reset(**kwargs)
  File "/home/dr/.local/lib/python3.10/site-packages/minerl/herobraine/env_specs/basalt_specs.py", line 78, in reset
    return self.env.reset()
  File "/home/dr/.local/lib/python3.10/site-packages/minerl/herobraine/env_specs/basalt_specs.py", line 57, in reset
    return super().reset()
  File "/home/dr/.local/lib/python3.10/site-packages/gym/core.py", line 251, in reset
    return self.env.reset(**kwargs)
  File "/home/dr/.local/lib/python3.10/site-packages/minerl/env/_singleagent.py", line 22, in reset
    multi_obs = super().reset()
  File "/home/dr/.local/lib/python3.10/site-packages/minerl/env/_multiagent.py", line 436, in reset
    self._setup_instances()
  File "/home/dr/.local/lib/python3.10/site-packages/minerl/env/_multiagent.py", line 539, in _setup_instances
    self.instances.extend([f.result() for f in instance_futures])
  File "/home/dr/.local/lib/python3.10/site-packages/minerl/env/_multiagent.py", line 539, in <listcomp>
    self.instances.extend([f.result() for f in instance_futures])
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/dr/.local/lib/python3.10/site-packages/minerl/env/_multiagent.py", line 805, in _get_new_instance
    instance.launch(replaceable=self._is_fault_tolerant)
  File "/home/dr/.local/lib/python3.10/site-packages/minerl/env/malmo.py", line 427, in launch
    raise EOFError(
EOFError: /home/dr/.local/lib/python3.10/site-packages/minerl/env/../MCP-Reborn
/home/dr/.local/lib/python3.10/site-packages/minerl/env/../MCP-Reborn/launchClient.sh: line 52: java: command not found
Minecraft process finished unexpectedly. There was an error with Malmo.

**Comment by drozdj** [comment]
M1 Pro chip

**Comment by drozdj** [comment]
> M1 Pro chip
also running on vm headless linux server

**Comment by Miffyli** [comment]
See this comment for help: https://github.com/minerllabs/minerl/issues/659#issuecomment-1306635414
