### ISSUE TITLE
i have java but installation dont see it

### ISSUE THREAD

**Issue by killertop555** [minerllabs/minerl#717]
I have java jdk,jre 8(in PATH too) and linux(git and from microsoft store ubuntu) when i run pip install git+https://github.com/minerllabs/minerl this error exist
 
```
Collecting git+https://github.com/minerllabs/minerl
  Cloning https://github.com/minerllabs/minerl to c:\users\killer\appdata\local\temp\pip-req-build-abwimkvg
  Running command git clone --filter=blob:none --quiet https://github.com/minerllabs/minerl 'C:\Users\killer\AppData\Local\Temp\pip-req-build-abwimkvg'
  Resolved https://github.com/minerllabs/minerl to commit c0c9baa03b5306ffc3acddc849ec4141b6deb98e
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      Cloning into 'MCP-Reborn'...
      Note: switching to '1.16.5-20210115'.

      You are in 'detached HEAD' state. You can look around, make experimental
      changes and commit them, and you can discard any commits you make in this
      state without impacting any branches by switching back to a branch.

      If you want to create a new branch to retain commits you create, you may
      do so (now or later) by using -c with the switch command. Example:

        git switch -c <new-branch-name>

      Or undo this operation with:

        git switch -

      Turn off this advice by setting config variable advice.detachedHead to false

      HEAD is now at 1e71be5 Update README.md
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\killer\AppData\Local\Temp\pip-req-build-abwimkvg\setup.py", line 214, in <module>
          prep_mcp()
        File "C:\Users\killer\AppData\Local\Temp\pip-req-build-abwimkvg\setup.py", line 138, in prep_mcp
          raise RuntimeError(
      RuntimeError:
                          `java` and/or `javac` commands were not found by the installation script.
                          Make sure you have installed Java JDK 8.
                          On Windows, if you installed WSL/WSL2, you may need to install JDK 8 in your WSL
                          environment with `sudo apt update; sudo apt install openjdk-8-jdk`.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details. 
```

**Comment by killertop555** [comment]
solved sudo apt update; sudo apt install openjdk-8-jdk in ubuntu
