### ISSUE TITLE
Stable baselines3 ValueError: not enough values to unpack (expected 5, got 4)

### ISSUE THREAD

**Issue by Sanfee18** [minerllabs/minerl#724]
So I am trying to execute a MineRLBasaltFindCave-v0 environment with a BitMaskWrapper that sets the action space to Discrete and then translates back to the original actions shape to be able to be compatible with PPO algorithm from Stable Baselines3 that doesn't support Dict action space (actually none of them supports it). 

I've already executed this setup and it worked, but when using a Monitor wrapper before my custom wrapper **now gives this error**:

Traceback (most recent call last):
  File "/home/gti/TFG/PPO.py", line 81, in <module>
    model.learn(total_timesteps=10000000)
  File "/home/gti/miniconda3/envs/tensor-env/lib/python3.11/site-packages/stable_baselines3/ppo/ppo.py", line 308, in learn
    return super().learn(
           ^^^^^^^^^^^^^^
  File "/home/gti/miniconda3/envs/tensor-env/lib/python3.11/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 259, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gti/miniconda3/envs/tensor-env/lib/python3.11/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 178, in collect_rollouts
    new_obs, rewards, dones, infos = env.step(clipped_actions)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gti/miniconda3/envs/tensor-env/lib/python3.11/site-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 197, in step
    return self.step_wait()
           ^^^^^^^^^^^^^^^^
  File "/home/gti/miniconda3/envs/tensor-env/lib/python3.11/site-packages/stable_baselines3/common/vec_env/vec_transpose.py", line 95, in step_wait
    observations, rewards, dones, infos = self.venv.step_wait()
                                          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gti/miniconda3/envs/tensor-env/lib/python3.11/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 58, in step_wait
    obs, self.buf_rews[env_idx], terminated, truncated, self.buf_infos[env_idx] = self.envs[env_idx].step(
                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gti/miniconda3/envs/tensor-env/lib/python3.11/site-packages/stable_baselines3/common/monitor.py", line 94, in step
    observation, reward, terminated, truncated, info = self.env.step(action)
                                                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gti/miniconda3/envs/tensor-env/lib/python3.11/site-packages/shimmy/openai_gym_compatibility.py", line 257, in step
    obs, reward, done, info = self.gym_env.step(action)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gti/TFG/PPO.py", line 31, in step
    observation, reward, terminated, truncated, info = self.env.step(masked_action)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gti/miniconda3/envs/tensor-env/lib/python3.11/site-packages/stable_baselines3/common/monitor.py", line 94, in step
    observation, reward, terminated, truncated, info = self.env.step(action)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 5, got 4)

**Comment by Miffyli** [comment]
Unfortunately we do not have time to provide tech support with custom code (e.g., using MineRL with some library, like here). These issues are primarly focused on issues running the core MineRL itself.
