### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by AppStudioLB** [minerllabs/minerl#726]
```
Collecting git+https://github.com/minerllabs/minerl@v1.0.0
  Cloning https://github.com/minerllabs/minerl (to revision v1.0.0) to /tmp/pip-req-build-1e2ft2nn
  Running command git clone --filter=blob:none --quiet https://github.com/minerllabs/minerl /tmp/pip-req-build-1e2ft2nn
  Running command git checkout -b v1.0.0 --track origin/v1.0.0
  Switched to a new branch 'v1.0.0'
  Branch 'v1.0.0' set up to track remote branch 'v1.0.0' from 'origin'.
  Resolved https://github.com/minerllabs/minerl to commit c0e07f204ae45982536dba85701c094695641e0b
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [171 lines of output]
      Cloning into 'MCP-Reborn'...
      Note: switching to '1.16.5-20210115'.

      You are in 'detached HEAD' state. You can look around, make experimental
      changes and commit them, and you can discard any commits you make in this
      state without impacting any branches by switching back to a branch.

      If you want to create a new branch to retain commits you create, you may
      do so (now or later) by using -c with the switch command. Example:

        git switch -c <new-branch-name>

      Or undo this operation with:

        git switch -

      Turn off this advice by setting config variable advice.detachedHead to false

      HEAD is now at 1e71be5 Update README.md
      > Task :mcp:downloadConfig

      > Task :mcp:setupMCP
      Setting up MCP environment
      Initializing steps
      Executing steps
       > Running 'downloadManifest'
       > Running 'downloadJson'
       > Running 'downloadClient'
       > Running 'downloadServer'
       > Running 'stripClient'
       > Running 'stripServer'
       > Running 'merge'
       > Running 'rename'
       > Running 'mcinject'
       > Running 'listLibraries'
       > Running 'decompile'
       > Running 'inject'
       > Running 'patch'
      MCP environment setup is complete

      > Task :applyPatches
      > Task :downloadMappings
      > Task :srg2mcp
      > Task :extractMapped
      > Task :setup

      BUILD SUCCESSFUL in 46s
      6 actionable tasks: 6 executed

      > Configure project :
      [MixinGradle] Skipping eclipse integration, extension not found
      * * * * * * * * * * * * * * * * * * * * * * * *
      These are the repositories after plugins have been applied:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_-692010191 -> downloads to: /root/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *
      Repositories after removing proxied repos:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_-692010191 -> downloads to: /root/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *

      FAILURE: Build failed with an exception.

      * What went wrong:
      A problem occurred configuring root project 'mcprec'.
      > Could not get unknown property 'jar' for task ':universalJar' of type org.gradle.api.tasks.bundling.Jar.

      * Try:
      Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

      * Get more help at https://help.gradle.org

      Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
      Use '--warning-mode all' to show the individual deprecation warnings.
      See https://docs.gradle.org/6.8.1/userguide/command_line_interface.html#sec:command_line_warnings

      BUILD FAILED in 1s

      > Configure project :
      [MixinGradle] Skipping eclipse integration, extension not found
      * * * * * * * * * * * * * * * * * * * * * * * *
      These are the repositories after plugins have been applied:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_258879651 -> downloads to: /root/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *
      Repositories after removing proxied repos:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_258879651 -> downloads to: /root/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *

      FAILURE: Build failed with an exception.

      * What went wrong:
      A problem occurred configuring root project 'mcprec'.
      > Could not get unknown property 'jar' for task ':universalJar' of type org.gradle.api.tasks.bundling.Jar.

      * Try:
      Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

      * Get more help at https://help.gradle.org

      Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
      Use '--warning-mode all' to show the individual deprecation warnings.
      See https://docs.gradle.org/6.8.1/userguide/command_line_interface.html#sec:command_line_warnings

      BUILD FAILED in 948ms

      > Configure project :
      [MixinGradle] Skipping eclipse integration, extension not found
      * * * * * * * * * * * * * * * * * * * * * * * *
      These are the repositories after plugins have been applied:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_939605684 -> downloads to: /root/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *
      Repositories after removing proxied repos:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_939605684 -> downloads to: /root/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *

      FAILURE: Build failed with an exception.

      * What went wrong:
      A problem occurred configuring root project 'mcprec'.
      > Could not get unknown property 'jar' for task ':universalJar' of type org.gradle.api.tasks.bundling.Jar.

      * Try:
      Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

      * Get more help at https://help.gradle.org

      Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
      Use '--warning-mode all' to show the individual deprecation warnings.
      See https://docs.gradle.org/6.8.1/userguide/command_line_interface.html#sec:command_line_warnings

      BUILD FAILED in 885ms
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-1e2ft2nn/setup.py", line 215, in <module>
          prep_mcp()
        File "/tmp/pip-req-build-1e2ft2nn/setup.py", line 193, in prep_mcp
          raise e
        File "/tmp/pip-req-build-1e2ft2nn/setup.py", line 190, in prep_mcp
          subprocess.check_call('{} downloadAssets'.format(gradlew).split(' '), cwd=workdir)
        File "/root/anaconda3/envs/MineRL_VPT/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['./gradlew', 'downloadAssets']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

==============================================================

How can I solve this error?

**Comment by Miffyli** [comment]
v1.0.0 does not work (could you point where you found this instruction so we can fix it?). Install `pip install git+https://github.com/minerllabs/minerl`

**Comment by AppStudioLB** [comment]
I found this instruction from Korean personal blog. Thank you, I solve the error.

**Comment by zhufq00** [comment]
> I found this instruction from Korean personal blog. Thank you, I solve the error.

Can you tell me how you solved this problem, I had the exact same problem, thanks a lot

**Comment by AppStudioLB** [comment]
Just install it(MineRL) with this command 

`pip install git+https://github.com/minerllabs/minerl`
