### ISSUE TITLE
TypeError for draw taking less arguments than given.

### ISSUE THREAD

**Issue by UnixTMDev** [minerllabs/minerl#738]
```
[I] unix@unix-mint ~/c/p/AICraft> MINERL_DATA_ROOT='/home/unix/code/py/AICraft' python3 -m minerl.viewer MineRLBasaltFindCave-v0
/home/unix/.local/lib/python3.10/site-packages/gym/logger.py:34: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))
2023-10-28 00:40:46 unix-mint __main__[117061] INFO Welcome to the MineRL Stream viewer! 

2023-10-28 00:40:46 unix-mint __main__[117061] INFO Building data pipeline for MineRLBasaltFindCave-v0
2023-10-28 00:40:46 unix-mint __main__[117061] INFO Loading data for v3_wasteful_carrot_vampire-3_29806-31129...
2023-10-28 00:40:46 unix-mint minerl.data.data_pipeline[117061] DEBUG Loading from file /home/unix/code/py/AICraft/MineRLBasaltFindCave-v0/v3_wasteful_carrot_vampire-3_29806-31129
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1294/1294 [00:00<00:00, 27896.78it/s]
2023-10-28 00:40:46 unix-mint __main__[117061] INFO Data loading complete!
2023-10-28 00:40:46 unix-mint __main__[117061] INFO META DATA: {'success': False, 'duration_ms': 64700, 'duration_steps': 1294, 'total_reward': 0.0, 'stream_name': 'v3_wasteful_carrot_vampire-3_29806-31129', 'true_video_frame_count': 1325}
<pyglet.font.fontconfig.FontConfigSearchResult object at 0x7f221d43cbb0>
<pyglet.font.fontconfig.FontConfigSearchResult object at 0x7f221d43e260>
<pyglet.font.fontconfig.FontConfigSearchResult object at 0x7f221d43fcd0>
0it [00:00, ?it/s]2023-10-28 00:40:46 unix-mint matplotlib[117061] DEBUG matplotlib data path: /home/unix/.local/lib/python3.10/site-packages/matplotlib/mpl-data
2023-10-28 00:40:46 unix-mint matplotlib[117061] DEBUG CONFIGDIR=/home/unix/.config/matplotlib
2023-10-28 00:40:46 unix-mint matplotlib[117061] DEBUG interactive is False
2023-10-28 00:40:46 unix-mint matplotlib[117061] DEBUG platform is linux
2023-10-28 00:40:46 unix-mint matplotlib[117061] DEBUG CACHEDIR=/home/unix/.cache/matplotlib
2023-10-28 00:40:46 unix-mint matplotlib.font_manager[117061] DEBUG Using fontManager instance from /home/unix/.cache/matplotlib/fontlist-v330.json
2023-10-28 00:40:46 unix-mint matplotlib.pyplot[117061] DEBUG Loaded backend agg version v2.2.
2023-10-28 00:40:46 unix-mint matplotlib.font_manager[117061] DEBUG findfont: Matching sans\-serif:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0.
2023-10-28 00:40:46 unix-mint matplotlib.font_manager[117061] DEBUG findfont: score(FontEntry(fname='/home/unix/.local/lib/python3.10/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSerif-Italic.ttf', name='DejaVu Serif', style='italic', variant='normal', weight=400, stretch='normal', size='scalable')) = 11.05
2023-10-28 00:40:46 unix-mint matplotlib.font_manager[117061] DEBUG findfont: score(FontEntry(fname='/home/unix/.local/lib/python3.10/site-packages/matplotlib/mpl-data/fonts/ttf/STIXSizOneSymReg.ttf', name='STIXSizeOneSym', style='normal', variant='normal', weight=400, stretch='normal', size='scalable')) = 10.05
2023-10-28 00:40:46 unix-mint matplotlib.font_manager[117061] DEBUG findfont: score(FontEntry(fname='/home/unix/.local/lib/python3.10/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans-Oblique.ttf', name='DejaVu Sans', style='oblique', variant='normal', weight=400, stretch='normal', size='scalable')) = 1.05

[a lot of what i think is debug text from matplotlib]

<pyglet.font.fontconfig.FontConfigSearchResult object at 0x7f220fcfa3e0>
<pyglet.font.fontconfig.FontConfigSearchResult object at 0x7f220fcfb820>
<pyglet.font.fontconfig.FontConfigSearchResult object at 0x7f221d43cbb0>
<pyglet.font.fontconfig.FontConfigSearchResult object at 0x7f220fb23100>
<pyglet.font.fontconfig.FontConfigSearchResult object at 0x7f221d43fcd0>
<pyglet.font.fontconfig.FontConfigSearchResult object at 0x7f220fcface0>
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/unix/.local/lib/python3.10/site-packages/minerl/viewer/__main__.py", line 50, in <module>
    main(env_name=args.environment, stream_name=args.stream_name)
  File "/home/unix/.local/lib/python3.10/site-packages/minerl/viewer/__main__.py", line 45, in main
    trajectory_display_controller.run()
  File "/home/unix/.local/lib/python3.10/site-packages/minerl/viewer/trajectory_display_controller.py", line 90, in run
    self.display.render(obs, rew, done, action, self.position, file_len)
  File "/home/unix/.local/lib/python3.10/site-packages/minerl/viewer/trajectory_display.py", line 162, in render
    self.cum_reward_rect.draw()
  File "/home/unix/.local/lib/python3.10/site-packages/minerl/viewer/primitives.py", line 17, in draw
    pyglet.graphics.draw(4, pyglet.gl.GL_QUADS, self._quad, self._color_str)
TypeError: draw() takes 2 positional arguments but 4 were given
[I] unix@unix-mint ~/c/p/AICraft [1]>
```
I'm not sure what to do about this. I haven't even written the code that's failing.
Here's a neofetch I guess (without the logo)
```
unix@unix-mint 
-------------- 
OS: Linux Mint 21.1 x86_64 
Kernel: 5.15.0-87-generic 
Uptime: 1 day, 13 hours, 58 mins 
Packages: 3870 (dpkg), 14 (flatpak) 
Shell: fish 3.3.1 
Resolution: 3840x2160, 2160x3840, 2160x3840 
WM: i3 
Theme: Mint-Y-Aqua [GTK3] 
Icons: Mint-Y-Aqua [GTK3] 
Terminal: gnome-terminal 
CPU: Intel i7-3770K (8) @ 3.900GHz 
GPU: NVIDIA GeForce GTX 1080 
Memory: 12133MiB / 15932MiB
```

**Comment by Miffyli** [comment]
Heya. We have not touched/updated that part of the code in the long time. My first guess is that pyglet has updated their API since the time code was written, since pyglet version was not fixed in requirements.txt. I recommend trying a pyglet version from 2019, e.g. `pip install pyglet==1.4.11` or `pip install pyglet==1.5`.

**Comment by UnixTMDev** [comment]
Sick! It worked! Thanks
