### ISSUE TITLE
<Find> and <Interact> not implemented in EnvServer.java

### ISSUE THREAD

**Issue by Skirlax** [minerllabs/minerl#749]
Hello.

I've been looking into why the interactor and multiagent envs don't work on  the latest version. I've noticed that the minerl's `EnvServer.java` isn't handling the `<Find>` and `<Interact>` tags like the `MalmoEnvServer.java` is. This also seems to be the reason why the interactor fails, since the debug log error message comes from `throw new IOException("Unknown env service command: " + command);`. Before trying to implement this I wanted to ask if there's a reason why this is the case; maybe I am missing something.

Paths:
`minerl/Malmo/Minecraft/src/main/java/com/microsoft/Malmo/Client/MalmoEnvServer.java`
`minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/env/EnvServer.java`

**Comment by Miffyli** [comment]
Hey. Yup this seems right. Malmö code is not being used in the new version actively (IIRC things failed if I tried to remove the folder, which is why it is still there, but the code is not generally used). The Python side still tries to use similar API as before, so the new Minecraft side code re-implements some very specific bits of the commands, but only very few to minimally support the things OpenAI did with this environment (spawning to fresh new world without changes) + BASALT environments (e.g., spawning to a village). Anything outside that is probably not supported.

**Comment by Skirlax** [comment]
Alright, thanks so much.

I am going to implement as much as I can in the next few weeks.

**Comment by Matoi647** [comment]
Have you fixed this issue? I'm also trying to fix the interactor. 
When I run interactor using the latest version, the error says:
``` shell
python -m minerl.interactor 55555
/home/matoi/Github/rl/MineRL/minerl-chat-env/lib/python3.10/site-packages/gym/wrappers/monitoring/video_recorder.py:9: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.spawn
2024-04-14 19:36:12 DESKTOP-29UAI3U __main__[5569] WARNING No existing interactor found on port 31415. Starting a new interactor.
2024-04-14 19:36:12 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] INFO Starting Minecraft process: ['/home/matoi/Github/rl/MineRL/minerl-chat-env/lib/python3.10/site-packages/minerl/env/../MCP-Reborn/launchClient.sh', '-port', '31415', '-env', '-runDir', '/home/matoi/Github/rl/MineRL/minerl-chat-env/lib/python3.10/site-packages/minerl/env/../MCP-Reborn/run']
2024-04-14 19:36:12 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] DEBUG /home/matoi/Github/rl/MineRL/minerl-chat-env/lib/python3.10/site-packages/minerl/env/../MCP-Reborn
2024-04-14 19:36:22 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] DEBUG SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2024-04-14 19:36:22 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] DEBUG SLF4J: Defaulting to no-operation (NOP) logger implementation
2024-04-14 19:36:22 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] DEBUG SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2024-04-14 19:36:27 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] DEBUG [19:36:27] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
2024-04-14 19:36:31 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] DEBUG [19:36:31] [Render thread/INFO]: Setting user: Player723
2024-04-14 19:36:32 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] DEBUG [19:36:32] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT
2024-04-14 19:36:40 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] ERROR [19:36:40] [Render thread/WARN]: ERROR : Couldn't load Narrator library : Unable to load library 'fliteWrapper': Can't obtain InputStream for linux-x86-64/libfliteWrapper.so
2024-04-14 19:36:40 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] DEBUG [19:36:40] [Render thread/INFO]: Reloading ResourceManager: Default
2024-04-14 19:36:40 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] DEBUG [19:36:40] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
2024-04-14 19:36:43 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] DEBUG [19:36:43] [Render thread/INFO]: OpenAL initialized.
2024-04-14 19:36:43 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] DEBUG [19:36:43] [Render thread/INFO]: Sound engine started
2024-04-14 19:36:44 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] DEBUG [19:36:44] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
2024-04-14 19:36:44 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] DEBUG [19:36:44] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
2024-04-14 19:36:44 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] DEBUG [19:36:44] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
2024-04-14 19:36:44 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] DEBUG [19:36:44] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
2024-04-14 19:36:44 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] DEBUG [19:36:44] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
2024-04-14 19:36:44 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] DEBUG [19:36:44] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
2024-04-14 19:36:44 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] DEBUG [19:36:44] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
2024-04-14 19:36:45 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] DEBUG [19:36:45] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
2024-04-14 19:36:45 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] DEBUG [19:36:45] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
2024-04-14 19:36:45 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] DEBUG [19:36:45] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
2024-04-14 19:36:46 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] DEBUG [19:36:46] [Thread-4/INFO]: [STDOUT]: ***** Start MalmoEnvServer on port 31415
2024-04-14 19:36:46 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] DEBUG [19:36:46] [Thread-4/INFO]: [STDOUT]: CLIENT enter state: DORMANT
2024-04-14 19:36:46 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] INFO Minecraft process ready
/home/matoi/Github/rl/MineRL/minerl-chat-env/lib/python3.10/site-packages/minerl/env/malmo.py:494: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
  self._logger_thread.setDaemon(True)
2024-04-14 19:36:46 DESKTOP-29UAI3U minerl.env.malmo[5569] INFO Logging output of Minecraft to ./logs/mc_22415.log
2024-04-14 19:36:46 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] DEBUG [19:36:46] [Thread-4/INFO]: [STDOUT]: SERVER enter state: DORMANT
2024-04-14 19:36:46 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] ERROR [19:36:46] [EnvServerSocketHandler/INFO]: [STDERR]: java.io.IOException: Unknown env service command: <Interact>127.0.0.1:55555</Interact>
2024-04-14 19:36:46 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] ERROR [19:36:46] [EnvServerSocketHandler/INFO]: [STDERR]:    at com.minerl.multiagent.env.EnvServer$1.run(EnvServer.java:169)
2024-04-14 19:36:46 DESKTOP-29UAI3U minerl.env.malmo.instance.12818b[5569] ERROR [19:36:46] [EnvServerSocketHandler/FATAL]: MalmoEnv socket error: java.io.IOException: Unknown env service command: <Interact>127.0.0.1:55555</Interact> (can be on disconnect)
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/matoi/Github/rl/MineRL/minerl-chat-env/lib/python3.10/site-packages/minerl/interactor/__main__.py", line 80, in <module>
    run_interactor(ip=opts.ip, port=opts.port)
  File "/home/matoi/Github/rl/MineRL/minerl-chat-env/lib/python3.10/site-packages/minerl/interactor/__main__.py", line 56, in run_interactor
    request_interactor(
  File "/home/matoi/Github/rl/MineRL/minerl-chat-env/lib/python3.10/site-packages/minerl/interactor/__main__.py", line 28, in request_interactor
    ok, = struct.unpack('!I', reply)
TypeError: a bytes-like object is required, not 'NoneType'
```
So I checked the `MalmoEnvServer.java`, and tried to implement `<Interact>` in `EnvServer.java`, here is my `interact()` function:
``` java

    // Handler for interact (which connects a client to an IP via multiplayer.).

    private final static int interactTagLength = "<Interact>".length();

    private void interact(String command, Socket socket) throws IOException {

        String token = command.substring(interactTagLength, command.length() - (interactTagLength + 1));
        LOGGER.info("Find token? " + token);

        // Purge previous token.
        String[] tokenSplits = token.split(":");
        String ip = tokenSplits[0];
        String port = tokenSplits[1];
        //Print the ip and port
        final ServerData sd = new ServerData("agent server", ip + ":" + port, false);

        Minecraft mc = Minecraft.getInstance();
        mc.displayGuiScreen(new ConnectingScreen(new MainMenuScreen(false), mc, serverData));
           
        // Say that we r done.
        DataOutputStream dout = new DataOutputStream(socket.getOutputStream());
        dout.writeInt(BYTES_INT);
        dout.writeInt(1);
        dout.flush();
    }
```
After adding `interact()` function, the `Unknown env service command` disappeared, but the interactor still can't receive message from the server, here is the log after adding `interact()`:
``` shell
/home/matoi/Github/rl/MineRL/minerl-chat-env-interactor/lib/python3.10/site-packages/gym/wrappers/monitoring/video_recorder.py:9: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.spawn
2024-05-26 09:20:14 DESKTOP-29UAI3U __main__[11192] WARNING No existing interactor found on port 31415. Starting a new interactor.
2024-05-26 09:20:14 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] INFO Starting Minecraft process: ['/home/matoi/Github/rl/MineRL/minerl-chat-env-interactor/lib/python3.10/site-packages/minerl/env/../MCP-Reborn/launchClient.sh', '-port', '31415', '-env', '-runDir', '/home/matoi/Github/rl/MineRL/minerl-chat-env-interactor/lib/python3.10/site-packages/minerl/env/../MCP-Reborn/run']
2024-05-26 09:20:14 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG /home/matoi/Github/rl/MineRL/minerl-chat-env-interactor/lib/python3.10/site-packages/minerl/env/../MCP-Reborn
2024-05-26 09:20:24 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2024-05-26 09:20:24 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG SLF4J: Defaulting to no-operation (NOP) logger implementation
2024-05-26 09:20:24 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2024-05-26 09:20:28 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG [09:20:28] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
2024-05-26 09:20:29 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG [09:20:29] [Render thread/INFO]: Setting user: Player8
2024-05-26 09:20:29 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG [09:20:29] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT
2024-05-26 09:20:32 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] ERROR [09:20:32] [Render thread/WARN]: ERROR : Couldn't load Narrator library : Unable to load library 'fliteWrapper': Can't obtain InputStream for linux-x86-64/libfliteWrapper.so
2024-05-26 09:20:32 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG [09:20:32] [Render thread/INFO]: Reloading ResourceManager: Default
2024-05-26 09:20:33 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG [09:20:33] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
2024-05-26 09:20:38 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG [09:20:38] [Render thread/INFO]: OpenAL initialized.
2024-05-26 09:20:38 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG [09:20:38] [Render thread/INFO]: Sound engine started
2024-05-26 09:20:40 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG [09:20:40] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
2024-05-26 09:20:41 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG [09:20:41] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
2024-05-26 09:20:41 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG [09:20:41] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
2024-05-26 09:20:41 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG [09:20:41] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
2024-05-26 09:20:41 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG [09:20:41] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
2024-05-26 09:20:41 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG [09:20:41] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
2024-05-26 09:20:41 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG [09:20:41] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
2024-05-26 09:20:43 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG [09:20:43] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
2024-05-26 09:20:43 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG [09:20:43] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
2024-05-26 09:20:43 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG [09:20:43] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
2024-05-26 09:20:44 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG [09:20:44] [Thread-4/INFO]: [STDOUT]: ***** Start MalmoEnvServer on port 31415
2024-05-26 09:20:44 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG [09:20:44] [Thread-4/INFO]: [STDOUT]: CLIENT enter state: DORMANT
2024-05-26 09:20:44 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] INFO Minecraft process ready
/home/matoi/Github/rl/MineRL/minerl-chat-env-interactor/lib/python3.10/site-packages/minerl/env/malmo.py:494: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
  self._logger_thread.setDaemon(True)
2024-05-26 09:20:44 DESKTOP-29UAI3U minerl.env.malmo[11192] INFO Logging output of Minecraft to ./logs/mc_22415.log
2024-05-26 09:20:44 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG [09:20:44] [Thread-4/INFO]: [STDOUT]: SERVER enter state: DORMANT
2024-05-26 09:20:44 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG [09:20:44] [EnvServerSocketHandler/INFO]: Find token? 127.0.0.1:31415
2024-05-26 09:20:44 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] ERROR [09:20:44] [EnvServerSocketHandler/ERROR]: Error while processing commands
2024-05-26 09:20:44 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] ERROR java.lang.IllegalStateException: Rendersystem called from wrong thread
2024-05-26 09:20:44 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG at com.mojang.blaze3d.systems.RenderSystem.assertThread(RenderSystem.java:76) ~[mcprec-6.13.jar:?]
2024-05-26 09:20:44 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG at com.mojang.blaze3d.platform.GlStateManager.pushMatrix(GlStateManager.java:1122) ~[mcprec-6.13.jar:?]
2024-05-26 09:20:44 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG at com.mojang.blaze3d.systems.RenderSystem.pushMatrix(RenderSystem.java:476) ~[mcprec-6.13.jar:?]
2024-05-26 09:20:44 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:962) ~[mcprec-6.13.jar:?]
2024-05-26 09:20:44 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG at net.minecraft.client.Minecraft.updateScreenTick(Minecraft.java:1932) ~[mcprec-6.13.jar:?]
2024-05-26 09:20:44 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG at net.minecraft.client.Minecraft.unloadWorld(Minecraft.java:1902) ~[mcprec-6.13.jar:?]
2024-05-26 09:20:44 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG at net.minecraft.client.Minecraft.unloadWorld(Minecraft.java:1887) ~[mcprec-6.13.jar:?]
2024-05-26 09:20:44 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG at net.minecraft.client.gui.screen.ConnectingScreen.<init>(ConnectingScreen.java:42) ~[mcprec-6.13.jar:?]
2024-05-26 09:20:44 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG at com.minerl.multiagent.env.EnvServer.interact(EnvServer.java:728) ~[mcprec-6.13.jar:?]
2024-05-26 09:20:44 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG at com.minerl.multiagent.env.EnvServer.access$300(EnvServer.java:50) ~[mcprec-6.13.jar:?]
2024-05-26 09:20:44 DESKTOP-29UAI3U minerl.env.malmo.instance.f61346[11192] DEBUG at com.minerl.multiagent.env.EnvServer$1.run(EnvServer.java:131) [mcprec-6.13.jar:?]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/matoi/Github/rl/MineRL/minerl-chat-env-interactor/lib/python3.10/site-packages/minerl/interactor/__main__.py", line 81, in <module>
    run_interactor(ip=opts.ip, port=opts.port)
  File "/home/matoi/Github/rl/MineRL/minerl-chat-env-interactor/lib/python3.10/site-packages/minerl/interactor/__main__.py", line 57, in run_interactor
    request_interactor(
  File "/home/matoi/Github/rl/MineRL/minerl-chat-env-interactor/lib/python3.10/site-packages/minerl/interactor/__main__.py", line 29, in request_interactor
    ok, = struct.unpack('!I', reply)
TypeError: a bytes-like object is required, not 'NoneType'
```

**Comment by Miffyli** [comment]
Unfortunately I do not have time to give much custom tech support here. However, from what I remember, interactor has not been updated in almost any way for the newest (+1.0) MineRL, so implementing support for it might be overly difficult. In original Malmö version (0.4.4 and older) the support was possible because of the very extensive tools Malmö had implemented.

**Comment by Matoi647** [comment]
> Unfortunately I do not have time to give much custom tech support here. However, from what I remember, interactor has not been updated in almost any way for the newest (+1.0) MineRL, so implementing support for it might be overly difficult. In original Malmö version (0.4.4 and older) the support was possible because of the very extensive tools Malmö had implemented.

Thank you. I just wanted to interact with VPT, didn't expect it to be so hard :) Maybe I should use v0.4.4 and modify the VPT code to fit v0.4.4.

**Comment by Miffyli** [comment]
@Matoi647  That also might be pretty tricky (but potentially do-able), given the action and observation spaces.

You could look at work that has used VPT, e.g. [STEVE-1](https://github.com/Shalev-Lifshitz/STEVE-1) and see if they have any cool interaction script somewhere in the code.
