### ISSUE TITLE
install minerl error ,my java  version is 1.8.0_402

### ISSUE THREAD

**Issue by jiabin-guo** [minerllabs/minerl#762]
pip install git+https://github.com/Zhoues/minerl
Collecting git+https://github.com/Zhoues/minerl
  Cloning https://github.com/Zhoues/minerl to /tmp/pip-req-build-2ta_yraf
  Running command git clone --filter=blob:none --quiet https://github.com/Zhoues/minerl /tmp/pip-req-build-2ta_yraf
  Resolved https://github.com/Zhoues/minerl to commit d69b85a17697bb3c6c18f1cc8d31cd73726d251d
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [412 lines of output]
      bash: /home/gjb/anaconda3/envs/minedreamer/lib/libtinfo.so.6: no version information available (required by bash)
      正克隆到 'MCP-Reborn'...
      注意：正在切换到 '1.16.5-20210115'。
      
      您正处于分离头指针状态。您可以查看、做试验性的修改及提交，并且您可以在切换
      回一个分支时，丢弃在此状态下所做的提交而不对分支造成影响。
      
      如果您想要通过创建分支来保留在此状态下所做的提交，您可以通过在 switch 命令
      中添加参数 -c 来实现（现在或稍后）。例如：
      
        git switch -c <新分支名>
      
      或者撤销此操作：
      
        git switch -
      
      通过将配置变量 advice.detachedHead 设置为 false 来关闭此建议
      
      HEAD 目前位于 1e71be5 Update README.md
      Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
      > Task :mcp:downloadConfig
      
      > Task :mcp:setupMCP
      Setting up MCP environment
      Initializing steps
      Executing steps
       > Running 'downloadManifest'
       > Running 'downloadJson'
       > Running 'downloadClient'
       > Running 'downloadServer'
       > Running 'stripClient'
       > Running 'stripServer'
       > Running 'merge'
       > Running 'rename'
       > Running 'mcinject'
       > Running 'listLibraries'
       > Running 'decompile'
       > Running 'inject'
       > Running 'patch'
      MCP environment setup is complete
      
      > Task :applyPatches
      > Task :downloadMappings
      > Task :srg2mcp
      > Task :extractMapped
      > Task :setup
      
      BUILD SUCCESSFUL in 45s
      6 actionable tasks: 6 executed
      bash: /home/gjb/anaconda3/envs/minedreamer/lib/libtinfo.so.6: no version information available (required by bash)
      patch: **** Failed to set the permissions of file src/main/java/net/minecraft/client/MouseHelper.java.oepqppT : Too many open files
      Starting a Gradle Daemon, 2 incompatible and 1 stopped Daemons could not be reused, use --status for details
      
      > Configure project :
      * * * * * * * * * * * * * * * * * * * * * * * *
      These are the repositories after plugins have been applied:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_-1311421419 -> downloads to: /home/gjb/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *
      Repositories after removing proxied repos:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_-1311421419 -> downloads to: /home/gjb/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *
      
      > Task :verifyRepos
      Checking BuildScript Repositories:
       | - [ OK ]: MavenLocal -> file:/home/gjb/.m2/repository
       | - [FAIL]: MavenRepo -> https://repo.maven.apache.org/maven2/
       | - [FAIL]: BintrayJCenter -> https://jcenter.bintray.com/
       | - [FAIL]: maven -> https://repo.spongepowered.org/maven/
      Checking Project Repositories:
       | - [FAIL]: MavenRepo -> https://repo.maven.apache.org/maven2/
       | - [FAIL]: BintrayJCenter -> https://jcenter.bintray.com/
       | - [FAIL]: maven -> https://repo.spongepowered.org/maven/
       | - [FAIL]: maven2 -> https://maven.minecraftforge.net/
       | - [ OK ]: BUNDELED_-1311421419 (accepted custom MC repo)
       | - [FAIL]: maven3 -> https://libraries.minecraft.net/
      
      > Task :downloadMCMeta
      > Task :downloadAssets
      
      Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
      Use '--warning-mode all' to show the individual deprecation warnings.
      See https://docs.gradle.org/6.8.1/userguide/command_line_interface.html#sec:command_line_warnings
      
      BUILD SUCCESSFUL in 23s
      3 actionable tasks: 3 executed
      
      > Configure project :
      * * * * * * * * * * * * * * * * * * * * * * * *
      These are the repositories after plugins have been applied:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_1112360901 -> downloads to: /home/gjb/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *
      Repositories after removing proxied repos:
       | - MavenRepo -> https://repo.maven.apache.org/maven2/
       | - BintrayJCenter -> https://jcenter.bintray.com/
       | - maven -> https://repo.spongepowered.org/maven/
       | - maven2 -> https://maven.minecraftforge.net/
       | - BUNDELED_1112360901 -> downloads to: /home/gjb/.gradle/caches/forge_gradle/bundeled_repo/
       | - maven3 -> https://libraries.minecraft.net/
      * * * * * * * * * * * * * * * * * * * * * * * *
      
      > Task :verifyRepos
      Checking BuildScript Repositories:
       | - [ OK ]: MavenLocal -> file:/home/gjb/.m2/repository
       | - [FAIL]: MavenRepo -> https://repo.maven.apache.org/maven2/
       | - [FAIL]: BintrayJCenter -> https://jcenter.bintray.com/
       | - [FAIL]: maven -> https://repo.spongepowered.org/maven/
      Checking Project Repositories:
       | - [FAIL]: MavenRepo -> https://repo.maven.apache.org/maven2/
       | - [FAIL]: BintrayJCenter -> https://jcenter.bintray.com/
       | - [FAIL]: maven -> https://repo.spongepowered.org/maven/
       | - [FAIL]: maven2 -> https://maven.minecraftforge.net/
       | - [ OK ]: BUNDELED_1112360901 (accepted custom MC repo)
       | - [FAIL]: maven3 -> https://libraries.minecraft.net/
      
      > Task :clean
      > Task :deleteSchemas
      > Task :copySchemas
      > Task :jaxb
      
      > Task :compileJava
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/env/EnvServer.java:634: 错误: 找不到符号
          private static MouseHelper.State constructMouseState(String actions) {
                                    ^
        符号:   类 State
        位置: 类 MouseHelper
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/recorder/PlayRecorder.java:14: 错误: 找不到符号
      import net.minecraft.client.ReplaySender;
                                 ^
        符号:   类 ReplaySender
        位置: 程序包 net.minecraft.client
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/recorder/PlayRecorder.java:318: 错误: 找不到符号
          public void setMouseKeyboardState(MouseHelper.State mouseState, KeyboardListener.State keyboardState) {
                                                       ^
        符号:   类 State
        位置: 类 MouseHelper
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/microsoft/Malmo/Utils/JSONWorldDataHelper.java:130: 错误: 找不到符号
              for(Stat<?> stat : statisticsManager.getKeys()) {
                                                  ^
        符号:   方法 getKeys()
        位置: 类型为StatisticsManager的变量 statisticsManager
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/microsoft/Malmo/Utils/JSONWorldDataHelper.java:173: 错误: 找不到符号
              for(Stat stat : statisticsManager.getKeys()) {
                                               ^
        符号:   方法 getKeys()
        位置: 类型为StatisticsManager的变量 statisticsManager
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/net/minecraft/client/Minecraft.java:412: 错误: 找不到符号
               InputStream inputstream = new JavaResourcePack().getResourceStream(ResourcePackType.CLIENT_RESOURCES, new ResourceLocation("icons", "icon_16x16.png"));
                                             ^
        符号:   类 JavaResourcePack
        位置: 类 Minecraft
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/net/minecraft/client/Minecraft.java:413: 错误: 找不到符号
               InputStream inputstream1 = new JavaResourcePack().getResourceStream(ResourcePackType.CLIENT_RESOURCES, new ResourceLocation("icons", "icon_32x32.png"));
                                              ^
        符号:   类 JavaResourcePack
        位置: 类 Minecraft
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/net/minecraft/client/Minecraft.java:941: 错误: 找不到符号
                     ReplaySender.getInstance().tick();
                     ^
        符号:   变量 ReplaySender
        位置: 类 Minecraft
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/net/minecraft/client/Minecraft.java:946: 错误: 找不到符号
                     integratedServer.runSyncTick(profiler);
                                     ^
        符号:   方法 runSyncTick(IProfiler)
        位置: 类型为IntegratedServer的变量 integratedServer
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/net/minecraft/client/Minecraft.java:1061: 错误: 找不到符号
               if (!this.gameTimeTracker.isTracking()) {
                                        ^
        符号:   方法 isTracking()
        位置: 类型为TimeTracker的变量 gameTimeTracker
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/net/minecraft/client/Minecraft.java:1063: 错误: 找不到符号
                  this.gameTimeTracker.startTracking();
                                      ^
        符号:   方法 startTracking()
        位置: 类型为TimeTracker的变量 gameTimeTracker
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/net/minecraft/client/Minecraft.java:1068: 错误: 找不到符号
               this.gameTimeTracker.stopTracking();
                                   ^
        符号:   方法 stopTracking()
        位置: 类型为TimeTracker的变量 gameTimeTracker
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/net/minecraft/client/Minecraft.java:1071: 错误: 找不到符号
            this.profiler = LongTickDetector.getProfiler(this.gameTimeTracker.getProfiler(), detector);
                                                                             ^
        符号:   方法 getProfiler()
        位置: 类型为TimeTracker的变量 gameTimeTracker
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/net/minecraft/client/Minecraft.java:1080: 错误: 找不到符号
               this.profilerResult = this.gameTimeTracker.getResults();
                                                         ^
        符号:   方法 getResults()
        位置: 类型为TimeTracker的变量 gameTimeTracker
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/net/minecraft/client/Minecraft.java:1085: 错误: 找不到符号
            this.profiler = this.gameTimeTracker.getProfiler();
                                                ^
        符号:   方法 getProfiler()
        位置: 类型为TimeTracker的变量 gameTimeTracker
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/net/minecraft/client/Minecraft.java:1674: 错误: 找不到符号
            loadWorld(savePath, worldName, DynamicRegistries.getImpl(),Minecraft::loadDataPackCodec,Minecraft::loadWorld,false,Minecraft.WorldSelectionType.BACKUP);
                                                            ^
        符号:   方法 getImpl()
        位置: 类 DynamicRegistries
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/net/minecraft/client/Minecraft.java:1694: 错误: 无法将类 SaveFormat中的方法 getLevelSave应用到给定类型;
               saveformat$levelsave = this.saveFormat.getLevelSave(savePath, worldName);
                                                     ^
        需要: String
        找到: Path,String
        原因: 实际参数列表和形式参数列表长度不同
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/net/minecraft/client/Minecraft.java:1746: 错误: 找不到符号
                     integratedServer.runTickAndTasks();
                                     ^
        符号:   方法 runTickAndTasks()
        位置: 类型为IntegratedServer的变量 integratedServer
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/net/minecraft/client/KeyboardListener.java:263: 错误: 找不到符号
               if (mc.mouseHelper.getHumanInput()) {
                                 ^
        符号:   方法 getHumanInput()
        位置: 类型为MouseHelper的变量 mouseHelper
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/net/minecraft/client/KeyboardListener.java:382: 错误: 找不到符号
               if (mc.mouseHelper.getHumanInput()) {
                                 ^
        符号:   方法 getHumanInput()
        位置: 类型为MouseHelper的变量 mouseHelper
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/env/FakeMouseCursor.java:79: 错误: 找不到符号
                  IResourcePack resourcePack = new JavaResourcePack();
                                                   ^
        符号:   类 JavaResourcePack
        位置: 类 FakeMouseCursor
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/env/EnvServer.java:261: 错误: 找不到符号
              mc.getSession().setUsername(missionInit.getMission().getAgentSection().get(0).getName());
                             ^
        符号:   方法 setUsername(String)
        位置: 类 Session
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/env/EnvServer.java:330: 错误: 找不到符号
                  Minecraft.getInstance().getSession().setUsername(username);
                                                      ^
        符号:   方法 setUsername(String)
        位置: 类 Session
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/env/EnvServer.java:376: 错误: 找不到符号
                  ReplaySender.getInstance().loadWorldFromZip(saveZipFile);
                  ^
        符号:   变量 ReplaySender
        位置: 类 EnvServer
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/env/EnvServer.java:414: 错误: 找不到符号
                  MinecraftServer.setSpawnBiomePredicate( b -> b.getCategory().getName().equals(spawnBiome) );
                                 ^
        符号:   方法 setSpawnBiomePredicate((b)->b.get[...]iome))
        位置: 类 MinecraftServer
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/env/EnvServer.java:418: 错误: 找不到符号
                  MinecraftServer.setSpawnInVillage(true);
                                 ^
        符号:   方法 setSpawnInVillage(boolean)
        位置: 类 MinecraftServer
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/env/EnvServer.java:423: 错误: 找不到符号
              DimensionGeneratorSettings dms = DimensionGeneratorSettings.fromDynamicRegistries(DynamicRegistries.getImpl(), seed, generateFeatures, bonusChest);
                                                                                                                 ^
        符号:   方法 getImpl()
        位置: 类 DynamicRegistries
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/env/EnvServer.java:424: 错误: 找不到符号
              mc.createWorld(worldName, worldSettings, DynamicRegistries.getImpl(), dms);
                                                                        ^
        符号:   方法 getImpl()
        位置: 类 DynamicRegistries
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/env/EnvServer.java:428: 错误: 找不到符号
              Set<String> biomeCategories = DynamicRegistries.getImpl().getRegistry(Registry.BIOME_KEY).getEntries().stream()
                                                             ^
        符号:   方法 getImpl()
        位置: 类 DynamicRegistries
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/env/EnvServer.java:602: 错误: 找不到符号
              MouseHelper.State mouseState = constructMouseState(actions);
                         ^
        符号:   类 State
        位置: 类 MouseHelper
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/env/EnvServer.java:604: 错误: 找不到符号
              ReplaySender.getInstance().addAction(mouseState, keysState);
              ^
        符号:   变量 ReplaySender
        位置: 类 EnvServer
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/env/EnvServer.java:662: 错误: 找不到符号
              return new MouseHelper.State(0, 0, dx, dy, dwheel, buttonsPressed, Collections.emptyList());
                                    ^
        符号:   类 State
        位置: 类 MouseHelper
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/env/EnvServer.java:717: 错误: 找不到符号
              ReplaySender.getInstance().stop();
              ^
        符号:   变量 ReplaySender
        位置: 类 EnvServer
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/recorder/PlayRecorder.java:140: 错误: 找不到符号
                          is.saveAndUploadWorld(filename + ".zip");
                            ^
        符号:   方法 saveAndUploadWorld(String)
        位置: 类型为IntegratedServer的变量 is
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/recorder/PlayRecorder.java:141: 错误: 找不到符号
                          is.setUploadPath(azurePath);
                            ^
        符号:   方法 setUploadPath(String)
        位置: 类型为IntegratedServer的变量 is
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/recorder/PlayRecorder.java:142: 错误: 找不到符号
                          is.setAutosavePeriod(saveStatePeriod);
                            ^
        符号:   方法 setAutosavePeriod(int)
        位置: 类型为IntegratedServer的变量 is
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/recorder/PlayRecorder.java:143: 错误: 找不到符号
                          is.setWorldZipPrefix(filename);
                            ^
        符号:   方法 setWorldZipPrefix(String)
        位置: 类型为IntegratedServer的变量 is
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/recorder/PlayRecorder.java:147: 错误: 找不到符号
                  if (ReplaySender.getInstance().getMode() == ReplaySender.Mode.OFF) {
                      ^
        符号:   变量 ReplaySender
        位置: 类 PlayRecorder
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/recorder/PlayRecorder.java:147: 错误: 程序包ReplaySender不存在
                  if (ReplaySender.getInstance().getMode() == ReplaySender.Mode.OFF) {
                                                                          ^
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/recorder/PlayRecorder.java:148: 错误: 找不到符号
                      ReplaySender.getInstance().sendFromEnv();
                      ^
        符号:   变量 ReplaySender
        位置: 类 PlayRecorder
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/recorder/PlayRecorder.java:186: 错误: 找不到符号
                  mc.mouseHelper.setHumanInput(true);
                                ^
        符号:   方法 setHumanInput(boolean)
        位置: 类型为MouseHelper的变量 mouseHelper
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/recorder/PlayRecorder.java:189: 错误: 找不到符号
                  mc.mouseHelper.setHumanInput(false);
                                ^
        符号:   方法 setHumanInput(boolean)
        位置: 类型为MouseHelper的变量 mouseHelper
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/recorder/PlayRecorder.java:200: 错误: 找不到符号
              mc.mouseHelper.clearState();
                            ^
        符号:   方法 clearState()
        位置: 类型为MouseHelper的变量 mouseHelper
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/recorder/PlayRecorder.java:218: 错误: 找不到符号
                      mouseState = gson.toJsonTree(mc.mouseHelper.getState());
                                                                 ^
        符号:   方法 getState()
        位置: 类型为MouseHelper的变量 mouseHelper
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/recorder/PlayRecorder.java:241: 错误: 找不到符号
                      actions.addProperty("serverTickDurationMs", mc.getIntegratedServer().getTickTimeRaw());
                                                                                          ^
        符号:   方法 getTickTimeRaw()
        位置: 类 IntegratedServer
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/recorder/PlayRecorder.java:243: 错误: 找不到符号
                  if (ReplaySender.getInstance().getMode() == ReplaySender.Mode.EXEC_CMD && mc.gameSettings.envPort == 0) {
                      ^
        符号:   变量 ReplaySender
        位置: 类 PlayRecorder
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/recorder/PlayRecorder.java:243: 错误: 程序包ReplaySender不存在
                  if (ReplaySender.getInstance().getMode() == ReplaySender.Mode.EXEC_CMD && mc.gameSettings.envPort == 0) {
                                                                          ^
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/recorder/PlayRecorder.java:244: 错误: 找不到符号
                      ReplaySender.getInstance().addAction(actions);
                      ^
        符号:   变量 ReplaySender
        位置: 类 PlayRecorder
      /tmp/pip-req-build-2ta_yraf/minerl/MCP-Reborn/src/main/java/com/minerl/multiagent/recorder/PlayRecorder.java:287: 错误: 找不到符号
                  mc.mouseHelper.setHumanInput(true);
                                ^
        符号:   方法 setHumanInput(boolean)
        位置: 类型为MouseHelper的变量 mouseHelper
      注: 某些输入文件使用或覆盖了已过时的 API。
      注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
      注: 某些输入文件使用了未经检查或不安全的操作。
      注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
      49 个错误
      
      > Task :compileJava FAILED
      
      FAILURE: Build failed with an exception.
      
      * What went wrong:
      Execution failed for task ':compileJava'.
      > Compilation failed; see the compiler error output for details.
      
      * Try:
      Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
      
      * Get more help at https://help.gradle.org
      
      Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
      Use '--warning-mode all' to show the individual deprecation warnings.
      See https://docs.gradle.org/6.8.1/userguide/command_line_interface.html#sec:command_line_warnings
      
      BUILD FAILED in 14s
      6 actionable tasks: 6 executed
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-2ta_yraf/setup.py", line 214, in <module>
          prep_mcp()
        File "/tmp/pip-req-build-2ta_yraf/setup.py", line 198, in prep_mcp
          subprocess.check_call('{} clean build shadowJar'.format(gradlew).split(' '), cwd=workdir)
        File "/home/gjb/anaconda3/envs/minedreamer/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['./gradlew', 'clean', 'build', 'shadowJar']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Miffyli** [comment]
Hey. Make sure you are running JDK 8 with `java --version` and `javac --version`. Compilation issues usually happen due to wrong JDK version.

Also, there are mentions of "could not set file permissions" in the log before compilation messages. I am not sure why this is happening (it says "too many files open"), but it could also impact the compilation phase.
