### ISSUE TITLE
Unable to run mineRL environment; zombie processes

### ISSUE THREAD

**Issue by carolinezhang1** [minerllabs/minerl#781]
Hello! I have been trying to set up mineRL on my computer and have been running into some issues with trying to run the environment setup code, specifically this command: obs = env.reset()

The process stops and I get these errors: 
`DEBUG:minerl.env.malmo.instance.500b73:[14:35:19] [EnvServerSocketHandler/INFO]: [STDOUT]: *** Stopping the replay, returning control to the inputs
INFO:process_watcher:Zombie process found in process tree.
INFO:process_watcher:Process psutil.Popen(pid=4700, name='bash', status='zombie', started='14:34:31') does not exist or is zombie.`

I use a Macbook computer with an Apple Silicon Chip, have Java 8, and installed mineRL using the instructions on the website. I would really appreciate any help with troubleshooting, thank you so much!

Also, here is the full log: 
`DeprecationWarning: 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
  return concat(self.root_render_func(self.new_context(vars)))
<template>:23: DeprecationWarning: 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
<template>:15: DeprecationWarning: 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
<template>:16: DeprecationWarning: 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
<template>:17: DeprecationWarning: 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
INFO:minerl.env.malmo.instance.500b73:Starting Minecraft process: RuntimeWarning: 'minerl.utils.process_watcher' found in sys.modules after import of package 'minerl.utils', but prior to execution of 'minerl.utils.process_watcher'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
INFO:process_watcher:Process watcher daemonizer launched successfully.
DEBUG:minerl.env.malmo.instance.500b73:SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
DEBUG:minerl.env.malmo.instance.500b73:SLF4J: Defaulting to no-operation (NOP) logger implementation
DEBUG:minerl.env.malmo.instance.500b73:SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
DEBUG:minerl.env.malmo.instance.500b73:[14:34:46] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
DEBUG:minerl.env.malmo.instance.500b73:[14:34:47] [Render thread/INFO]: Setting user: Player686
DEBUG:minerl.env.malmo.instance.500b73:[14:34:47] [Render thread/INFO]: Backend library: LWJGL version 3.2.1 SNAPSHOT
ERROR:minerl.env.malmo.instance.500b73:[14:34:48] [Render thread/ERROR]: GLFW error collected during initialization: GLFW error during init: [0x10008]13117847264
DEBUG:minerl.env.malmo.instance.500b73:[14:34:50] [Render thread/INFO]: Reloading ResourceManager: Default
DEBUG:minerl.env.malmo.instance.500b73:[14:34:51] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
DEBUG:minerl.env.malmo.instance.500b73:[14:34:55] [Render thread/INFO]: OpenAL initialized.
DEBUG:minerl.env.malmo.instance.500b73:[14:34:55] [Render thread/INFO]: Sound engine started
DEBUG:minerl.env.malmo.instance.500b73:[14:34:55] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
DEBUG:minerl.env.malmo.instance.500b73:[14:34:55] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
DEBUG:minerl.env.malmo.instance.500b73:[14:34:55] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
DEBUG:minerl.env.malmo.instance.500b73:[14:34:55] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
DEBUG:minerl.env.malmo.instance.500b73:[14:34:55] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
DEBUG:minerl.env.malmo.instance.500b73:[14:34:55] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
DEBUG:minerl.env.malmo.instance.500b73:[14:34:55] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
DEBUG:minerl.env.malmo.instance.500b73:[14:34:56] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
DEBUG:minerl.env.malmo.instance.500b73:[14:34:56] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
DEBUG:minerl.env.malmo.instance.500b73:[14:34:56] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
DEBUG:minerl.env.malmo.instance.500b73:[14:34:57] [Thread-3/INFO]: [STDOUT]: ***** Start MalmoEnvServer on port 9070
DEBUG:minerl.env.malmo.instance.500b73:[14:34:57] [Thread-3/INFO]: [STDOUT]: CLIENT enter state: DORMANT
INFO:minerl.env.malmo.instance.500b73:Minecraft process ready
INFO:minerl.env.malmo:Logging output of Minecraft to ./logs/mc_70.log
DEBUG:minerl.env._multiagent:Creating socket connection Malmo[None:500b73, proc=4700, addr=localhost:9070, locked=True]
DEBUG:minerl.env.malmo.instance.500b73:[14:34:57] [Thread-3/INFO]: [STDOUT]: SERVER enter state: DORMANT
DEBUG:minerl.env._multiagent:Saying hello for client: Malmo[None:500b73, proc=4700, addr=localhost:9070, locked=True]
INFO:minerl.env._multiagent:Attempting to quit: Malmo[None:500b73, proc=4700, addr=localhost:9070, locked=True]
DEBUG:minerl.env._multiagent:Sending mission init: Malmo[None:500b73, proc=4700, addr=localhost:9070, locked=True]
DEBUG:minerl.env.malmo.instance.500b73:[14:34:57] [EnvServerSocketHandler/INFO]: Received Mission token 8f753766-6b5d-4eeb-bb73-bb8b84bb5af7:0:0:1:true
DEBUG:minerl.env.malmo.instance.500b73:[14:34:57] [EnvServerSocketHandler/INFO]: Received mission init command  <MissionInit xmlns="http://ProjectMalmo.microsoft.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" SchemaVersion="" PlatformVersion="0.37.0"><Mission><About><Summary>MineRLBasaltBuildVillageHouse-v0</Summary></About><ModSettings><MsPerTick>50</MsPerTick></ModSettings><ServerSection><ServerInitialConditions><Time><AllowPassageOfTime>false</AllowPassageOfTime></Time><AllowSpawning>true</AllowSpawning></ServerInitialConditions><ServerHandlers><DefaultWorldGenerator forceReset="true" generatorOptions="{}"/><ServerQuitFromTimeUp timeLimitMs="720000" description="out_of_time"/><ServerQuitWhenAnyAgentFinishes/></ServerHandlers></ServerSection><AgentSection mode="Survival"><Name>MineRLAgent0</Name><AgentStart><LowLevelInputs>true</LowLevelInputs><GuiScale>1.0</GuiScale><GammaSetting>2.0</GammaSetting><FOVSetting>70.0</FOVSetting><FakeCursorSize>16</FakeCursorSize><Inventory><InventoryObject slot="0" type="stone_pickaxe" quantity="1"/><InventoryObject slot="1" type="stone_axe" quantity="1"/><InventoryObject slot="2" type="cobblestone" quantity="64"/><InventoryObject slot="3" type="oak_log" quantity="64"/><InventoryObject slot="4" type="glass_pane" quantity="64"/><InventoryObject slot="5" type="torch" quantity="64"/><InventoryObject slot="6" type="dirt" quantity="64"/><InventoryObject slot="7" type="grass_block" quantity="64"/><InventoryObject slot="8" type="poppy" quantity="64"/><InventoryObject slot="9" type="spruce_log" quantity="64"/><InventoryObject slot="10" type="acacia_log" quantity="64"/><InventoryObject slot="11" type="jungle_log" quantity="64"/><InventoryObject slot="12" type="sand" quantity="64"/><InventoryObject slot="13" type="sandstone" quantity="64"/><InventoryObject slot="14" type="smooth_sandstone" quantity="64"/><InventoryObject slot="15" type="terracotta" quantity="64"/><InventoryObject slot="16" type="packed_ice" quantity="64"/><InventoryObject slot="17" type="snow_block" quantity="64"/><InventoryObject slot="18" type="cobweb" quantity="64"/><InventoryObject slot="19" type="white_wool" quantity="64"/><InventoryObject slot="20" type="black_dye" quantity="64"/><InventoryObject slot="21" type="blue_dye" quantity="64"/><InventoryObject slot="22" type="brown_dye" quantity="64"/><InventoryObject slot="23" type="green_dye" quantity="64"/><InventoryObject slot="24" type="red_dye" quantity="64"/><InventoryObject slot="25" type="white_dye" quantity="64"/><InventoryObject slot="26" type="yellow_dye" quantity="64"/><InventoryObject slot="27" type="flower_pot" quantity="64"/><InventoryObject slot="28" type="cactus" quantity="64"/><InventoryObject slot="29" type="lantern" quantity="64"/></Inventory><PreferredSpawnBiome>plains</PreferredSpawnBiome><DoneOnDeath>true</DoneOnDeath><SpawnInVillage>true</SpawnInVillage></AgentStart><AgentHandlers><FileBasedPerformanceProducer/><PauseCommand/><VideoProducer want_depth="false"><Width>640</Width><Height>360</Height></VideoProducer><HumanLevelCommands/><CameraCommands/></AgentHandlers></AgentSection></Mission><ExperimentUID>8f753766-6b5d-4eeb-bb73-bb8b84bb5af7</ExperimentUID><ClientRole>0</ClientRole><ClientAgentConnection><ClientIPAddress>127.0.0.1</ClientIPAddress><ClientMissionControlPort>0</ClientMissionControlPort><ClientCommandsPort>0</ClientCommandsPort><AgentIPAddress>127.0.0.1</AgentIPAddress><AgentMissionControlPort>0</AgentMissionControlPort><AgentVideoPort>0</AgentVideoPort><AgentDepthPort>0</AgentDepthPort><AgentLuminancePort>0</AgentLuminancePort><AgentObservationsPort>0</AgentObservationsPort><AgentRewardsPort>0</AgentRewardsPort><AgentColourMapPort>0</AgentColourMapPort></ClientAgentConnection></MissionInit>
DEBUG:minerl.env.malmo.instance.500b73:[14:34:57] [EnvServerSocketHandler/INFO]: [STDOUT]: Setting width, height to 640, 360
DEBUG:minerl.env.malmo.instance.500b73:[14:34:57] [EnvServerSocketHandler/INFO]: [STDOUT]: Gamma: 2.0
DEBUG:minerl.env.malmo.instance.500b73:[14:34:57] [EnvServerSocketHandler/INFO]: [STDOUT]: FOV: 70.0
DEBUG:minerl.env.malmo.instance.500b73:[14:34:57] [Sound engine/FATAL]: Error executing task on Sound executor
ERROR:minerl.env.malmo.instance.500b73:java.lang.NullPointerException: null
DEBUG:minerl.env.malmo.instance.500b73: at net.minecraft.client.audio.ChannelManager.lambda$tick$3(ChannelManager.java:57) ~[mcprec-6.13.jar:?]
DEBUG:minerl.env.malmo.instance.500b73: at net.minecraft.util.concurrent.ThreadTaskExecutor.run(ThreadTaskExecutor.java:136) ~[mcprec-6.13.jar:?]
DEBUG:minerl.env.malmo.instance.500b73: at net.minecraft.util.concurrent.ThreadTaskExecutor.driveOne(ThreadTaskExecutor.java:109) ~[mcprec-6.13.jar:?]
DEBUG:minerl.env.malmo.instance.500b73: at net.minecraft.util.concurrent.ThreadTaskExecutor.driveUntil(ThreadTaskExecutor.java:119) ~[mcprec-6.13.jar:?]
DEBUG:minerl.env.malmo.instance.500b73: at net.minecraft.client.audio.SoundEngineExecutor.run(SoundEngineExecutor.java:39) ~[mcprec-6.13.jar:?]
DEBUG:minerl.env.malmo.instance.500b73: at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
DEBUG:minerl.env.malmo.instance.500b73:[14:34:57] [EnvServerSocketHandler/INFO]: [STDOUT]: GuiScale: 1.0
DEBUG:minerl.env.malmo.instance.500b73:[14:34:57] [Render thread/INFO]: [STDOUT]: Seed not provided, generating random one: -4632864742680281746
WARNING:minerl.env.malmo.instance.500b73:[14:34:58] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
WARNING:minerl.env.malmo.instance.500b73:[14:34:58] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
WARNING:minerl.env.malmo.instance.500b73:[14:34:58] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
WARNING:minerl.env.malmo.instance.500b73:[14:34:58] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
WARNING:minerl.env.malmo.instance.500b73:[14:34:58] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
DEBUG:minerl.env.malmo.instance.500b73:[14:34:58] [Render thread/INFO]: Reloading ResourceManager: Default
DEBUG:minerl.env.malmo.instance.500b73:[14:34:59] [Render thread/INFO]: Loaded 7 recipes
DEBUG:minerl.env.malmo.instance.500b73:[14:34:59] [Render thread/INFO]: Loaded 927 advancements
DEBUG:minerl.env.malmo.instance.500b73:[14:35:00] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
DEBUG:minerl.env.malmo.instance.500b73:[14:35:00] [Render thread/INFO]: Starting integrated minecraft server version 1.16.5
DEBUG:minerl.env.malmo.instance.500b73:[14:35:00] [Render thread/INFO]: Generating keypair
DEBUG:minerl.env.malmo.instance.500b73:[14:35:06] [Render thread/INFO]: Preparing start region for dimension minecraft:overworld
DEBUG:minerl.env.malmo.instance.500b73:[14:35:12] [Render thread/INFO]: Changing view distance to 11, from 10
DEBUG:minerl.env.malmo.instance.500b73:[14:35:13] [Render thread/INFO]: MineRLAgent0[local:E:2b26dc80] logged in with entity id 203 at (-221.5, 65.0, -1441.5)
DEBUG:minerl.env.malmo.instance.500b73:[14:35:13] [Render thread/INFO]: MineRLAgent0 joined the game
DEBUG:minerl.env.malmo.instance.500b73:[14:35:13] [Render thread/INFO]: [STDOUT]: *** creating fake mouse cursor ***
DEBUG:minerl.env.malmo.instance.500b73:[14:35:13] [Render thread/INFO]: Preparing spawn area: 19%
DEBUG:minerl.env.malmo.instance.500b73:[14:35:13] [Render thread/INFO]: Time elapsed: 2 ms
DEBUG:minerl.env.malmo.instance.500b73:[14:35:14] [Render thread/INFO]: [STDOUT]: Starting new video null
DEBUG:minerl.env.malmo.instance.500b73:[14:35:14] [Render thread/INFO]: Saving and pausing game...
DEBUG:minerl.env.malmo.instance.500b73:[14:35:14] [Render thread/INFO]: Saving chunks for level 'ServerLevel[mcpworld4ee8ef4a30a2]'/minecraft:overworld
DEBUG:minerl.env.malmo.instance.500b73:[14:35:14] [Render thread/INFO]: Saving chunks for level 'ServerLevel[mcpworld4ee8ef4a30a2]'/minecraft:the_nether
DEBUG:minerl.env.malmo.instance.500b73:[14:35:14] [Render thread/INFO]: Saving chunks for level 'ServerLevel[mcpworld4ee8ef4a30a2]'/minecraft:the_end
DEBUG:minerl.env.malmo.instance.500b73:[14:35:15] [Render thread/INFO]: MineRLAgent0 has made the advancement [Getting an Upgrade]
DEBUG:minerl.env.malmo.instance.500b73:[14:35:15] [Render thread/INFO]: MineRLAgent0 has made the advancement [Stone Age]
DEBUG:minerl.env.malmo.instance.500b73:[14:35:15] [Render thread/INFO]: [CHAT] MineRLAgent0 has made the advancement [Getting an Upgrade]
DEBUG:minerl.env.malmo.instance.500b73:[14:35:15] [Render thread/INFO]: [CHAT] MineRLAgent0 has made the advancement [Stone Age]
DEBUG:minerl.env.malmo.instance.500b73:[14:35:15] [Render thread/INFO]: Loaded 138 advancements
DEBUG:minerl.env._multiagent:Peeking the clients.
DEBUG:minerl.env.malmo.instance.500b73:[14:35:19] [EnvServerSocketHandler/INFO]: [STDOUT]: *** Stopping the replay, returning control to the inputs
INFO:process_watcher:Zombie process found in process tree.
INFO:process_watcher:Process psutil.Popen(pid=4700, name='bash', status='zombie', started='14:34:31') does not exist or is zombie.`

**Comment by Miffyli** [comment]
Hey. Installing MineRL on newer Macs requires additional steps. See instructions here: https://github.com/minerllabs/minerl/issues/659#issuecomment-1306635414 

Edit: I just saw you commented on that thread as well. Unfortunately I do not have good tips to give here. Usually glfw (or any rendering) errors happen because of lack of display (i.e. you need to run things with xvfb-run), but with Macs this should not be the case.
