### ISSUE TITLE
Minecraft gets stuck if env.reset() is run again within short interval of time 

### ISSUE THREAD

**Issue by Mrugankakarte** [minerllabs/minerl#80]
Hi @MadcowD ,

With reference to issue posted [here](https://discourse.aicrowd.com/t/resetting-environment/1266/3), here is my notebook.

[Test Notebook.zip](https://github.com/minerllabs/minerl/files/3313498/Test.Notebook.zip)

As mentioned, `env.reset()` works if I wait for a min or two before running it again, but gets stuck otherwise. Please let me know if I am doing something wrong.

**Comment by Mrugankakarte** [comment]
I have added HTML file as well in case you don't see the errors in notebook.
[Test Notebook.zip](https://github.com/minerllabs/minerl/files/3313608/Test.Notebook.zip)

**Comment by MadcowD** [comment]
Are you on windows or *nix?

**Comment by SaminYeasar** [comment]
I'm sort getting similar issue with env.reset()
error:
Failed to reset (timeout), trying again!
[18:38:52] [EnvServerSocketHandler/INFO]: [STDERR]: java.io.EOFException
[18:38:52] [EnvServerSocketHandler/INFO]: [STDERR]: 	at java.io.DataInputStream.readInt(DataInputStream.java:392)
[18:38:52] [EnvServerSocketHandler/INFO]: [STDERR]: 	at com.microsoft.Malmo.Client.MalmoEnvServer$1.run(MalmoEnvServer.java:143)
[18:38:52] [EnvServerSocketHandler/INFO]: [STDOUT]: [ERROR] MalmoEnv socket error: java.io.EOFException (can be on disconnect)
Failed to reset (timeout), trying again!
Connection with Minecraft client cleaned more than once; restarting.
[18:43:04] [EnvServerSocketHandler/INFO]: [STDERR]: java.io.EOFException
[18:43:04] [EnvServerSocketHandler/INFO]: [STDERR]: 	at java.io.DataInputStream.readInt(DataInputStream.java:392)
[18:43:04] [EnvServerSocketHandler/INFO]: [STDERR]: 	at com.microsoft.Malmo.Client.MalmoEnvServer$1.run(MalmoEnvServer.java:143)
[18:43:04] [EnvServerSocketHandler/INFO]: [STDOUT]: [ERROR] MalmoEnv socket error: java.io.EOFException (can be on disconnect)

**Comment by SaminYeasar** [comment]
Updated to version 0.1.13 now getting the following:

Failed to reset (socket error), trying again!
Cleaning connection! Somethong must have gone wrong.
Failed to reset (socket error), trying again!
Cleaning connection! Somethong must have gone wrong.
Connection with Minecraft client cleaned more than once; restarting.

**Comment by MadcowD** [comment]
https://gist.github.com/MadcowD/d18d3e06c75181ca35b1a8b9816359d7

**Comment by Mrugankakarte** [comment]
Hi @MadcowD,

After updating to 0.1.13, I can't get the mission to start. Everytime I run the line `state, _ = env.reset()` I get error.
```
Failed to reset (socket error), trying again!
Cleaning connection! Somethong must have gone wrong.
Failed to reset (socket error), trying again!
Cleaning connection! Somethong must have gone wrong.
Connection with Minecraft client cleaned more than once; restarting.

Failed to delete the temporary minecraft directory.

Attempted to send kill command to minecraft process and failed.

timed out
```

The mission never starts and after sometime new Minecraft window opens, and this keeps repeating.

```
---------------------------------------------------------------------------
ConnectionRefusedError                    Traceback (most recent call last)
C:\Mrugank_pc\Softwares\Python\Anaconda3_5.1.0\lib\site-packages\minerl\env\core.py in _start_up(self)
    392                 sock.settimeout(SOCKTIME)
--> 393                 sock.connect((self.instance.host, self.instance.port))
    394                 self._hello(sock)

ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-4-041d6286fe1a> in <module>
      2 done = False
      3 
----> 4 state, _ = env.reset()
      5 while not done:
      6     #action = get_action(state) #This should generate error as get_action() is not defined

C:\Mrugank_pc\Softwares\Python\Anaconda3_5.1.0\lib\site-packages\gym\wrappers\time_limit.py in reset(self, **kwargs)
     22     def reset(self, **kwargs):
     23         self._elapsed_steps = 0
---> 24         return self.env.reset(**kwargs)

C:\Mrugank_pc\Softwares\Python\Anaconda3_5.1.0\lib\site-packages\minerl\env\core.py in reset(self)
    378                 time.sleep(0.1)
    379 
--> 380         return self._start_up()
    381 
    382     @retry

C:\Mrugank_pc\Softwares\Python\Anaconda3_5.1.0\lib\site-packages\minerl\env\comms.py in wrapper(*args, **kwargs)
     37         for i in range(retry_count):
     38             try:
---> 39                 return func(*args, **kwargs)
     40             except Pyro4.errors.PyroError as e:
     41                 logger.error("An error occurred contacting the instance manager. Is it started!?")

C:\Mrugank_pc\Softwares\Python\Anaconda3_5.1.0\lib\site-packages\minerl\env\core.py in _start_up(self)
    402         except (socket.timeout, socket.error) as e:
    403             logger.error("Failed to reset (socket error), trying again!")
--> 404             self._clean_connection()
    405             raise e
    406 

C:\Mrugank_pc\Softwares\Python\Anaconda3_5.1.0\lib\site-packages\minerl\env\core.py in _clean_connection(self)
    422             if self.instance:
    423                 self.instance.kill()
--> 424             self.instance = InstanceManager.get_instance()
    425             self.had_to_clean = False
    426         else:

C:\Mrugank_pc\Softwares\Python\Anaconda3_5.1.0\lib\site-packages\minerl\env\malmo.py in get_instance(cls)
     98             if len(cls._instance_pool) < cls.MAXINSTANCES:
     99                 cls.ninstances += 1
--> 100                 inst = cls.Instance(cls._get_valid_port())
    101                 cls._instance_pool.append(inst)
    102                 inst._acquire_lock()

C:\Mrugank_pc\Softwares\Python\Anaconda3_5.1.0\lib\site-packages\minerl\env\malmo.py in __init__(self, port, existing)
    278 
    279             # Launch the instance!
--> 280             self.launch(port, existing)
    281 
    282 

C:\Mrugank_pc\Softwares\Python\Anaconda3_5.1.0\lib\site-packages\minerl\env\malmo.py in launch(self, port, existing)
    288                 self.instance_dir = tempfile.mkdtemp()
    289                 self.minecraft_dir = os.path.join(self.instance_dir, 'Minecraft')
--> 290                 shutil.copytree(os.path.join(InstanceManager.MINECRAFT_DIR), self.minecraft_dir)
    291                 shutil.copytree(os.path.join(InstanceManager.SCHEMAS_DIR), os.path.join(self.instance_dir, 'Schemas'))
    292 

C:\Mrugank_pc\Softwares\Python\Anaconda3_5.1.0\lib\shutil.py in copytree(src, dst, symlinks, ignore, copy_function, ignore_dangling_symlinks)
    346                         copy_function(srcname, dstname)
    347             elif os.path.isdir(srcname):
--> 348                 copytree(srcname, dstname, symlinks, ignore, copy_function)
    349             else:
    350                 # Will raise a SpecialFileError for unsupported file types

C:\Mrugank_pc\Softwares\Python\Anaconda3_5.1.0\lib\shutil.py in copytree(src, dst, symlinks, ignore, copy_function, ignore_dangling_symlinks)
    346                         copy_function(srcname, dstname)
    347             elif os.path.isdir(srcname):
--> 348                 copytree(srcname, dstname, symlinks, ignore, copy_function)
    349             else:
    350                 # Will raise a SpecialFileError for unsupported file types

C:\Mrugank_pc\Softwares\Python\Anaconda3_5.1.0\lib\shutil.py in copytree(src, dst, symlinks, ignore, copy_function, ignore_dangling_symlinks)
    346                         copy_function(srcname, dstname)
    347             elif os.path.isdir(srcname):
--> 348                 copytree(srcname, dstname, symlinks, ignore, copy_function)
    349             else:
    350                 # Will raise a SpecialFileError for unsupported file types

C:\Mrugank_pc\Softwares\Python\Anaconda3_5.1.0\lib\shutil.py in copytree(src, dst, symlinks, ignore, copy_function, ignore_dangling_symlinks)
    346                         copy_function(srcname, dstname)
    347             elif os.path.isdir(srcname):
--> 348                 copytree(srcname, dstname, symlinks, ignore, copy_function)
    349             else:
    350                 # Will raise a SpecialFileError for unsupported file types

C:\Mrugank_pc\Softwares\Python\Anaconda3_5.1.0\lib\shutil.py in copytree(src, dst, symlinks, ignore, copy_function, ignore_dangling_symlinks)
    346                         copy_function(srcname, dstname)
    347             elif os.path.isdir(srcname):
--> 348                 copytree(srcname, dstname, symlinks, ignore, copy_function)
    349             else:
    350                 # Will raise a SpecialFileError for unsupported file types

C:\Mrugank_pc\Softwares\Python\Anaconda3_5.1.0\lib\shutil.py in copytree(src, dst, symlinks, ignore, copy_function, ignore_dangling_symlinks)
    346                         copy_function(srcname, dstname)
    347             elif os.path.isdir(srcname):
--> 348                 copytree(srcname, dstname, symlinks, ignore, copy_function)
    349             else:
    350                 # Will raise a SpecialFileError for unsupported file types

C:\Mrugank_pc\Softwares\Python\Anaconda3_5.1.0\lib\shutil.py in copytree(src, dst, symlinks, ignore, copy_function, ignore_dangling_symlinks)
    346                         copy_function(srcname, dstname)
    347             elif os.path.isdir(srcname):
--> 348                 copytree(srcname, dstname, symlinks, ignore, copy_function)
    349             else:
    350                 # Will raise a SpecialFileError for unsupported file types

C:\Mrugank_pc\Softwares\Python\Anaconda3_5.1.0\lib\shutil.py in copytree(src, dst, symlinks, ignore, copy_function, ignore_dangling_symlinks)
    327         dstname = os.path.join(dst, name)
    328         try:
--> 329             if os.path.islink(srcname):
    330                 linkto = os.readlink(srcname)
    331                 if symlinks:

C:\Mrugank_pc\Softwares\Python\Anaconda3_5.1.0\lib\ntpath.py in islink(path)
    251     """
    252     try:
--> 253         st = os.lstat(path)
    254     except (OSError, AttributeError):
    255         return False

KeyboardInterrupt: 

```

**Comment by Mrugankakarte** [comment]
Downgrading to 0.1.12 also didn't help.

**Comment by katja-hofmann** [comment]
I ran into the same issue. Downgrading to 0.1.9 worked for me.

**Comment by MadcowD** [comment]
@Katja-Hofmann and all else,

Would you please run your 1.13 scripts with `logging.basicConfig(level=logging.DEBUG)`

**Comment by MadcowD** [comment]
@Mrugankakarte It would be great if I could see your logs

**Comment by Mrugankakarte** [comment]
Hi @MadcowD,

Here are my logs.
[minecraft_logs.log](https://github.com/minerllabs/minerl/files/3319546/minecraft_logs.log)

Is the issue fixed? I couldn't install new minerl version..pip says 0.1.13 is the latest one.

**Comment by MadcowD** [comment]
@Mrugankakarte You can update now!

**Comment by MadcowD** [comment]
Anyone who has upgraded is this error fixed?
Make sure to upgrade to `minerl` v`0.1.15`!
```
pip3 install --upgrade minerl
```

**Comment by Mrugankakarte** [comment]
Hi @MadcowD ,

After updating to `0.1.15` I couldn't get the mission to start. Tried 2 times, same error `Malmo busy`
Here are my logs.
[minecraft_logs.log](https://github.com/minerllabs/minerl/files/3328815/minecraft_logs.log)
[minecraft_logs2.log](https://github.com/minerllabs/minerl/files/3328816/minecraft_logs2.log)
