### ISSUE TITLE
MineRL suddenly gets stuck: Biome null pointer.

### ISSUE THREAD

**Issue by keisuke-nakata** [minerllabs/minerl#87]
Potentially related (maybe): #80 , #79  

MineRL got stuck suddenly when an agent tried to `step`, but I could not find the cause of this issue.  
Here are the `logs/` files:

[minecraft_proc_9001.log](https://github.com/minerllabs/minerl/files/3318920/minecraft_proc_9001.log)
[minecraft_proc_9002.log](https://github.com/minerllabs/minerl/files/3318921/minecraft_proc_9002.log)
[minecraft_proc_9003.log](https://github.com/minerllabs/minerl/files/3318922/minecraft_proc_9003.log)

Python 3.5.2, MineRL 0.1.12 (commit `75b5416eb97859971e3a8edbda670378fcbad709`)

**Comment by keisuke-nakata** [comment]
In this case, MineRL did not fail with error.  
I'm happy if MineRL raises some errors with this issue, in order to find the script stopped.

**Comment by MadcowD** [comment]
@keisuke-nakata  Can you try with MineRL 0.1.14?

Thanks.

**Comment by MadcowD** [comment]
This appears to be the issue:
```
[12:51:58] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.terraingen.WorldTypeEvent$InitBiomeGens@4f06f43f:
java.lang.NullPointerException
	at com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation.onBiomeGenInit(BiomeGeneratorImplementation.java:87) ~[BiomeGeneratorImplementation.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_21_BiomeGeneratorImplementation_onBiomeGenInit_InitBiomeGens.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraft.world.biome.BiomeProvider.getModdedBiomeGenerators(BiomeProvider.java:242) [BiomeProvider.class:?]
	at net.minecraft.world.biome.BiomeProvider.<init>(BiomeProvider.java:45) [BiomeProvider.class:?]
	at net.minecraft.world.biome.BiomeProvider.<init>(BiomeProvider.java:52) [BiomeProvider.class:?]
	at net.minecraft.world.WorldType.getBiomeProvider(WorldType.java:169) [WorldType.class:?]
	at net.minecraft.world.WorldProvider.init(WorldProvider.java:73) [WorldProvider.class:?]
	at net.minecraft.world.WorldProvider.setWorld(WorldProvider.java:49) [WorldProvider.class:?]
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:75) [WorldClient.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleJoinGame(NetHandlerPlayClient.java:309) [NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.SPacketJoinGame.processPacket(SPacketJoinGame.java:89) [SPacketJoinGame.class:?]
	at net.minecraft.network.play.server.SPacketJoinGame.processPacket(SPacketJoinGame.java:13) [SPacketJoinGame.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:21) [PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at net.minecraft.util.Util.runTask(Util.java:29) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:3450) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:407) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
[12:51:58] [Client thread/ERROR] [FML]: Index: 192 Listeners:
[12:51:58] [Client thread/ERROR] [FML]: 0: LOWEST
[12:51:58] [Client thread/ERROR] [FML]: 1: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@7cbf2b90 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 2: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@30c6c12d onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 3: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@271b142 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 4: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@2fc0025c onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 5: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@a548a06 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 6: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@2fd0010d onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 7: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@65404635 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 8: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@7b6fee42 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 9: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@6b08577e onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 10: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@16baf1e1 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 11: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@565489ea onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 12: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@4ff1aab onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 13: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@f15218e onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 14: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@68d69a42 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 15: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@417ddba1 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 16: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@5741ff2f onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 17: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@32f1f5da onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 18: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@11198bfb onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 19: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@4af40c48 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 20: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@62f73fd9 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 21: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@286813b6 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 22: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@792f56a1 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 23: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@2ee0b92 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 24: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@4928d1cd onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 25: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@51a7322 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 26: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@3e6dd5e onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 27: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@4fb9b9f4 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 28: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@2ac3ae52 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 29: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@54ed6c1 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 30: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@4470b4df onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 31: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@4a817313 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 32: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@eee75f3 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 33: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@38126cba onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 34: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@14e6dbb6 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 35: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@16e5b115 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 36: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@1f9a05dd onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 37: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@2280242d onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 38: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@24cde6d4 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 39: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@6ba08ff onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 40: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@6c167a8e onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 41: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@7e4a1696 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 42: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@75339fc2 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 43: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@6711381d onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 44: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@2e4fc822 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 45: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@717ab820 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 46: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@563f3f5c onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
[12:51:58] [Client thread/ERROR] [FML]: 47: ASM: com.microsoft.Malmo.MissionHandlers.BiomeGeneratorImplementation@5d90b9a3 onBiomeGenInit(Lnet/minecraftforge/event/terraingen/WorldTypeEvent$InitBiomeGens;)V
```

**Comment by MadcowD** [comment]
Make sure to upgrade to 0.1.15!
```
pip3 install --upgrade minerl
```
This should give us better debug information.

Will

**Comment by keisuke-nakata** [comment]
MineRL got stuck in 5 out of 30 trials with MineRL==0.1.16.  

I checked the `logs/` and they showed same logs for all stuck trials.  
I'll attach the log files from stuck trials:
[87.zip](https://github.com/minerllabs/minerl/files/3343751/87.zip)

**Comment by MadcowD** [comment]
okay got it, I've implemented a temporary fix in an upcoming version of `minerl`.

What environment are you using?

**Comment by keisuke-nakata** [comment]
I'm using Docker image (which I personally created) and run containers on our company's cluster.  
Each container were allocated 12 cores CPU & 64 GiB RAM.  
And the disk is not super fast because I used NFS for experiments storage.

**Comment by MadcowD** [comment]
Okay, I'll make sure this new version gets pushed out ASAP.

**Comment by keisuke-nakata** [comment]
I'm suffering from this issue on MineRL v0.1.18.  
6 trials (out of 40) got stuck. I'll put the logs from stuck trials.

**Comment by keisuke-nakata** [comment]
I'm suffering this issue even on MineRL v0.1.18.  
6 trials (out of 40) got stuck. I'll put the logs from stuck trials.

All stuck tasks were "MineRLNavigate-v0" in this case.
(Not all "MineRLNavigate-v0" trials got stuck however)

[20190708_minerl_stuck_logs.zip](https://github.com/minerllabs/minerl/files/3366581/20190708_minerl_stuck_logs.zip)

**Comment by MadcowD** [comment]
This looks like a different error than before. (Just from the logs), can I make a new issue for this.

**Comment by MadcowD** [comment]
@keisuke-nakata  Which of these logs exhibit the issue?

**Comment by MadcowD** [comment]
Moving to #128
